// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const animeSeriesCharacters: Character[] = [
    {
        name: 'Ace of the Diamond',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2kqZX7OKVHkLm2XmI2AXxAd0MrA.jpg',
    },
    {
        name: "Adam's Sweet Agony",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1n1ZP0KHXUSvVxZG63x7aOzmO4M.jpg',
    },
    {
        name: "Atashin'chi",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bQCZvbyTJFWt3majCn37ykJBpIf.jpg',
    },
    {
        name: 'Attack on Titan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    },
    {
        name: 'B-PROJECT',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2GuZ8IRVYXkepzYZGz3kBsmr5ot.jpg',
    },
    {
        name: 'BEASTARS',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sh9iNWkleOjEHRHj8WPHhmMi8HL.jpg',
    },
    {
        name: 'Bleach',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5iVUUnE2tgBPypACYNobCKHagfV.jpg',
    },
    {
        name: 'Bungo Stray Dogs',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6AQmGhkYwAqW2OevjXbsh7tZnNO.jpg',
    },
    {
        name: 'Cardfight!! Vanguard',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mm0ULBbs9XrHq4OAE8VUa84wvgi.jpg',
    },
    {
        name: 'Chibi Maruko-chan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bfn54AAMuh47IFqeoco0jgeVH1a.jpg',
    },
    {
        name: 'Chihayafuru',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/x1yYnCaK8gLnLgQSnd9IGoapHbx.jpg',
    },
    {
        name: 'Chiikawa',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cXm3mxmlOWJZAyn5fqFI9JpARa3.jpg',
    },
    {
        name: 'Da Capo',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yaDB7CTZA8PatqVmPnfwBynA9SI.jpg',
    },
    {
        name: 'Death Note',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg',
    },
    {
        name: 'Detective Conan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rRIEFvHRy01OYzmXQBbGeW0Qilc.jpg',
    },
    {
        name: 'Doraemon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9ZN1P32SHviL3SV51qLivxycvcx.jpg',
    },
    {
        name: 'Doraemon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bHMqPDsW7Lb71CVHXq4PuEvQ4NY.jpg',
    },
    {
        name: 'Dragon Ball Z',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yfyToia25GnvjY7FPAGaCm3lKRc.jpg',
    },
    {
        name: 'Duel Masters',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/t5ijeKzOukACRktUfbjuMIlqwfr.jpg',
    },
    {
        name: 'Fairy Tail',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/h50lj7xO65qafNYZCrfQ7ztkMBD.jpg',
    },
    {
        name: 'Fighting Spirit',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1LApB9C9kEkh2ZU2vzAhurNDipl.jpg',
    },
    {
        name: "Frieren: Beyond Journey's End",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
    },
    {
        name: 'Fullmetal Alchemist: Brotherhood',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
    },
    {
        name: 'Haikyu!!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rBXEmHQaYoIAyOWRpu8v3cBGKcT.jpg',
    },
    {
        name: 'Hamtaro',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/heeMIthcPavUaNJJl0YPARva2ua.jpg',
    },
    {
        name: "Hell's Paradise",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1V9I7SvZbYoMbSvdtnlkkq9SB1k.jpg',
    },
    {
        name: 'High School DxD',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5a9vaaLDAZTYjgfWIw7ZYhL1m1A.jpg',
    },
    {
        name: 'Hunter x Hunter',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/i2EEr2uBvRlAwJ8d8zTG2Y19mIa.jpg',
    },
    {
        name: 'Hunter x Hunter',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eobAuhCJA8oRp814V67WhezVXtQ.jpg',
    },
    {
        name: 'Ichigo Aika: Strawberry Elegy',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fjKOO6PBLwLG3ViyvrIL9oZUmbU.jpg',
    },
    {
        name: 'Inazuma Eleven',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9kQWvBMPWz1gykKLXuX6JBjC9uQ.jpg',
    },
    {
        name: 'Initial D',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/CMG53GMx0OFFmF4dzhlFuebarq.jpg',
    },
    {
        name: 'InuYasha',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jgvW9n0EwKtq9nbztWhyTvvoqjS.jpg',
    },
    {
        name: "JoJo's Bizarre Adventure",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ogAWwbh3frWtiTyyXrZaVFtqCgp.jpg',
    },
    {
        name: 'Joshiochi! 2-kai kara Onnanoko ga... Futtekita!?',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7x8x6dl4leOSw6KGUcOrQew7Eua.jpg',
    },
    {
        name: 'JUJUTSU KAISEN',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg',
    },
    {
        name: 'Lupin the 3rd',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aywOqgw5opNykCW4R8os1liPVnq.jpg',
    },
    {
        name: 'MÄR: Märchen Awakens Romance',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8GCxSybC4X4nKPT2qZPTow30D2H.jpg',
    },
    {
        name: 'Mob Psycho 100',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vR7hwaGQ0ySRoq1WobiNRaPs4WO.jpg',
    },
    {
        name: 'Mobile Suit Gundam ZZ',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/u7GMUFdfljplCbySERldRUReP6P.jpg',
    },
    {
        name: 'Monogatari',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zCEjjb1NH3LLsWeZx47wOeqkezf.jpg',
    },
    {
        name: 'Monster',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/n5XNKXnoXpoXyfiCtXHOf8q8PFM.jpg',
    },
    {
        name: 'Mr. Osomatsu',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vEsmh6m9fUhJzGfLxUpliT3vqdh.jpg',
    },
    {
        name: 'Mushoku Tensei: Jobless Reincarnation',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gLKOYIMyKlUHW0SVdskhgf9C0yy.jpg',
    },
    {
        name: 'Naruto',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/Asv6ornwVeMxKUdA5ySLMrgENwy.jpg',
    },
    {
        name: 'Naruto Shippūden',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/71mASgFgSiPl9QUexVH8BubU0lD.jpg',
    },
    {
        name: "Natsume's Book of Friends",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4IAX5fgsyj9SnV2sqEh5JfuOvUo.jpg',
    },
    {
        name: 'Ninja Boy Rantaro',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fzNiSp0HhCthOTYu9IYWlPPa7fU.jpg',
    },
    {
        name: 'Ninja Hattori-kun',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9PUkpvq0wJnJ2M00dtgxKn6LptB.jpg',
    },
    {
        name: 'Obake no Q-tarō',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/acb9g0rlsFhy3LBPDvMF7Tso9Q0.jpg',
    },
    {
        name: 'One Piece',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uiIB9ctqZFbfRXXimtpmZb5dusi.jpg',
    },
    {
        name: 'One-Punch Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dT10AxJIXVvRwFAew4tt2RhzJrD.jpg',
    },
    {
        name: 'Overflow',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8RtwL5gxUvh9YViqjhNlVRvJpum.jpg',
    },
    {
        name: 'Pokémon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/w1g6hUQg0IzXyU7APRfCQbepsKN.jpg',
    },
    {
        name: 'Pokémon Horizons',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/amemXW39lMbNBJFRMJ5W7q9mLP2.jpg',
    },
    {
        name: 'Powerpuff Girls Z',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lJpPdByOlbmU1Gu40VOL6fEg9U3.jpg',
    },
    {
        name: 'Ranma ½',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qb1R5iLZcjIgdDIfXFQXmJadQPI.jpg',
    },
    {
        name: 'Re:ZERO -Starting Life in Another World-',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/t3lgcb3RHb2PKyHWf1hU6RQXH6N.jpg',
    },
    {
        name: 'REBORN!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6x7mx9f3ufHCC3pNgMoMnzVo3jw.jpg',
    },
    {
        name: 'Rin-ne',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aWTAIftIb2pEnOPyXRDgpscJOKK.jpg',
    },
    {
        name: 'Sailor Moon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wz45BNOMLRZdxXm94P8NGevKubm.jpg',
    },
    {
        name: 'Saint Seiya',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dhtiYYbob8saEUFWle3aWgVY28M.jpg',
    },
    {
        name: 'Sazae-san',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ovOdOiGr0xHxB8rCwLSXAchCrta.jpg',
    },
    {
        name: 'Sgt. Frog',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9cgmkJnUVawW1o6jmmy8kqIl5IJ.jpg',
    },
    {
        name: 'Shin Chan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zg19Paur3lVVSh8J4LJVO1wgBIg.jpg',
    },
    {
        name: 'Shugo Chara!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cP1oeOZCDv1KlQcaV7IpDAUpoFc.jpg',
    },
    {
        name: 'Solo Leveling',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
    },
    {
        name: 'SPY x FAMILY',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7NAvPYPAu7MeHwP8E9sn81PqsRh.jpg',
    },
    {
        name: 'Strike the Blood',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rbGaCkEVS7PE5fKKMAmvO4XZXyA.jpg',
    },
    {
        name: 'Sword Art Online',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9m8bFIXPg26taNrFSXGwEORVACD.jpg',
    },
    {
        name: 'The Apothecary Diaries',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/e3ojpANrFnmJCyeBNTinYwyBCIN.jpg',
    },
    {
        name: 'Tiger Mask W',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yisqc1PDIHL3fHoJdS0yPqGuOEO.jpg',
    },
    {
        name: 'To Your Eternity',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lA2jRBubr2OLOlbkJXuBXYqv4A9.jpg',
    },
    {
        name: 'Toriko',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8NyEmf5xB1HSYM0MzADv8mjUnc4.jpg',
    },
    {
        name: 'Urusei Yatsura',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bs0Q5TMYVUTNXCPbuPBNylzqrxk.jpg',
    },
    {
        name: "Yu-Gi-Oh! 5D's",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1fareX2gQVmpcxoPFHLAHu3ljld.jpg',
    },
    {
        name: 'Yu-Gi-Oh! Arc-V',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nVST01k1PpOZGbGEmCZhevRWhEL.jpg',
    },
    {
        name: 'Yu-Gi-Oh! Duel Monsters',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mM6c5ISlyKWtie2hGiZWo6hmlhU.jpg',
    },
    {
        name: 'Yu-Gi-Oh! GX',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vhY30rXaM5axSpAdr1M1HRQrQGa.jpg',
    },
    {
        name: 'Yu-Gi-Oh! Zexal',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lHOkQJs8oPvU5idZIcjzor7T4m3.jpg',
    },
]
