// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const attackOnTitanCharacters: Character[] = [
    {
        name: 'Anka Rheinberger',
        imageUrl: 'attack-on-titan/anka-rheinberger.webp',
    },
    {
        name: 'Annie Leonhart',
        imageUrl: 'attack-on-titan/annie-leonhart.webp',
    },
    {
        name: 'Armin Arlert',
        imageUrl: 'attack-on-titan/armin-arlert.webp',
    },
    {
        name: 'Bertolt Hoover',
        imageUrl: 'attack-on-titan/bertolt-hoover.webp',
    },
    {
        name: 'Carla Yeager',
        imageUrl: 'attack-on-titan/carla-yeager.webp',
    },
    {
        name: 'Connie Springer',
        imageUrl: 'attack-on-titan/connie-springer.webp',
    },
    {
        name: 'Darius Zackly',
        imageUrl: 'attack-on-titan/darius-zackly.webp',
    },
    {
        name: 'Dot Pixis',
        imageUrl: 'attack-on-titan/dot-pixis.webp',
    },
    {
        name: 'Eren Yeager',
        imageUrl: 'attack-on-titan/eren-yeager.webp',
    },
    {
        name: 'Erwin Smith',
        imageUrl: 'attack-on-titan/erwin-smith.webp',
    },
    {
        name: 'Father Ackerman',
        imageUrl: 'attack-on-titan/father-ackerman.webp',
    },
    {
        name: 'Grandfather Arlert',
        imageUrl: 'attack-on-titan/grandfather-arlert.webp',
    },
    {
        name: 'Grisha Yeager',
        imageUrl: 'attack-on-titan/grisha-yeager.webp',
    },
    {
        name: 'Hange Zoë',
        imageUrl: 'attack-on-titan/hange-zoe.webp',
    },
    {
        name: 'Hannes',
        imageUrl: 'attack-on-titan/hannes.webp',
    },
    {
        name: 'Hitch Dreyse',
        imageUrl: 'attack-on-titan/hitch-dreyse.webp',
    },
    {
        name: 'Ian Dietrich',
        imageUrl: 'attack-on-titan/ian-dietrich.webp',
    },
    {
        name: 'Jean Kirstein',
        imageUrl: 'attack-on-titan/jean-kirstein.webp',
    },
    {
        name: 'Keith Shadis',
        imageUrl: 'attack-on-titan/keith-shadis.webp',
    },
    {
        name: 'Kitts Verman',
        imageUrl: 'attack-on-titan/kitts-verman.webp',
    },
    {
        name: 'Krista Lenz',
        imageUrl: 'attack-on-titan/krista-lenz.webp',
    },
    {
        name: 'Levi',
        imageUrl: 'attack-on-titan/levi.webp',
    },
    {
        name: 'Marco Bott',
        imageUrl: 'attack-on-titan/marco-bott.webp',
    },
    {
        name: 'Marlo Freudenberg',
        imageUrl: 'attack-on-titan/marlo-freudenberg.webp',
    },
    {
        name: 'Mikasa Ackerman',
        imageUrl: 'attack-on-titan/mikasa-ackerman.webp',
    },
    {
        name: 'Mike Zacharias',
        imageUrl: 'attack-on-titan/mike-zacharias.webp',
    },
    {
        name: 'Mina Carolina',
        imageUrl: 'attack-on-titan/mina-carolina.webp',
    },
    {
        name: 'Moblit Berner',
        imageUrl: 'attack-on-titan/moblit-berner.webp',
    },
    {
        name: 'Moses',
        imageUrl: 'attack-on-titan/moses.webp',
    },
    {
        name: 'Mother Ackerman',
        imageUrl: 'attack-on-titan/mother-ackerman.webp',
    },
    {
        name: 'Nanaba',
        imageUrl: 'attack-on-titan/nanaba.webp',
    },
    {
        name: 'Nile Dok',
        imageUrl: 'attack-on-titan/nile-dok.webp',
    },
    {
        name: 'Oluo Bozado',
        imageUrl: 'attack-on-titan/oluo-bozado.webp',
    },
    {
        name: 'Petra Ral',
        imageUrl: 'attack-on-titan/petra-ral.webp',
    },
    {
        name: 'Reiner Braun',
        imageUrl: 'attack-on-titan/reiner-braun.webp',
    },
    {
        name: 'Riko Brzenska',
        imageUrl: 'attack-on-titan/riko-brzenska.webp',
    },
    {
        name: 'Samuel Linke-Jackson',
        imageUrl: 'attack-on-titan/samuel-linke-jackson.webp',
    },
    {
        name: 'Sasha Blouse',
        imageUrl: 'attack-on-titan/sasha-blouse.webp',
    },
    {
        name: 'Thomas Wagner',
        imageUrl: 'attack-on-titan/thomas-wagner.webp',
    },
    {
        name: 'Ymir',
        imageUrl: 'attack-on-titan/ymir.webp',
    },
]
