// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const brandCharacters: Character[] = [
    {
        name: 'Adidas',
        imageUrl:
            'https://img.logo.dev/adidas.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Airbnb',
        imageUrl:
            'https://img.logo.dev/airbnb.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Amazon',
        imageUrl:
            'https://img.logo.dev/amazon.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'AMD',
        imageUrl:
            'https://img.logo.dev/amd.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Apple',
        imageUrl:
            'https://img.logo.dev/apple.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Audi',
        imageUrl:
            'https://img.logo.dev/audi.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'BMW',
        imageUrl:
            'https://img.logo.dev/bmw.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Burger King',
        imageUrl:
            'https://img.logo.dev/burgerking.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Coca-Cola',
        imageUrl:
            'https://img.logo.dev/coca-cola.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Discord',
        imageUrl:
            'https://img.logo.dev/discord.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Disney',
        imageUrl:
            'https://img.logo.dev/disney.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: "Domino's",
        imageUrl:
            'https://img.logo.dev/dominos.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'EA Sports',
        imageUrl:
            'https://img.logo.dev/ea.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Epic Games',
        imageUrl:
            'https://img.logo.dev/epicgames.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Ferrari',
        imageUrl:
            'https://img.logo.dev/ferrari.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Ford',
        imageUrl:
            'https://img.logo.dev/ford.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Google',
        imageUrl:
            'https://img.logo.dev/google.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Instagram',
        imageUrl:
            'https://img.logo.dev/instagram.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Intel',
        imageUrl:
            'https://img.logo.dev/intel.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'KFC',
        imageUrl:
            'https://img.logo.dev/kfc.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Lamborghini',
        imageUrl:
            'https://img.logo.dev/lamborghini.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'LG',
        imageUrl:
            'https://img.logo.dev/lg.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'LinkedIn',
        imageUrl:
            'https://img.logo.dev/linkedin.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Marvel',
        imageUrl:
            'https://img.logo.dev/marvel.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Mastercard',
        imageUrl:
            'https://img.logo.dev/mastercard.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: "McDonald's",
        imageUrl:
            'https://img.logo.dev/mcdonalds.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Mercedes-Benz',
        imageUrl:
            'https://img.logo.dev/mercedes-benz.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Meta',
        imageUrl:
            'https://img.logo.dev/meta.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Microsoft',
        imageUrl:
            'https://img.logo.dev/microsoft.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Netflix',
        imageUrl:
            'https://img.logo.dev/netflix.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Nike',
        imageUrl:
            'https://img.logo.dev/nike.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Nintendo',
        imageUrl:
            'https://img.logo.dev/nintendo.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Nvidia',
        imageUrl:
            'https://img.logo.dev/nvidia.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'PayPal',
        imageUrl:
            'https://img.logo.dev/paypal.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Pepsi',
        imageUrl:
            'https://img.logo.dev/pepsi.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'PlayStation',
        imageUrl:
            'https://img.logo.dev/playstation.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Porsche',
        imageUrl:
            'https://img.logo.dev/porsche.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Puma',
        imageUrl:
            'https://img.logo.dev/puma.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Reddit',
        imageUrl:
            'https://img.logo.dev/reddit.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Samsung',
        imageUrl:
            'https://img.logo.dev/samsung.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Shopify',
        imageUrl:
            'https://img.logo.dev/shopify.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Snapchat',
        imageUrl:
            'https://img.logo.dev/snapchat.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Sony',
        imageUrl:
            'https://img.logo.dev/sony.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Spotify',
        imageUrl:
            'https://img.logo.dev/spotify.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Starbucks',
        imageUrl:
            'https://img.logo.dev/starbucks.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Steam',
        imageUrl:
            'https://img.logo.dev/steampowered.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Subway',
        imageUrl:
            'https://img.logo.dev/subway.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Tesla',
        imageUrl:
            'https://img.logo.dev/tesla.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'TikTok',
        imageUrl:
            'https://img.logo.dev/tiktok.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Toyota',
        imageUrl:
            'https://img.logo.dev/toyota.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Twitch',
        imageUrl:
            'https://img.logo.dev/twitch.tv?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Twitter',
        imageUrl:
            'https://img.logo.dev/twitter.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Uber',
        imageUrl:
            'https://img.logo.dev/uber.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Ubisoft',
        imageUrl:
            'https://img.logo.dev/ubisoft.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Visa',
        imageUrl:
            'https://img.logo.dev/visa.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Volkswagen',
        imageUrl:
            'https://img.logo.dev/vw.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'WhatsApp',
        imageUrl:
            'https://img.logo.dev/whatsapp.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'Xbox',
        imageUrl:
            'https://img.logo.dev/xbox.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
    {
        name: 'YouTube',
        imageUrl:
            'https://img.logo.dev/youtube.com?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark',
    },
]
