// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const brandCharacters: Character[] = [
    {
        name: 'Adidas',
        imageUrl: 'https://logo.clearbit.com/adidas.com',
    },
    {
        name: 'Airbnb',
        imageUrl: 'https://logo.clearbit.com/airbnb.com',
    },
    {
        name: 'Amazon',
        imageUrl: 'https://logo.clearbit.com/amazon.com',
    },
    {
        name: 'AMD',
        imageUrl: 'https://logo.clearbit.com/amd.com',
    },
    {
        name: 'Apple',
        imageUrl: 'https://logo.clearbit.com/apple.com',
    },
    {
        name: 'Audi',
        imageUrl: 'https://logo.clearbit.com/audi.com',
    },
    {
        name: 'BMW',
        imageUrl: 'https://logo.clearbit.com/bmw.com',
    },
    {
        name: 'Burger King',
        imageUrl: 'https://logo.clearbit.com/burgerking.com',
    },
    {
        name: 'Coca-Cola',
        imageUrl: 'https://logo.clearbit.com/coca-cola.com',
    },
    {
        name: 'Discord',
        imageUrl: 'https://logo.clearbit.com/discord.com',
    },
    {
        name: 'Disney',
        imageUrl: 'https://logo.clearbit.com/disney.com',
    },
    {
        name: "Domino's",
        imageUrl: 'https://logo.clearbit.com/dominos.com',
    },
    {
        name: 'EA Sports',
        imageUrl: 'https://logo.clearbit.com/ea.com',
    },
    {
        name: 'Epic Games',
        imageUrl: 'https://logo.clearbit.com/epicgames.com',
    },
    {
        name: 'Ferrari',
        imageUrl: 'https://logo.clearbit.com/ferrari.com',
    },
    {
        name: 'Ford',
        imageUrl: 'https://logo.clearbit.com/ford.com',
    },
    {
        name: 'Google',
        imageUrl: 'https://logo.clearbit.com/google.com',
    },
    {
        name: 'Instagram',
        imageUrl: 'https://logo.clearbit.com/instagram.com',
    },
    {
        name: 'Intel',
        imageUrl: 'https://logo.clearbit.com/intel.com',
    },
    {
        name: 'KFC',
        imageUrl: 'https://logo.clearbit.com/kfc.com',
    },
    {
        name: 'Lamborghini',
        imageUrl: 'https://logo.clearbit.com/lamborghini.com',
    },
    {
        name: 'LG',
        imageUrl: 'https://logo.clearbit.com/lg.com',
    },
    {
        name: 'LinkedIn',
        imageUrl: 'https://logo.clearbit.com/linkedin.com',
    },
    {
        name: 'Marvel',
        imageUrl: 'https://logo.clearbit.com/marvel.com',
    },
    {
        name: 'Mastercard',
        imageUrl: 'https://logo.clearbit.com/mastercard.com',
    },
    {
        name: "McDonald's",
        imageUrl: 'https://logo.clearbit.com/mcdonalds.com',
    },
    {
        name: 'Mercedes-Benz',
        imageUrl: 'https://logo.clearbit.com/mercedes-benz.com',
    },
    {
        name: 'Meta',
        imageUrl: 'https://logo.clearbit.com/meta.com',
    },
    {
        name: 'Microsoft',
        imageUrl: 'https://logo.clearbit.com/microsoft.com',
    },
    {
        name: 'Netflix',
        imageUrl: 'https://logo.clearbit.com/netflix.com',
    },
    {
        name: 'Nike',
        imageUrl: 'https://logo.clearbit.com/nike.com',
    },
    {
        name: 'Nintendo',
        imageUrl: 'https://logo.clearbit.com/nintendo.com',
    },
    {
        name: 'Nvidia',
        imageUrl: 'https://logo.clearbit.com/nvidia.com',
    },
    {
        name: 'PayPal',
        imageUrl: 'https://logo.clearbit.com/paypal.com',
    },
    {
        name: 'Pepsi',
        imageUrl: 'https://logo.clearbit.com/pepsi.com',
    },
    {
        name: 'PlayStation',
        imageUrl: 'https://logo.clearbit.com/playstation.com',
    },
    {
        name: 'Porsche',
        imageUrl: 'https://logo.clearbit.com/porsche.com',
    },
    {
        name: 'Puma',
        imageUrl: 'https://logo.clearbit.com/puma.com',
    },
    {
        name: 'Reddit',
        imageUrl: 'https://logo.clearbit.com/reddit.com',
    },
    {
        name: 'Samsung',
        imageUrl: 'https://logo.clearbit.com/samsung.com',
    },
    {
        name: 'Shopify',
        imageUrl: 'https://logo.clearbit.com/shopify.com',
    },
    {
        name: 'Snapchat',
        imageUrl: 'https://logo.clearbit.com/snapchat.com',
    },
    {
        name: 'Sony',
        imageUrl: 'https://logo.clearbit.com/sony.com',
    },
    {
        name: 'Spotify',
        imageUrl: 'https://logo.clearbit.com/spotify.com',
    },
    {
        name: 'Starbucks',
        imageUrl: 'https://logo.clearbit.com/starbucks.com',
    },
    {
        name: 'Steam',
        imageUrl: 'https://logo.clearbit.com/steampowered.com',
    },
    {
        name: 'Subway',
        imageUrl: 'https://logo.clearbit.com/subway.com',
    },
    {
        name: 'Tesla',
        imageUrl: 'https://logo.clearbit.com/tesla.com',
    },
    {
        name: 'TikTok',
        imageUrl: 'https://logo.clearbit.com/tiktok.com',
    },
    {
        name: 'Toyota',
        imageUrl: 'https://logo.clearbit.com/toyota.com',
    },
    {
        name: 'Twitch',
        imageUrl: 'https://logo.clearbit.com/twitch.tv',
    },
    {
        name: 'Twitter',
        imageUrl: 'https://logo.clearbit.com/twitter.com',
    },
    {
        name: 'Uber',
        imageUrl: 'https://logo.clearbit.com/uber.com',
    },
    {
        name: 'Ubisoft',
        imageUrl: 'https://logo.clearbit.com/ubisoft.com',
    },
    {
        name: 'Visa',
        imageUrl: 'https://logo.clearbit.com/visa.com',
    },
    {
        name: 'Volkswagen',
        imageUrl: 'https://logo.clearbit.com/vw.com',
    },
    {
        name: 'WhatsApp',
        imageUrl: 'https://logo.clearbit.com/whatsapp.com',
    },
    {
        name: 'Xbox',
        imageUrl: 'https://logo.clearbit.com/xbox.com',
    },
    {
        name: 'YouTube',
        imageUrl: 'https://logo.clearbit.com/youtube.com',
    },
]
