// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const brandCharacters: Character[] = [
    {
        name: 'Adidas',
        imageUrl: 'brands/adidas.webp',
    },
    {
        name: 'Airbnb',
        imageUrl: 'brands/airbnb.webp',
    },
    {
        name: 'Amazon',
        imageUrl: 'brands/amazon.webp',
    },
    {
        name: 'AMD',
        imageUrl: 'brands/amd.webp',
    },
    {
        name: 'Apple',
        imageUrl: 'brands/apple.webp',
    },
    {
        name: 'Audi',
        imageUrl: 'brands/audi.webp',
    },
    {
        name: 'BMW',
        imageUrl: 'brands/bmw.webp',
    },
    {
        name: 'Burger King',
        imageUrl: 'brands/burger-king.webp',
    },
    {
        name: 'Coca-Cola',
        imageUrl: 'brands/coca-cola.webp',
    },
    {
        name: 'Discord',
        imageUrl: 'brands/discord.webp',
    },
    {
        name: 'Disney',
        imageUrl: 'brands/disney.webp',
    },
    {
        name: "Domino's",
        imageUrl: 'brands/domino-s.webp',
    },
    {
        name: 'EA Sports',
        imageUrl: 'brands/ea-sports.webp',
    },
    {
        name: 'Epic Games',
        imageUrl: 'brands/epic-games.webp',
    },
    {
        name: 'Ferrari',
        imageUrl: 'brands/ferrari.webp',
    },
    {
        name: 'Ford',
        imageUrl: 'brands/ford.webp',
    },
    {
        name: 'Google',
        imageUrl: 'brands/google.webp',
    },
    {
        name: 'Instagram',
        imageUrl: 'brands/instagram.webp',
    },
    {
        name: 'Intel',
        imageUrl: 'brands/intel.webp',
    },
    {
        name: 'KFC',
        imageUrl: 'brands/kfc.webp',
    },
    {
        name: 'Lamborghini',
        imageUrl: 'brands/lamborghini.webp',
    },
    {
        name: 'LG',
        imageUrl: 'brands/lg.webp',
    },
    {
        name: 'LinkedIn',
        imageUrl: 'brands/linkedin.webp',
    },
    {
        name: 'Marvel',
        imageUrl: 'brands/marvel.webp',
    },
    {
        name: 'Mastercard',
        imageUrl: 'brands/mastercard.webp',
    },
    {
        name: "McDonald's",
        imageUrl: 'brands/mcdonald-s.webp',
    },
    {
        name: 'Mercedes-Benz',
        imageUrl: 'brands/mercedes-benz.webp',
    },
    {
        name: 'Meta',
        imageUrl: 'brands/meta.webp',
    },
    {
        name: 'Microsoft',
        imageUrl: 'brands/microsoft.webp',
    },
    {
        name: 'Netflix',
        imageUrl: 'brands/netflix.webp',
    },
    {
        name: 'Nike',
        imageUrl: 'brands/nike.webp',
    },
    {
        name: 'Nintendo',
        imageUrl: 'brands/nintendo.webp',
    },
    {
        name: 'Nvidia',
        imageUrl: 'brands/nvidia.webp',
    },
    {
        name: 'PayPal',
        imageUrl: 'brands/paypal.webp',
    },
    {
        name: 'Pepsi',
        imageUrl: 'brands/pepsi.webp',
    },
    {
        name: 'PlayStation',
        imageUrl: 'brands/playstation.webp',
    },
    {
        name: 'Porsche',
        imageUrl: 'brands/porsche.webp',
    },
    {
        name: 'Puma',
        imageUrl: 'brands/puma.webp',
    },
    {
        name: 'Reddit',
        imageUrl: 'brands/reddit.webp',
    },
    {
        name: 'Samsung',
        imageUrl: 'brands/samsung.webp',
    },
    {
        name: 'Shopify',
        imageUrl: 'brands/shopify.webp',
    },
    {
        name: 'Snapchat',
        imageUrl: 'brands/snapchat.webp',
    },
    {
        name: 'Sony',
        imageUrl: 'brands/sony.webp',
    },
    {
        name: 'Spotify',
        imageUrl: 'brands/spotify.webp',
    },
    {
        name: 'Starbucks',
        imageUrl: 'brands/starbucks.webp',
    },
    {
        name: 'Steam',
        imageUrl: 'brands/steam.webp',
    },
    {
        name: 'Subway',
        imageUrl: 'brands/subway.webp',
    },
    {
        name: 'Tesla',
        imageUrl: 'brands/tesla.webp',
    },
    {
        name: 'TikTok',
        imageUrl: 'brands/tiktok.webp',
    },
    {
        name: 'Toyota',
        imageUrl: 'brands/toyota.webp',
    },
    {
        name: 'Twitch',
        imageUrl: 'brands/twitch.webp',
    },
    {
        name: 'Twitter',
        imageUrl: 'brands/twitter.webp',
    },
    {
        name: 'Uber',
        imageUrl: 'brands/uber.webp',
    },
    {
        name: 'Ubisoft',
        imageUrl: 'brands/ubisoft.webp',
    },
    {
        name: 'Visa',
        imageUrl: 'brands/visa.webp',
    },
    {
        name: 'Volkswagen',
        imageUrl: 'brands/volkswagen.webp',
    },
    {
        name: 'WhatsApp',
        imageUrl: 'brands/whatsapp.webp',
    },
    {
        name: 'Xbox',
        imageUrl: 'brands/xbox.webp',
    },
    {
        name: 'YouTube',
        imageUrl: 'brands/youtube.webp',
    },
]
