// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const deathNoteCharacters: Character[] = [
    {
        name: 'Anthony Carter',
        imageUrl: 'death-note/anthony-carter.webp',
    },
    {
        name: 'Gook',
        imageUrl: 'death-note/gook.webp',
    },
    {
        name: 'Halle Bullook',
        imageUrl: 'death-note/halle-bullook.webp',
    },
    {
        name: 'Jealous',
        imageUrl: 'death-note/jealous.webp',
    },
    {
        name: 'Kanzou Mogi',
        imageUrl: 'death-note/kanzou-mogi.webp',
    },
    {
        name: 'Kiyomi Takada',
        imageUrl: 'death-note/kiyomi-takada.webp',
    },
    {
        name: 'Kyousuke Higuchi',
        imageUrl: 'death-note/kyousuke-higuchi.webp',
    },
    {
        name: 'L Lawliet',
        imageUrl: 'death-note/l-lawliet.webp',
    },
    {
        name: 'Light Yagami',
        imageUrl: 'death-note/light-yagami.webp',
    },
    {
        name: 'Lind L. Tailor',
        imageUrl: 'death-note/lind-l-tailor.webp',
    },
    {
        name: 'Mail Jeevas',
        imageUrl: 'death-note/mail-jeevas.webp',
    },
    {
        name: 'Mary Kenwood',
        imageUrl: 'death-note/mary-kenwood.webp',
    },
    {
        name: 'Mihael Keehl',
        imageUrl: 'death-note/mihael-keehl.webp',
    },
    {
        name: 'Misa Amane',
        imageUrl: 'death-note/misa-amane.webp',
    },
    {
        name: 'Naomi Misora',
        imageUrl: 'death-note/naomi-misora.webp',
    },
    {
        name: 'Nate River',
        imageUrl: 'death-note/nate-river.webp',
    },
    {
        name: 'Quillsh Wammy',
        imageUrl: 'death-note/quillsh-wammy.webp',
    },
    {
        name: 'Raye Penber',
        imageUrl: 'death-note/raye-penber.webp',
    },
    {
        name: 'Reiji Namikawa',
        imageUrl: 'death-note/reiji-namikawa.webp',
    },
    {
        name: 'Rem',
        imageUrl: 'death-note/rem.webp',
    },
    {
        name: 'Ryuk',
        imageUrl: 'death-note/ryuk.webp',
    },
    {
        name: 'Sayu Yagami',
        imageUrl: 'death-note/sayu-yagami.webp',
    },
    {
        name: 'Shidoh',
        imageUrl: 'death-note/shidoh.webp',
    },
    {
        name: 'Shuuichi Aizawa',
        imageUrl: 'death-note/shuuichi-aizawa.webp',
    },
    {
        name: 'Souichirou Yagami',
        imageUrl: 'death-note/souichirou-yagami.webp',
    },
    {
        name: 'Stephen Loud',
        imageUrl: 'death-note/stephen-loud.webp',
    },
    {
        name: 'Takuo Shibuimaru',
        imageUrl: 'death-note/takuo-shibuimaru.webp',
    },
    {
        name: 'Teru Mikami',
        imageUrl: 'death-note/teru-mikami.webp',
    },
    {
        name: 'Touta Matsuda',
        imageUrl: 'death-note/touta-matsuda.webp',
    },
    {
        name: 'Yuri',
        imageUrl: 'death-note/yuri.webp',
    },
]
