// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const demonSlayerCharacters: Character[] = [
    {
        name: 'Aoi Kanzaki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/388816.jpg?s=8edf4db221b9669a7360c07365b70d82',
    },
    {
        name: 'Enmu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/440983.jpg?s=1ebcd7b3476422ec1f95819e37fd1dce',
    },
    {
        name: 'Genya Shinazugawa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/390152.jpg?s=cc66310ec90675724eaa4a626300a972',
    },
    {
        name: 'Giyuu Tomioka',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/423445.jpg?s=a049de02a43de100a4b68b759a95fa41',
    },
    {
        name: 'Gotou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/388820.jpg?s=0620ac8e4920f26e4a727ec8f7ea193d',
    },
    {
        name: 'Gyoumei Himejima',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/550017.jpg?s=161a6d45c08fe0c74b24668fd665d79d',
    },
    {
        name: 'Hanako Kamado',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/382218.jpg?s=73cbfe14ee593811d70d0a44de16ce01',
    },
    {
        name: 'Hotaru Haganezuka',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/379207.jpg?s=3c7d46ae2ec328058158ba2fdfe3272c',
    },
    {
        name: 'Inosuke Hashibira',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/329560.jpg?s=5ef0629d3641cd02eaeaf7d4df9ea4c2',
    },
    {
        name: 'Kagaya Ubuyashiki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/387497.jpg?s=e6703bc6bca651607032e86749bfdc2a',
    },
    {
        name: 'Kaigaku',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/508549.jpg?s=405b346d5e35d22ca72cfe9dcac0e8f4',
    },
    {
        name: 'Kanae Kochou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/389355.jpg?s=d84b20e84e95effcc36a4f1a09d49626',
    },
    {
        name: 'Kanao Tsuyuri',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/384712.jpg?s=efa0d88902b290fa7a72e6287eaa3e2b',
    },
    {
        name: 'Kie Kamado',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/382215.jpg?s=60219faf71eb6cf8865617ec462e30f2',
    },
    {
        name: 'Kyougai',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/385328.jpg?s=8074ed3ed6a5751a6d197fe7681319ae',
    },
    {
        name: 'Kyoujurou Rengoku',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/423443.jpg?s=2f06005562d13647b1a8280b93db9d54',
    },
    {
        name: 'Makomo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/382213.jpg?s=29cc0fe8cb48a226123ce9613dca4908',
    },
    {
        name: 'Mitsuri Kanroji',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/514229.jpg?s=8bbf40b3cfa80df52f3eccce022146ea',
    },
    {
        name: 'Mother Spider Demon',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/385242.jpg?s=280b191a858dde5dc8f1c836f86f90bb',
    },
    {
        name: 'Muichirou Tokitou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/464903.jpg?s=8a4c1a500e00fe55746dd8d259401513',
    },
    {
        name: 'Murata',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/388807.jpg?s=5db86cfffbfb133ce9fa16599207961e',
    },
    {
        name: 'Muzan Kibutsuji',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/384669.jpg?s=c9d7f04d71e6651de82cb1e56f52e8e0',
    },
    {
        name: 'Nakime',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/551259.jpg?s=72bfdcb99a910a1f62b2ea3d08990407',
    },
    {
        name: 'Nezuko Kamado',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/378254.jpg?s=c3cdc50f2d9f3b30e4453c8ca1f8460f',
    },
    {
        name: 'Obanai Iguro',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/466014.jpg?s=84acfcc6983f442cb4b968c78baf4f87',
    },
    {
        name: 'Older Sister Spider Demon',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/385245.jpg?s=82b53dfaeb21db5c28ab002f31a196e3',
    },
    {
        name: 'Rui',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/385228.jpg?s=8f8d74e29bfeabd42d3a05efa5b02f5c',
    },
    {
        name: 'Sabito',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/599194.jpg?s=2935cd641904eabf29e506c2368ffa28',
    },
    {
        name: 'Sakonji Urokodaki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/382214.jpg?s=c6e1deed4aaafdf7525e309c7b876502',
    },
    {
        name: 'Sanemi Shinazugawa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/556642.jpg?s=ada28fd15a950dfccfc37d41aaea8870',
    },
    {
        name: 'Shinobu Kochou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/386591.jpg?s=3c18dc65ee6cd3a032214d6a6e49ac9e',
    },
    {
        name: 'Susamaru',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/379196.jpg?s=b9c3da27a29979c3a1e45ca97bc64520',
    },
    {
        name: 'Tamayo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/384692.jpg?s=54e3861d7f054ca4013293d70b2a5bed',
    },
    {
        name: 'Tanjirou Kamado',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/386735.jpg?s=7327e90f2310ececd18696cd4aa2ff4e',
    },
    {
        name: 'Tanjuurou Kamado',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/385444.jpg?s=38029074c6aaebd8cd81fca6f2edc8b1',
    },
    {
        name: 'Tengen Uzui',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/387706.jpg?s=c761782087650f5a1e98a21aa7635280',
    },
    {
        name: 'Ukogi',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/470329.jpg?s=f260f7dfd1ce3805169c66fc1fe7572a',
    },
    {
        name: 'Yoriichi Tsugikuni',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/394870.jpg?s=b0ac33b0b4fc18dbb38587ef170b6f27',
    },
    {
        name: 'Yushirou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/384720.jpg?s=f6ace68d582e4c8a87f5fcd0ff093e81',
    },
    {
        name: 'Zenitsu Agatsuma',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/459689.jpg?s=d5ccecc4a7b9e2118acb849a2062a84c',
    },
]
