// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const demonSlayerCharacters: Character[] = [
    {
        name: 'Aoi Kanzaki',
        imageUrl: 'demon-slayer/aoi-kanzaki.webp',
    },
    {
        name: 'Enmu',
        imageUrl: 'demon-slayer/enmu.webp',
    },
    {
        name: 'Genya Shinazugawa',
        imageUrl: 'demon-slayer/genya-shinazugawa.webp',
    },
    {
        name: 'Giyuu Tomioka',
        imageUrl: 'demon-slayer/giyuu-tomioka.webp',
    },
    {
        name: 'Gotou',
        imageUrl: 'demon-slayer/gotou.webp',
    },
    {
        name: 'Gyoumei Himejima',
        imageUrl: 'demon-slayer/gyoumei-himejima.webp',
    },
    {
        name: 'Hanako Kamado',
        imageUrl: 'demon-slayer/hanako-kamado.webp',
    },
    {
        name: 'Hotaru Haganezuka',
        imageUrl: 'demon-slayer/hotaru-haganezuka.webp',
    },
    {
        name: 'Inosuke Hashibira',
        imageUrl: 'demon-slayer/inosuke-hashibira.webp',
    },
    {
        name: 'Kagaya Ubuyashiki',
        imageUrl: 'demon-slayer/kagaya-ubuyashiki.webp',
    },
    {
        name: 'Kaigaku',
        imageUrl: 'demon-slayer/kaigaku.webp',
    },
    {
        name: 'Kanae Kochou',
        imageUrl: 'demon-slayer/kanae-kochou.webp',
    },
    {
        name: 'Kanao Tsuyuri',
        imageUrl: 'demon-slayer/kanao-tsuyuri.webp',
    },
    {
        name: 'Kie Kamado',
        imageUrl: 'demon-slayer/kie-kamado.webp',
    },
    {
        name: 'Kyougai',
        imageUrl: 'demon-slayer/kyougai.webp',
    },
    {
        name: 'Kyoujurou Rengoku',
        imageUrl: 'demon-slayer/kyoujurou-rengoku.webp',
    },
    {
        name: 'Makomo',
        imageUrl: 'demon-slayer/makomo.webp',
    },
    {
        name: 'Mitsuri Kanroji',
        imageUrl: 'demon-slayer/mitsuri-kanroji.webp',
    },
    {
        name: 'Mother Spider Demon',
        imageUrl: 'demon-slayer/mother-spider-demon.webp',
    },
    {
        name: 'Muichirou Tokitou',
        imageUrl: 'demon-slayer/muichirou-tokitou.webp',
    },
    {
        name: 'Murata',
        imageUrl: 'demon-slayer/murata.webp',
    },
    {
        name: 'Muzan Kibutsuji',
        imageUrl: 'demon-slayer/muzan-kibutsuji.webp',
    },
    {
        name: 'Nakime',
        imageUrl: 'demon-slayer/nakime.webp',
    },
    {
        name: 'Nezuko Kamado',
        imageUrl: 'demon-slayer/nezuko-kamado.webp',
    },
    {
        name: 'Obanai Iguro',
        imageUrl: 'demon-slayer/obanai-iguro.webp',
    },
    {
        name: 'Older Sister Spider Demon',
        imageUrl: 'demon-slayer/older-sister-spider-demon.webp',
    },
    {
        name: 'Rui',
        imageUrl: 'demon-slayer/rui.webp',
    },
    {
        name: 'Sabito',
        imageUrl: 'demon-slayer/sabito.webp',
    },
    {
        name: 'Sakonji Urokodaki',
        imageUrl: 'demon-slayer/sakonji-urokodaki.webp',
    },
    {
        name: 'Sanemi Shinazugawa',
        imageUrl: 'demon-slayer/sanemi-shinazugawa.webp',
    },
    {
        name: 'Shinobu Kochou',
        imageUrl: 'demon-slayer/shinobu-kochou.webp',
    },
    {
        name: 'Susamaru',
        imageUrl: 'demon-slayer/susamaru.webp',
    },
    {
        name: 'Tamayo',
        imageUrl: 'demon-slayer/tamayo.webp',
    },
    {
        name: 'Tanjirou Kamado',
        imageUrl: 'demon-slayer/tanjirou-kamado.webp',
    },
    {
        name: 'Tanjuurou Kamado',
        imageUrl: 'demon-slayer/tanjuurou-kamado.webp',
    },
    {
        name: 'Tengen Uzui',
        imageUrl: 'demon-slayer/tengen-uzui.webp',
    },
    {
        name: 'Ukogi',
        imageUrl: 'demon-slayer/ukogi.webp',
    },
    {
        name: 'Yoriichi Tsugikuni',
        imageUrl: 'demon-slayer/yoriichi-tsugikuni.webp',
    },
    {
        name: 'Yushirou',
        imageUrl: 'demon-slayer/yushirou.webp',
    },
    {
        name: 'Zenitsu Agatsuma',
        imageUrl: 'demon-slayer/zenitsu-agatsuma.webp',
    },
]
