// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const dota2Characters: Character[] = [
    {
        name: 'Abaddon',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abaddon.png',
    },
    {
        name: 'Alchemist',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/alchemist.png',
    },
    {
        name: 'Ancient Apparition',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ancient_apparition.png',
    },
    {
        name: 'Anti-Mage',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/antimage.png',
    },
    {
        name: 'Arc Warden',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/arc_warden.png',
    },
    {
        name: 'Axe',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/axe.png',
    },
    {
        name: 'Bane',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bane.png',
    },
    {
        name: 'Batrider',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/batrider.png',
    },
    {
        name: 'Beastmaster',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/beastmaster.png',
    },
    {
        name: 'Bloodseeker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bloodseeker.png',
    },
    {
        name: 'Bounty Hunter',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bounty_hunter.png',
    },
    {
        name: 'Brewmaster',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/brewmaster.png',
    },
    {
        name: 'Bristleback',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bristleback.png',
    },
    {
        name: 'Broodmother',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/broodmother.png',
    },
    {
        name: 'Centaur Warrunner',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/centaur.png',
    },
    {
        name: 'Chaos Knight',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chaos_knight.png',
    },
    {
        name: 'Chen',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chen.png',
    },
    {
        name: 'Clinkz',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/clinkz.png',
    },
    {
        name: 'Clockwerk',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rattletrap.png',
    },
    {
        name: 'Crystal Maiden',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/crystal_maiden.png',
    },
    {
        name: 'Dark Seer',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_seer.png',
    },
    {
        name: 'Dark Willow',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_willow.png',
    },
    {
        name: 'Dawnbreaker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png',
    },
    {
        name: 'Dazzle',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dazzle.png',
    },
    {
        name: 'Death Prophet',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/death_prophet.png',
    },
    {
        name: 'Disruptor',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/disruptor.png',
    },
    {
        name: 'Doom',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/doom_bringer.png',
    },
    {
        name: 'Dragon Knight',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dragon_knight.png',
    },
    {
        name: 'Drow Ranger',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/drow_ranger.png',
    },
    {
        name: 'Earth Spirit',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earth_spirit.png',
    },
    {
        name: 'Earthshaker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earthshaker.png',
    },
    {
        name: 'Elder Titan',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/elder_titan.png',
    },
    {
        name: 'Ember Spirit',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ember_spirit.png',
    },
    {
        name: 'Enchantress',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enchantress.png',
    },
    {
        name: 'Enigma',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enigma.png',
    },
    {
        name: 'Faceless Void',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/faceless_void.png',
    },
    {
        name: 'Grimstroke',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/grimstroke.png',
    },
    {
        name: 'Gyrocopter',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/gyrocopter.png',
    },
    {
        name: 'Hoodwink',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/hoodwink.png',
    },
    {
        name: 'Huskar',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/huskar.png',
    },
    {
        name: 'Invoker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/invoker.png',
    },
    {
        name: 'Io',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/wisp.png',
    },
    {
        name: 'Jakiro',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/jakiro.png',
    },
    {
        name: 'Juggernaut',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/juggernaut.png',
    },
    {
        name: 'Keeper of the Light',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png',
    },
    {
        name: 'Kez',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kez.png',
    },
    {
        name: 'Kunkka',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kunkka.png',
    },
    {
        name: 'Largo',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/largo.png',
    },
    {
        name: 'Legion Commander',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/legion_commander.png',
    },
    {
        name: 'Leshrac',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/leshrac.png',
    },
    {
        name: 'Lich',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lich.png',
    },
    {
        name: 'Lifestealer',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/life_stealer.png',
    },
    {
        name: 'Lina',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lina.png',
    },
    {
        name: 'Lion',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lion.png',
    },
    {
        name: 'Lone Druid',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lone_druid.png',
    },
    {
        name: 'Luna',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/luna.png',
    },
    {
        name: 'Lycan',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lycan.png',
    },
    {
        name: 'Magnus',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/magnataur.png',
    },
    {
        name: 'Marci',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/marci.png',
    },
    {
        name: 'Mars',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mars.png',
    },
    {
        name: 'Medusa',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/medusa.png',
    },
    {
        name: 'Meepo',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/meepo.png',
    },
    {
        name: 'Mirana',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mirana.png',
    },
    {
        name: 'Monkey King',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/monkey_king.png',
    },
    {
        name: 'Morphling',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/morphling.png',
    },
    {
        name: 'Muerta',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/muerta.png',
    },
    {
        name: 'Naga Siren',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/naga_siren.png',
    },
    {
        name: "Nature's Prophet",
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/furion.png',
    },
    {
        name: 'Necrophos',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/necrolyte.png',
    },
    {
        name: 'Night Stalker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/night_stalker.png',
    },
    {
        name: 'Nyx Assassin',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nyx_assassin.png',
    },
    {
        name: 'Ogre Magi',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ogre_magi.png',
    },
    {
        name: 'Omniknight',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/omniknight.png',
    },
    {
        name: 'Oracle',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/oracle.png',
    },
    {
        name: 'Outworld Destroyer',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png',
    },
    {
        name: 'Pangolier',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pangolier.png',
    },
    {
        name: 'Phantom Assassin',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_assassin.png',
    },
    {
        name: 'Phantom Lancer',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_lancer.png',
    },
    {
        name: 'Phoenix',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phoenix.png',
    },
    {
        name: 'Primal Beast',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/primal_beast.png',
    },
    {
        name: 'Puck',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/puck.png',
    },
    {
        name: 'Pudge',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pudge.png',
    },
    {
        name: 'Pugna',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pugna.png',
    },
    {
        name: 'Queen of Pain',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/queenofpain.png',
    },
    {
        name: 'Razor',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/razor.png',
    },
    {
        name: 'Riki',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/riki.png',
    },
    {
        name: 'Ringmaster',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ringmaster.png',
    },
    {
        name: 'Rubick',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rubick.png',
    },
    {
        name: 'Sand King',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sand_king.png',
    },
    {
        name: 'Shadow Demon',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_demon.png',
    },
    {
        name: 'Shadow Fiend',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nevermore.png',
    },
    {
        name: 'Shadow Shaman',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_shaman.png',
    },
    {
        name: 'Silencer',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/silencer.png',
    },
    {
        name: 'Skywrath Mage',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skywrath_mage.png',
    },
    {
        name: 'Slardar',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slardar.png',
    },
    {
        name: 'Slark',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slark.png',
    },
    {
        name: 'Snapfire',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/snapfire.png',
    },
    {
        name: 'Sniper',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sniper.png',
    },
    {
        name: 'Spectre',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spectre.png',
    },
    {
        name: 'Spirit Breaker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spirit_breaker.png',
    },
    {
        name: 'Storm Spirit',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/storm_spirit.png',
    },
    {
        name: 'Sven',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sven.png',
    },
    {
        name: 'Techies',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/techies.png',
    },
    {
        name: 'Templar Assassin',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/templar_assassin.png',
    },
    {
        name: 'Terrorblade',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/terrorblade.png',
    },
    {
        name: 'Tidehunter',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tidehunter.png',
    },
    {
        name: 'Timbersaw',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shredder.png',
    },
    {
        name: 'Tinker',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tinker.png',
    },
    {
        name: 'Tiny',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tiny.png',
    },
    {
        name: 'Treant Protector',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/treant.png',
    },
    {
        name: 'Troll Warlord',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/troll_warlord.png',
    },
    {
        name: 'Tusk',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tusk.png',
    },
    {
        name: 'Underlord',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abyssal_underlord.png',
    },
    {
        name: 'Undying',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/undying.png',
    },
    {
        name: 'Ursa',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ursa.png',
    },
    {
        name: 'Vengeful Spirit',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/vengefulspirit.png',
    },
    {
        name: 'Venomancer',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/venomancer.png',
    },
    {
        name: 'Viper',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/viper.png',
    },
    {
        name: 'Visage',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/visage.png',
    },
    {
        name: 'Void Spirit',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/void_spirit.png',
    },
    {
        name: 'Warlock',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/warlock.png',
    },
    {
        name: 'Weaver',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/weaver.png',
    },
    {
        name: 'Windranger',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/windrunner.png',
    },
    {
        name: 'Winter Wyvern',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/winter_wyvern.png',
    },
    {
        name: 'Witch Doctor',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/witch_doctor.png',
    },
    {
        name: 'Wraith King',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skeleton_king.png',
    },
    {
        name: 'Zeus',
        imageUrl:
            'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/zuus.png',
    },
]
