// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const dragonBallCharacters: Character[] = [
    {
        name: 'Android 13',
        imageUrl: 'https://dragonball-api.com/characters/Androide13normal.webp',
    },
    {
        name: 'Android 14',
        imageUrl: 'https://dragonball-api.com/characters/14Dokkan.webp',
    },
    {
        name: 'Android 15',
        imageUrl: 'https://dragonball-api.com/characters/15Dokkan.webp',
    },
    {
        name: 'Android 16',
        imageUrl: 'https://dragonball-api.com/characters/Androide_16.webp',
    },
    {
        name: 'Android 17',
        imageUrl: 'https://dragonball-api.com/characters/17_Artwork.webp',
    },
    {
        name: 'Android 18',
        imageUrl:
            'https://dragonball-api.com/characters/Androide_18_Artwork.webp',
    },
    {
        name: 'Android 19',
        imageUrl: 'https://dragonball-api.com/characters/Android19.webp',
    },
    {
        name: 'Android 20 (Dr. Gero)',
        imageUrl:
            'https://dragonball-api.com/characters/Dr._Gero nadroide 20.webp',
    },
    {
        name: 'Babidi',
        imageUrl: 'https://dragonball-api.com/characters/Babidi_Artwork.webp',
    },
    {
        name: 'Bardock',
        imageUrl: 'https://dragonball-api.com/characters/Bardock_Artwork.webp',
    },
    {
        name: 'Bills',
        imageUrl:
            'https://dragonball-api.com/characters/Beerus_DBS_Broly_Artwork.webp',
    },
    {
        name: 'Broly',
        imageUrl:
            'https://dragonball-api.com/transformaciones/Broly_DBS_Base.webp',
    },
    {
        name: 'Bulma',
        imageUrl: 'https://dragonball-api.com/characters/bulma.webp',
    },
    {
        name: 'Celula',
        imageUrl: 'https://dragonball-api.com/characters/celula.webp',
    },
    {
        name: 'Chi-Chi',
        imageUrl: 'https://dragonball-api.com/characters/ChiChi_DBS.webp',
    },
    {
        name: 'Dende',
        imageUrl: 'https://dragonball-api.com/characters/Dende_Artwork.webp',
    },
    {
        name: 'Dodoria',
        imageUrl: 'https://dragonball-api.com/characters/dodoria.webp',
    },
    {
        name: 'Dyspo',
        imageUrl: 'https://dragonball-api.com/characters/Dispo_render.webp',
    },
    {
        name: 'Freezer',
        imageUrl: 'https://dragonball-api.com/characters/Freezer.webp',
    },
    {
        name: 'Ginyu',
        imageUrl: 'https://dragonball-api.com/characters/ginyu.webp',
    },
    {
        name: 'Gogeta',
        imageUrl: 'https://dragonball-api.com/transformaciones/gogeta.webp',
    },
    {
        name: 'Gohan',
        imageUrl: 'https://dragonball-api.com/characters/gohan.webp',
    },
    {
        name: 'Goku',
        imageUrl: 'https://dragonball-api.com/characters/goku_normal.webp',
    },
    {
        name: 'Gotenks',
        imageUrl: 'https://dragonball-api.com/characters/Gotenks_Artwork.webp',
    },
    {
        name: 'Gran Kaio',
        imageUrl: 'https://dragonball-api.com/characters/Gran_kaio_sama12.webp',
    },
    {
        name: 'Gran Kaio-shin',
        imageUrl:
            'https://dragonball-api.com/characters/Gran_Kaio-shin_Artwork.webp',
    },
    {
        name: 'Grand Priest ',
        imageUrl: 'https://dragonball-api.com/characters/Grand priest.webp',
    },
    {
        name: 'Janemba',
        imageUrl:
            'https://dragonball-api.com/transformaciones/Janemba_artwork_SDBH.webp',
    },
    {
        name: 'Jiren',
        imageUrl: 'https://dragonball-api.com/characters/Jiren.webp',
    },
    {
        name: 'Kaio del este',
        imageUrl: 'https://dragonball-api.com/characters/kaio del este.webp',
    },
    {
        name: 'Kaio del norte (Kaito)',
        imageUrl: 'https://dragonball-api.com/characters/Kaio_del_Norte.webp',
    },
    {
        name: 'Kaio del Oeste',
        imageUrl: 'https://dragonball-api.com/characters/Kaio del oeste.webp',
    },
    {
        name: 'Kaio del Sur',
        imageUrl:
            'https://dragonball-api.com/characters/Kaio_del_sur_cuerpo_completo.webp',
    },
    {
        name: 'Kaio-shin del Este',
        imageUrl:
            'https://dragonball-api.com/characters/Kaio-shin_del_este_Artwork.webp',
    },
    {
        name: 'Kaio-shin del Norte',
        imageUrl:
            'https://dragonball-api.com/characters/Kaio-shin del norte.webp',
    },
    {
        name: 'Kaio-shin del Oeste',
        imageUrl:
            'https://dragonball-api.com/characters/Kaio-shin_del_Oeste_Dokkan.webp',
    },
    {
        name: 'Kaio-shin del Sur',
        imageUrl:
            'https://dragonball-api.com/characters/Kaio-shin_del_Sur_Dokkan.webp',
    },
    {
        name: 'Kibito',
        imageUrl: 'https://dragonball-api.com/characters/Kibito_Artwork.webp',
    },
    {
        name: 'Kibito-Shin',
        imageUrl:
            'https://dragonball-api.com/characters/Kibito_shin_Artwork.webp',
    },
    {
        name: 'Krillin',
        imageUrl: 'https://dragonball-api.com/characters/Krilin_Universo7.webp',
    },
    {
        name: 'Launch',
        imageUrl:
            'https://dragonball-api.com/characters/Lunch_traje_de_sirvienta_en_el_manga.webp',
    },
    {
        name: 'Majin Buu',
        imageUrl:
            'https://dragonball-api.com/characters/BuuGordo_Universo7.webp',
    },
    {
        name: 'Marcarita ',
        imageUrl: 'https://dragonball-api.com/characters/Marcarita.webp',
    },
    {
        name: 'Master Roshi',
        imageUrl: 'https://dragonball-api.com/characters/roshi.webp',
    },
    {
        name: 'Mr. Satan',
        imageUrl: 'https://dragonball-api.com/characters/Mr_Satan_DBSuper.webp',
    },
    {
        name: 'Nail',
        imageUrl: 'https://dragonball-api.com/characters/Nail_Artwork.webp',
    },
    {
        name: 'Piccolo',
        imageUrl: 'https://dragonball-api.com/characters/picolo_normal.webp',
    },
    {
        name: 'Raditz',
        imageUrl:
            'https://dragonball-api.com/characters/Raditz_artwork_Dokkan.webp',
    },
    {
        name: 'Tenshinhan',
        imageUrl:
            'https://dragonball-api.com/characters/Tenshinhan_Universo7.webp',
    },
    {
        name: 'Toppo',
        imageUrl: 'https://dragonball-api.com/characters/Toppo.webp',
    },
    {
        name: 'Trunks',
        imageUrl:
            'https://dragonball-api.com/characters/Trunks_Buu_Artwork.webp',
    },
    {
        name: 'Vegeta',
        imageUrl: 'https://dragonball-api.com/characters/vegeta_normal.webp',
    },
    {
        name: 'Vegetto',
        imageUrl: 'https://dragonball-api.com/transformaciones/Vegetto.webp',
    },
    {
        name: 'Vermoudh',
        imageUrl: 'https://dragonball-api.com/characters/Vermoud.webp',
    },
    {
        name: 'Whis',
        imageUrl:
            'https://dragonball-api.com/characters/Whis_DBS_Broly_Artwork.webp',
    },
    {
        name: 'Yamcha',
        imageUrl: 'https://dragonball-api.com/characters/Final_Yamcha.webp',
    },
    {
        name: 'Zarbon',
        imageUrl: 'https://dragonball-api.com/characters/zarbon.webp',
    },
    {
        name: 'Zeno',
        imageUrl: 'https://dragonball-api.com/characters/Zeno_Artwork.webp',
    },
]
