// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const dragonBallCharacters: Character[] = [
    {
        name: 'Android 13',
        imageUrl: 'dragon-ball/android-13.webp',
    },
    {
        name: 'Android 14',
        imageUrl: 'dragon-ball/android-14.webp',
    },
    {
        name: 'Android 15',
        imageUrl: 'dragon-ball/android-15.webp',
    },
    {
        name: 'Android 16',
        imageUrl: 'dragon-ball/android-16.webp',
    },
    {
        name: 'Android 17',
        imageUrl: 'dragon-ball/android-17.webp',
    },
    {
        name: 'Android 18',
        imageUrl: 'dragon-ball/android-18.webp',
    },
    {
        name: 'Android 19',
        imageUrl: 'dragon-ball/android-19.webp',
    },
    {
        name: 'Android 20 (Dr. Gero)',
        imageUrl: 'dragon-ball/android-20-dr-gero.webp',
    },
    {
        name: 'Babidi',
        imageUrl: 'dragon-ball/babidi.webp',
    },
    {
        name: 'Bardock',
        imageUrl: 'dragon-ball/bardock.webp',
    },
    {
        name: 'Bills',
        imageUrl: 'dragon-ball/bills.webp',
    },
    {
        name: 'Broly',
        imageUrl: 'dragon-ball/broly.webp',
    },
    {
        name: 'Bulma',
        imageUrl: 'dragon-ball/bulma.webp',
    },
    {
        name: 'Celula',
        imageUrl: 'dragon-ball/celula.webp',
    },
    {
        name: 'Chi-Chi',
        imageUrl: 'dragon-ball/chi-chi.webp',
    },
    {
        name: 'Dende',
        imageUrl: 'dragon-ball/dende.webp',
    },
    {
        name: 'Dodoria',
        imageUrl: 'dragon-ball/dodoria.webp',
    },
    {
        name: 'Dyspo',
        imageUrl: 'dragon-ball/dyspo.webp',
    },
    {
        name: 'Freezer',
        imageUrl: 'dragon-ball/freezer.webp',
    },
    {
        name: 'Ginyu',
        imageUrl: 'dragon-ball/ginyu.webp',
    },
    {
        name: 'Gogeta',
        imageUrl: 'dragon-ball/gogeta.webp',
    },
    {
        name: 'Gohan',
        imageUrl: 'dragon-ball/gohan.webp',
    },
    {
        name: 'Goku',
        imageUrl: 'dragon-ball/goku.webp',
    },
    {
        name: 'Gotenks',
        imageUrl: 'dragon-ball/gotenks.webp',
    },
    {
        name: 'Gran Kaio',
        imageUrl: 'dragon-ball/gran-kaio.webp',
    },
    {
        name: 'Gran Kaio-shin',
        imageUrl: 'dragon-ball/gran-kaio-shin.webp',
    },
    {
        name: 'Grand Priest ',
        imageUrl: 'dragon-ball/grand-priest.webp',
    },
    {
        name: 'Janemba',
        imageUrl: 'dragon-ball/janemba.webp',
    },
    {
        name: 'Jiren',
        imageUrl: 'dragon-ball/jiren.webp',
    },
    {
        name: 'Kaio del este',
        imageUrl: 'dragon-ball/kaio-del-este.webp',
    },
    {
        name: 'Kaio del norte (Kaito)',
        imageUrl: 'dragon-ball/kaio-del-norte-kaito.webp',
    },
    {
        name: 'Kaio del Oeste',
        imageUrl: 'dragon-ball/kaio-del-oeste.webp',
    },
    {
        name: 'Kaio del Sur',
        imageUrl: 'dragon-ball/kaio-del-sur.webp',
    },
    {
        name: 'Kaio-shin del Este',
        imageUrl: 'dragon-ball/kaio-shin-del-este.webp',
    },
    {
        name: 'Kaio-shin del Norte',
        imageUrl: 'dragon-ball/kaio-shin-del-norte.webp',
    },
    {
        name: 'Kaio-shin del Oeste',
        imageUrl: 'dragon-ball/kaio-shin-del-oeste.webp',
    },
    {
        name: 'Kaio-shin del Sur',
        imageUrl: 'dragon-ball/kaio-shin-del-sur.webp',
    },
    {
        name: 'Kibito',
        imageUrl: 'dragon-ball/kibito.webp',
    },
    {
        name: 'Kibito-Shin',
        imageUrl: 'dragon-ball/kibito-shin.webp',
    },
    {
        name: 'Krillin',
        imageUrl: 'dragon-ball/krillin.webp',
    },
    {
        name: 'Launch',
        imageUrl: 'dragon-ball/launch.webp',
    },
    {
        name: 'Majin Buu',
        imageUrl: 'dragon-ball/majin-buu.webp',
    },
    {
        name: 'Marcarita ',
        imageUrl: 'dragon-ball/marcarita.webp',
    },
    {
        name: 'Master Roshi',
        imageUrl: 'dragon-ball/master-roshi.webp',
    },
    {
        name: 'Mr. Satan',
        imageUrl: 'dragon-ball/mr-satan.webp',
    },
    {
        name: 'Nail',
        imageUrl: 'dragon-ball/nail.webp',
    },
    {
        name: 'Piccolo',
        imageUrl: 'dragon-ball/piccolo.webp',
    },
    {
        name: 'Raditz',
        imageUrl: 'dragon-ball/raditz.webp',
    },
    {
        name: 'Tenshinhan',
        imageUrl: 'dragon-ball/tenshinhan.webp',
    },
    {
        name: 'Toppo',
        imageUrl: 'dragon-ball/toppo.webp',
    },
    {
        name: 'Trunks',
        imageUrl: 'dragon-ball/trunks.webp',
    },
    {
        name: 'Vegeta',
        imageUrl: 'dragon-ball/vegeta.webp',
    },
    {
        name: 'Vegetto',
        imageUrl: 'dragon-ball/vegetto.webp',
    },
    {
        name: 'Vermoudh',
        imageUrl: 'dragon-ball/vermoudh.webp',
    },
    {
        name: 'Whis',
        imageUrl: 'dragon-ball/whis.webp',
    },
    {
        name: 'Yamcha',
        imageUrl: 'dragon-ball/yamcha.webp',
    },
    {
        name: 'Zarbon',
        imageUrl: 'dragon-ball/zarbon.webp',
    },
    {
        name: 'Zeno',
        imageUrl: 'dragon-ball/zeno.webp',
    },
]
