// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const flagCharacters: Character[] = [
    {
        name: 'Afghanistan',
        imageUrl: 'https://flagcdn.com/w1280/af.webp',
    },
    {
        name: 'Åland Islands',
        imageUrl: 'https://flagcdn.com/w1280/ax.webp',
    },
    {
        name: 'Albania',
        imageUrl: 'https://flagcdn.com/w1280/al.webp',
    },
    {
        name: 'Algeria',
        imageUrl: 'https://flagcdn.com/w1280/dz.webp',
    },
    {
        name: 'American Samoa',
        imageUrl: 'https://flagcdn.com/w1280/as.webp',
    },
    {
        name: 'Andorra',
        imageUrl: 'https://flagcdn.com/w1280/ad.webp',
    },
    {
        name: 'Angola',
        imageUrl: 'https://flagcdn.com/w1280/ao.webp',
    },
    {
        name: 'Anguilla',
        imageUrl: 'https://flagcdn.com/w1280/ai.webp',
    },
    {
        name: 'Antigua and Barbuda',
        imageUrl: 'https://flagcdn.com/w1280/ag.webp',
    },
    {
        name: 'Argentina',
        imageUrl: 'https://flagcdn.com/w1280/ar.webp',
    },
    {
        name: 'Armenia',
        imageUrl: 'https://flagcdn.com/w1280/am.webp',
    },
    {
        name: 'Aruba',
        imageUrl: 'https://flagcdn.com/w1280/aw.webp',
    },
    {
        name: 'Australia',
        imageUrl: 'https://flagcdn.com/w1280/au.webp',
    },
    {
        name: 'Austria',
        imageUrl: 'https://flagcdn.com/w1280/at.webp',
    },
    {
        name: 'Azerbaijan',
        imageUrl: 'https://flagcdn.com/w1280/az.webp',
    },
    {
        name: 'Bahamas',
        imageUrl: 'https://flagcdn.com/w1280/bs.webp',
    },
    {
        name: 'Bahrain',
        imageUrl: 'https://flagcdn.com/w1280/bh.webp',
    },
    {
        name: 'Bangladesh',
        imageUrl: 'https://flagcdn.com/w1280/bd.webp',
    },
    {
        name: 'Barbados',
        imageUrl: 'https://flagcdn.com/w1280/bb.webp',
    },
    {
        name: 'Belarus',
        imageUrl: 'https://flagcdn.com/w1280/by.webp',
    },
    {
        name: 'Belgium',
        imageUrl: 'https://flagcdn.com/w1280/be.webp',
    },
    {
        name: 'Belize',
        imageUrl: 'https://flagcdn.com/w1280/bz.webp',
    },
    {
        name: 'Benin',
        imageUrl: 'https://flagcdn.com/w1280/bj.webp',
    },
    {
        name: 'Bermuda',
        imageUrl: 'https://flagcdn.com/w1280/bm.webp',
    },
    {
        name: 'Bhutan',
        imageUrl: 'https://flagcdn.com/w1280/bt.webp',
    },
    {
        name: 'Bolivia',
        imageUrl: 'https://flagcdn.com/w1280/bo.webp',
    },
    {
        name: 'Bosnia and Herzegovina',
        imageUrl: 'https://flagcdn.com/w1280/ba.webp',
    },
    {
        name: 'Botswana',
        imageUrl: 'https://flagcdn.com/w1280/bw.webp',
    },
    {
        name: 'Brazil',
        imageUrl: 'https://flagcdn.com/w1280/br.webp',
    },
    {
        name: 'British Virgin Islands',
        imageUrl: 'https://flagcdn.com/w1280/vg.webp',
    },
    {
        name: 'Brunei',
        imageUrl: 'https://flagcdn.com/w1280/bn.webp',
    },
    {
        name: 'Bulgaria',
        imageUrl: 'https://flagcdn.com/w1280/bg.webp',
    },
    {
        name: 'Burkina Faso',
        imageUrl: 'https://flagcdn.com/w1280/bf.webp',
    },
    {
        name: 'Burundi',
        imageUrl: 'https://flagcdn.com/w1280/bi.webp',
    },
    {
        name: 'Cambodia',
        imageUrl: 'https://flagcdn.com/w1280/kh.webp',
    },
    {
        name: 'Cameroon',
        imageUrl: 'https://flagcdn.com/w1280/cm.webp',
    },
    {
        name: 'Canada',
        imageUrl: 'https://flagcdn.com/w1280/ca.webp',
    },
    {
        name: 'Cape Verde',
        imageUrl: 'https://flagcdn.com/w1280/cv.webp',
    },
    {
        name: 'Caribbean Netherlands',
        imageUrl: 'https://flagcdn.com/w1280/bq.webp',
    },
    {
        name: 'Cayman Islands',
        imageUrl: 'https://flagcdn.com/w1280/ky.webp',
    },
    {
        name: 'Central African Republic',
        imageUrl: 'https://flagcdn.com/w1280/cf.webp',
    },
    {
        name: 'Chad',
        imageUrl: 'https://flagcdn.com/w1280/td.webp',
    },
    {
        name: 'Chile',
        imageUrl: 'https://flagcdn.com/w1280/cl.webp',
    },
    {
        name: 'China',
        imageUrl: 'https://flagcdn.com/w1280/cn.webp',
    },
    {
        name: 'Christmas Island',
        imageUrl: 'https://flagcdn.com/w1280/cx.webp',
    },
    {
        name: 'Cocos (Keeling) Islands',
        imageUrl: 'https://flagcdn.com/w1280/cc.webp',
    },
    {
        name: 'Colombia',
        imageUrl: 'https://flagcdn.com/w1280/co.webp',
    },
    {
        name: 'Comoros',
        imageUrl: 'https://flagcdn.com/w1280/km.webp',
    },
    {
        name: 'Cook Islands',
        imageUrl: 'https://flagcdn.com/w1280/ck.webp',
    },
    {
        name: 'Costa Rica',
        imageUrl: 'https://flagcdn.com/w1280/cr.webp',
    },
    {
        name: "Côte d'Ivoire (Ivory Coast)",
        imageUrl: 'https://flagcdn.com/w1280/ci.webp',
    },
    {
        name: 'Croatia',
        imageUrl: 'https://flagcdn.com/w1280/hr.webp',
    },
    {
        name: 'Cuba',
        imageUrl: 'https://flagcdn.com/w1280/cu.webp',
    },
    {
        name: 'Curaçao',
        imageUrl: 'https://flagcdn.com/w1280/cw.webp',
    },
    {
        name: 'Cyprus',
        imageUrl: 'https://flagcdn.com/w1280/cy.webp',
    },
    {
        name: 'Czechia',
        imageUrl: 'https://flagcdn.com/w1280/cz.webp',
    },
    {
        name: 'Denmark',
        imageUrl: 'https://flagcdn.com/w1280/dk.webp',
    },
    {
        name: 'Djibouti',
        imageUrl: 'https://flagcdn.com/w1280/dj.webp',
    },
    {
        name: 'Dominica',
        imageUrl: 'https://flagcdn.com/w1280/dm.webp',
    },
    {
        name: 'Dominican Republic',
        imageUrl: 'https://flagcdn.com/w1280/do.webp',
    },
    {
        name: 'DR Congo',
        imageUrl: 'https://flagcdn.com/w1280/cd.webp',
    },
    {
        name: 'Ecuador',
        imageUrl: 'https://flagcdn.com/w1280/ec.webp',
    },
    {
        name: 'Egypt',
        imageUrl: 'https://flagcdn.com/w1280/eg.webp',
    },
    {
        name: 'El Salvador',
        imageUrl: 'https://flagcdn.com/w1280/sv.webp',
    },
    {
        name: 'Equatorial Guinea',
        imageUrl: 'https://flagcdn.com/w1280/gq.webp',
    },
    {
        name: 'Eritrea',
        imageUrl: 'https://flagcdn.com/w1280/er.webp',
    },
    {
        name: 'Estonia',
        imageUrl: 'https://flagcdn.com/w1280/ee.webp',
    },
    {
        name: 'Eswatini (Swaziland)',
        imageUrl: 'https://flagcdn.com/w1280/sz.webp',
    },
    {
        name: 'Ethiopia',
        imageUrl: 'https://flagcdn.com/w1280/et.webp',
    },
    {
        name: 'Falkland Islands',
        imageUrl: 'https://flagcdn.com/w1280/fk.webp',
    },
    {
        name: 'Faroe Islands',
        imageUrl: 'https://flagcdn.com/w1280/fo.webp',
    },
    {
        name: 'Fiji',
        imageUrl: 'https://flagcdn.com/w1280/fj.webp',
    },
    {
        name: 'Finland',
        imageUrl: 'https://flagcdn.com/w1280/fi.webp',
    },
    {
        name: 'France',
        imageUrl: 'https://flagcdn.com/w1280/fr.webp',
    },
    {
        name: 'French Guiana',
        imageUrl: 'https://flagcdn.com/w1280/gf.webp',
    },
    {
        name: 'French Polynesia',
        imageUrl: 'https://flagcdn.com/w1280/pf.webp',
    },
    {
        name: 'Gabon',
        imageUrl: 'https://flagcdn.com/w1280/ga.webp',
    },
    {
        name: 'Gambia',
        imageUrl: 'https://flagcdn.com/w1280/gm.webp',
    },
    {
        name: 'Georgia',
        imageUrl: 'https://flagcdn.com/w1280/ge.webp',
    },
    {
        name: 'Germany',
        imageUrl: 'https://flagcdn.com/w1280/de.webp',
    },
    {
        name: 'Ghana',
        imageUrl: 'https://flagcdn.com/w1280/gh.webp',
    },
    {
        name: 'Gibraltar',
        imageUrl: 'https://flagcdn.com/w1280/gi.webp',
    },
    {
        name: 'Greece',
        imageUrl: 'https://flagcdn.com/w1280/gr.webp',
    },
    {
        name: 'Greenland',
        imageUrl: 'https://flagcdn.com/w1280/gl.webp',
    },
    {
        name: 'Grenada',
        imageUrl: 'https://flagcdn.com/w1280/gd.webp',
    },
    {
        name: 'Guadeloupe',
        imageUrl: 'https://flagcdn.com/w1280/gp.webp',
    },
    {
        name: 'Guam',
        imageUrl: 'https://flagcdn.com/w1280/gu.webp',
    },
    {
        name: 'Guatemala',
        imageUrl: 'https://flagcdn.com/w1280/gt.webp',
    },
    {
        name: 'Guernsey',
        imageUrl: 'https://flagcdn.com/w1280/gg.webp',
    },
    {
        name: 'Guinea',
        imageUrl: 'https://flagcdn.com/w1280/gn.webp',
    },
    {
        name: 'Guinea-Bissau',
        imageUrl: 'https://flagcdn.com/w1280/gw.webp',
    },
    {
        name: 'Guyana',
        imageUrl: 'https://flagcdn.com/w1280/gy.webp',
    },
    {
        name: 'Haiti',
        imageUrl: 'https://flagcdn.com/w1280/ht.webp',
    },
    {
        name: 'Honduras',
        imageUrl: 'https://flagcdn.com/w1280/hn.webp',
    },
    {
        name: 'Hong Kong',
        imageUrl: 'https://flagcdn.com/w1280/hk.webp',
    },
    {
        name: 'Hungary',
        imageUrl: 'https://flagcdn.com/w1280/hu.webp',
    },
    {
        name: 'Iceland',
        imageUrl: 'https://flagcdn.com/w1280/is.webp',
    },
    {
        name: 'India',
        imageUrl: 'https://flagcdn.com/w1280/in.webp',
    },
    {
        name: 'Indonesia',
        imageUrl: 'https://flagcdn.com/w1280/id.webp',
    },
    {
        name: 'Iran',
        imageUrl: 'https://flagcdn.com/w1280/ir.webp',
    },
    {
        name: 'Iraq',
        imageUrl: 'https://flagcdn.com/w1280/iq.webp',
    },
    {
        name: 'Ireland',
        imageUrl: 'https://flagcdn.com/w1280/ie.webp',
    },
    {
        name: 'Isle of Man',
        imageUrl: 'https://flagcdn.com/w1280/im.webp',
    },
    {
        name: 'Israel',
        imageUrl: 'https://flagcdn.com/w1280/il.webp',
    },
    {
        name: 'Italy',
        imageUrl: 'https://flagcdn.com/w1280/it.webp',
    },
    {
        name: 'Jamaica',
        imageUrl: 'https://flagcdn.com/w1280/jm.webp',
    },
    {
        name: 'Japan',
        imageUrl: 'https://flagcdn.com/w1280/jp.webp',
    },
    {
        name: 'Jersey',
        imageUrl: 'https://flagcdn.com/w1280/je.webp',
    },
    {
        name: 'Jordan',
        imageUrl: 'https://flagcdn.com/w1280/jo.webp',
    },
    {
        name: 'Kazakhstan',
        imageUrl: 'https://flagcdn.com/w1280/kz.webp',
    },
    {
        name: 'Kenya',
        imageUrl: 'https://flagcdn.com/w1280/ke.webp',
    },
    {
        name: 'Kiribati',
        imageUrl: 'https://flagcdn.com/w1280/ki.webp',
    },
    {
        name: 'Kuwait',
        imageUrl: 'https://flagcdn.com/w1280/kw.webp',
    },
    {
        name: 'Kyrgyzstan',
        imageUrl: 'https://flagcdn.com/w1280/kg.webp',
    },
    {
        name: 'Laos',
        imageUrl: 'https://flagcdn.com/w1280/la.webp',
    },
    {
        name: 'Latvia',
        imageUrl: 'https://flagcdn.com/w1280/lv.webp',
    },
    {
        name: 'Lebanon',
        imageUrl: 'https://flagcdn.com/w1280/lb.webp',
    },
    {
        name: 'Lesotho',
        imageUrl: 'https://flagcdn.com/w1280/ls.webp',
    },
    {
        name: 'Liberia',
        imageUrl: 'https://flagcdn.com/w1280/lr.webp',
    },
    {
        name: 'Libya',
        imageUrl: 'https://flagcdn.com/w1280/ly.webp',
    },
    {
        name: 'Liechtenstein',
        imageUrl: 'https://flagcdn.com/w1280/li.webp',
    },
    {
        name: 'Lithuania',
        imageUrl: 'https://flagcdn.com/w1280/lt.webp',
    },
    {
        name: 'Luxembourg',
        imageUrl: 'https://flagcdn.com/w1280/lu.webp',
    },
    {
        name: 'Macau',
        imageUrl: 'https://flagcdn.com/w1280/mo.webp',
    },
    {
        name: 'Madagascar',
        imageUrl: 'https://flagcdn.com/w1280/mg.webp',
    },
    {
        name: 'Malawi',
        imageUrl: 'https://flagcdn.com/w1280/mw.webp',
    },
    {
        name: 'Malaysia',
        imageUrl: 'https://flagcdn.com/w1280/my.webp',
    },
    {
        name: 'Maldives',
        imageUrl: 'https://flagcdn.com/w1280/mv.webp',
    },
    {
        name: 'Mali',
        imageUrl: 'https://flagcdn.com/w1280/ml.webp',
    },
    {
        name: 'Malta',
        imageUrl: 'https://flagcdn.com/w1280/mt.webp',
    },
    {
        name: 'Marshall Islands',
        imageUrl: 'https://flagcdn.com/w1280/mh.webp',
    },
    {
        name: 'Martinique',
        imageUrl: 'https://flagcdn.com/w1280/mq.webp',
    },
    {
        name: 'Mauritania',
        imageUrl: 'https://flagcdn.com/w1280/mr.webp',
    },
    {
        name: 'Mauritius',
        imageUrl: 'https://flagcdn.com/w1280/mu.webp',
    },
    {
        name: 'Mayotte',
        imageUrl: 'https://flagcdn.com/w1280/yt.webp',
    },
    {
        name: 'Mexico',
        imageUrl: 'https://flagcdn.com/w1280/mx.webp',
    },
    {
        name: 'Micronesia',
        imageUrl: 'https://flagcdn.com/w1280/fm.webp',
    },
    {
        name: 'Moldova',
        imageUrl: 'https://flagcdn.com/w1280/md.webp',
    },
    {
        name: 'Monaco',
        imageUrl: 'https://flagcdn.com/w1280/mc.webp',
    },
    {
        name: 'Mongolia',
        imageUrl: 'https://flagcdn.com/w1280/mn.webp',
    },
    {
        name: 'Montenegro',
        imageUrl: 'https://flagcdn.com/w1280/me.webp',
    },
    {
        name: 'Montserrat',
        imageUrl: 'https://flagcdn.com/w1280/ms.webp',
    },
    {
        name: 'Morocco',
        imageUrl: 'https://flagcdn.com/w1280/ma.webp',
    },
    {
        name: 'Mozambique',
        imageUrl: 'https://flagcdn.com/w1280/mz.webp',
    },
    {
        name: 'Myanmar',
        imageUrl: 'https://flagcdn.com/w1280/mm.webp',
    },
    {
        name: 'Namibia',
        imageUrl: 'https://flagcdn.com/w1280/na.webp',
    },
    {
        name: 'Nauru',
        imageUrl: 'https://flagcdn.com/w1280/nr.webp',
    },
    {
        name: 'Nepal',
        imageUrl: 'https://flagcdn.com/w1280/np.webp',
    },
    {
        name: 'Netherlands',
        imageUrl: 'https://flagcdn.com/w1280/nl.webp',
    },
    {
        name: 'New Caledonia',
        imageUrl: 'https://flagcdn.com/w1280/nc.webp',
    },
    {
        name: 'New Zealand',
        imageUrl: 'https://flagcdn.com/w1280/nz.webp',
    },
    {
        name: 'Nicaragua',
        imageUrl: 'https://flagcdn.com/w1280/ni.webp',
    },
    {
        name: 'Niger',
        imageUrl: 'https://flagcdn.com/w1280/ne.webp',
    },
    {
        name: 'Nigeria',
        imageUrl: 'https://flagcdn.com/w1280/ng.webp',
    },
    {
        name: 'Niue',
        imageUrl: 'https://flagcdn.com/w1280/nu.webp',
    },
    {
        name: 'Norfolk Island',
        imageUrl: 'https://flagcdn.com/w1280/nf.webp',
    },
    {
        name: 'North Korea',
        imageUrl: 'https://flagcdn.com/w1280/kp.webp',
    },
    {
        name: 'North Macedonia',
        imageUrl: 'https://flagcdn.com/w1280/mk.webp',
    },
    {
        name: 'Northern Mariana Islands',
        imageUrl: 'https://flagcdn.com/w1280/mp.webp',
    },
    {
        name: 'Norway',
        imageUrl: 'https://flagcdn.com/w1280/no.webp',
    },
    {
        name: 'Oman',
        imageUrl: 'https://flagcdn.com/w1280/om.webp',
    },
    {
        name: 'Pakistan',
        imageUrl: 'https://flagcdn.com/w1280/pk.webp',
    },
    {
        name: 'Palau',
        imageUrl: 'https://flagcdn.com/w1280/pw.webp',
    },
    {
        name: 'Palestine',
        imageUrl: 'https://flagcdn.com/w1280/ps.webp',
    },
    {
        name: 'Panama',
        imageUrl: 'https://flagcdn.com/w1280/pa.webp',
    },
    {
        name: 'Papua New Guinea',
        imageUrl: 'https://flagcdn.com/w1280/pg.webp',
    },
    {
        name: 'Paraguay',
        imageUrl: 'https://flagcdn.com/w1280/py.webp',
    },
    {
        name: 'Peru',
        imageUrl: 'https://flagcdn.com/w1280/pe.webp',
    },
    {
        name: 'Philippines',
        imageUrl: 'https://flagcdn.com/w1280/ph.webp',
    },
    {
        name: 'Pitcairn Islands',
        imageUrl: 'https://flagcdn.com/w1280/pn.webp',
    },
    {
        name: 'Poland',
        imageUrl: 'https://flagcdn.com/w1280/pl.webp',
    },
    {
        name: 'Portugal',
        imageUrl: 'https://flagcdn.com/w1280/pt.webp',
    },
    {
        name: 'Puerto Rico',
        imageUrl: 'https://flagcdn.com/w1280/pr.webp',
    },
    {
        name: 'Qatar',
        imageUrl: 'https://flagcdn.com/w1280/qa.webp',
    },
    {
        name: 'Republic of the Congo',
        imageUrl: 'https://flagcdn.com/w1280/cg.webp',
    },
    {
        name: 'Réunion',
        imageUrl: 'https://flagcdn.com/w1280/re.webp',
    },
    {
        name: 'Romania',
        imageUrl: 'https://flagcdn.com/w1280/ro.webp',
    },
    {
        name: 'Russia',
        imageUrl: 'https://flagcdn.com/w1280/ru.webp',
    },
    {
        name: 'Rwanda',
        imageUrl: 'https://flagcdn.com/w1280/rw.webp',
    },
    {
        name: 'Saint Barthélemy',
        imageUrl: 'https://flagcdn.com/w1280/bl.webp',
    },
    {
        name: 'Saint Kitts and Nevis',
        imageUrl: 'https://flagcdn.com/w1280/kn.webp',
    },
    {
        name: 'Saint Lucia',
        imageUrl: 'https://flagcdn.com/w1280/lc.webp',
    },
    {
        name: 'Saint Martin',
        imageUrl: 'https://flagcdn.com/w1280/mf.webp',
    },
    {
        name: 'Saint Pierre and Miquelon',
        imageUrl: 'https://flagcdn.com/w1280/pm.webp',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        imageUrl: 'https://flagcdn.com/w1280/vc.webp',
    },
    {
        name: 'Samoa',
        imageUrl: 'https://flagcdn.com/w1280/ws.webp',
    },
    {
        name: 'San Marino',
        imageUrl: 'https://flagcdn.com/w1280/sm.webp',
    },
    {
        name: 'São Tomé and Príncipe',
        imageUrl: 'https://flagcdn.com/w1280/st.webp',
    },
    {
        name: 'Saudi Arabia',
        imageUrl: 'https://flagcdn.com/w1280/sa.webp',
    },
    {
        name: 'Senegal',
        imageUrl: 'https://flagcdn.com/w1280/sn.webp',
    },
    {
        name: 'Serbia',
        imageUrl: 'https://flagcdn.com/w1280/rs.webp',
    },
    {
        name: 'Seychelles',
        imageUrl: 'https://flagcdn.com/w1280/sc.webp',
    },
    {
        name: 'Sierra Leone',
        imageUrl: 'https://flagcdn.com/w1280/sl.webp',
    },
    {
        name: 'Singapore',
        imageUrl: 'https://flagcdn.com/w1280/sg.webp',
    },
    {
        name: 'Sint Maarten',
        imageUrl: 'https://flagcdn.com/w1280/sx.webp',
    },
    {
        name: 'Slovakia',
        imageUrl: 'https://flagcdn.com/w1280/sk.webp',
    },
    {
        name: 'Slovenia',
        imageUrl: 'https://flagcdn.com/w1280/si.webp',
    },
    {
        name: 'Solomon Islands',
        imageUrl: 'https://flagcdn.com/w1280/sb.webp',
    },
    {
        name: 'Somalia',
        imageUrl: 'https://flagcdn.com/w1280/so.webp',
    },
    {
        name: 'South Africa',
        imageUrl: 'https://flagcdn.com/w1280/za.webp',
    },
    {
        name: 'South Korea',
        imageUrl: 'https://flagcdn.com/w1280/kr.webp',
    },
    {
        name: 'South Sudan',
        imageUrl: 'https://flagcdn.com/w1280/ss.webp',
    },
    {
        name: 'Spain',
        imageUrl: 'https://flagcdn.com/w1280/es.webp',
    },
    {
        name: 'Sri Lanka',
        imageUrl: 'https://flagcdn.com/w1280/lk.webp',
    },
    {
        name: 'Sudan',
        imageUrl: 'https://flagcdn.com/w1280/sd.webp',
    },
    {
        name: 'Suriname',
        imageUrl: 'https://flagcdn.com/w1280/sr.webp',
    },
    {
        name: 'Sweden',
        imageUrl: 'https://flagcdn.com/w1280/se.webp',
    },
    {
        name: 'Switzerland',
        imageUrl: 'https://flagcdn.com/w1280/ch.webp',
    },
    {
        name: 'Syria',
        imageUrl: 'https://flagcdn.com/w1280/sy.webp',
    },
    {
        name: 'Taiwan',
        imageUrl: 'https://flagcdn.com/w1280/tw.webp',
    },
    {
        name: 'Tajikistan',
        imageUrl: 'https://flagcdn.com/w1280/tj.webp',
    },
    {
        name: 'Tanzania',
        imageUrl: 'https://flagcdn.com/w1280/tz.webp',
    },
    {
        name: 'Thailand',
        imageUrl: 'https://flagcdn.com/w1280/th.webp',
    },
    {
        name: 'Timor-Leste',
        imageUrl: 'https://flagcdn.com/w1280/tl.webp',
    },
    {
        name: 'Togo',
        imageUrl: 'https://flagcdn.com/w1280/tg.webp',
    },
    {
        name: 'Tokelau',
        imageUrl: 'https://flagcdn.com/w1280/tk.webp',
    },
    {
        name: 'Tonga',
        imageUrl: 'https://flagcdn.com/w1280/to.webp',
    },
    {
        name: 'Trinidad and Tobago',
        imageUrl: 'https://flagcdn.com/w1280/tt.webp',
    },
    {
        name: 'Tunisia',
        imageUrl: 'https://flagcdn.com/w1280/tn.webp',
    },
    {
        name: 'Turkey',
        imageUrl: 'https://flagcdn.com/w1280/tr.webp',
    },
    {
        name: 'Turkmenistan',
        imageUrl: 'https://flagcdn.com/w1280/tm.webp',
    },
    {
        name: 'Turks and Caicos Islands',
        imageUrl: 'https://flagcdn.com/w1280/tc.webp',
    },
    {
        name: 'Tuvalu',
        imageUrl: 'https://flagcdn.com/w1280/tv.webp',
    },
    {
        name: 'Uganda',
        imageUrl: 'https://flagcdn.com/w1280/ug.webp',
    },
    {
        name: 'Ukraine',
        imageUrl: 'https://flagcdn.com/w1280/ua.webp',
    },
    {
        name: 'United Arab Emirates',
        imageUrl: 'https://flagcdn.com/w1280/ae.webp',
    },
    {
        name: 'United Kingdom',
        imageUrl: 'https://flagcdn.com/w1280/gb.webp',
    },
    {
        name: 'United States',
        imageUrl: 'https://flagcdn.com/w1280/us.webp',
    },
    {
        name: 'United States Virgin Islands',
        imageUrl: 'https://flagcdn.com/w1280/vi.webp',
    },
    {
        name: 'Uruguay',
        imageUrl: 'https://flagcdn.com/w1280/uy.webp',
    },
    {
        name: 'Uzbekistan',
        imageUrl: 'https://flagcdn.com/w1280/uz.webp',
    },
    {
        name: 'Vanuatu',
        imageUrl: 'https://flagcdn.com/w1280/vu.webp',
    },
    {
        name: 'Vatican City (Holy See)',
        imageUrl: 'https://flagcdn.com/w1280/va.webp',
    },
    {
        name: 'Venezuela',
        imageUrl: 'https://flagcdn.com/w1280/ve.webp',
    },
    {
        name: 'Vietnam',
        imageUrl: 'https://flagcdn.com/w1280/vn.webp',
    },
    {
        name: 'Wallis and Futuna',
        imageUrl: 'https://flagcdn.com/w1280/wf.webp',
    },
    {
        name: 'Western Sahara',
        imageUrl: 'https://flagcdn.com/w1280/eh.webp',
    },
    {
        name: 'Yemen',
        imageUrl: 'https://flagcdn.com/w1280/ye.webp',
    },
    {
        name: 'Zambia',
        imageUrl: 'https://flagcdn.com/w1280/zm.webp',
    },
    {
        name: 'Zimbabwe',
        imageUrl: 'https://flagcdn.com/w1280/zw.webp',
    },
]
