// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const flagCharacters: Character[] = [
    {
        name: 'Afghanistan',
        imageUrl: 'flags/afghanistan.webp',
    },
    {
        name: 'Åland Islands',
        imageUrl: 'flags/aland-islands.webp',
    },
    {
        name: 'Albania',
        imageUrl: 'flags/albania.webp',
    },
    {
        name: 'Algeria',
        imageUrl: 'flags/algeria.webp',
    },
    {
        name: 'American Samoa',
        imageUrl: 'flags/american-samoa.webp',
    },
    {
        name: 'Andorra',
        imageUrl: 'flags/andorra.webp',
    },
    {
        name: 'Angola',
        imageUrl: 'flags/angola.webp',
    },
    {
        name: 'Anguilla',
        imageUrl: 'flags/anguilla.webp',
    },
    {
        name: 'Antigua and Barbuda',
        imageUrl: 'flags/antigua-and-barbuda.webp',
    },
    {
        name: 'Argentina',
        imageUrl: 'flags/argentina.webp',
    },
    {
        name: 'Armenia',
        imageUrl: 'flags/armenia.webp',
    },
    {
        name: 'Aruba',
        imageUrl: 'flags/aruba.webp',
    },
    {
        name: 'Australia',
        imageUrl: 'flags/australia.webp',
    },
    {
        name: 'Austria',
        imageUrl: 'flags/austria.webp',
    },
    {
        name: 'Azerbaijan',
        imageUrl: 'flags/azerbaijan.webp',
    },
    {
        name: 'Bahamas',
        imageUrl: 'flags/bahamas.webp',
    },
    {
        name: 'Bahrain',
        imageUrl: 'flags/bahrain.webp',
    },
    {
        name: 'Bangladesh',
        imageUrl: 'flags/bangladesh.webp',
    },
    {
        name: 'Barbados',
        imageUrl: 'flags/barbados.webp',
    },
    {
        name: 'Belarus',
        imageUrl: 'flags/belarus.webp',
    },
    {
        name: 'Belgium',
        imageUrl: 'flags/belgium.webp',
    },
    {
        name: 'Belize',
        imageUrl: 'flags/belize.webp',
    },
    {
        name: 'Benin',
        imageUrl: 'flags/benin.webp',
    },
    {
        name: 'Bermuda',
        imageUrl: 'flags/bermuda.webp',
    },
    {
        name: 'Bhutan',
        imageUrl: 'flags/bhutan.webp',
    },
    {
        name: 'Bolivia',
        imageUrl: 'flags/bolivia.webp',
    },
    {
        name: 'Bosnia and Herzegovina',
        imageUrl: 'flags/bosnia-and-herzegovina.webp',
    },
    {
        name: 'Botswana',
        imageUrl: 'flags/botswana.webp',
    },
    {
        name: 'Brazil',
        imageUrl: 'flags/brazil.webp',
    },
    {
        name: 'British Virgin Islands',
        imageUrl: 'flags/british-virgin-islands.webp',
    },
    {
        name: 'Brunei',
        imageUrl: 'flags/brunei.webp',
    },
    {
        name: 'Bulgaria',
        imageUrl: 'flags/bulgaria.webp',
    },
    {
        name: 'Burkina Faso',
        imageUrl: 'flags/burkina-faso.webp',
    },
    {
        name: 'Burundi',
        imageUrl: 'flags/burundi.webp',
    },
    {
        name: 'Cambodia',
        imageUrl: 'flags/cambodia.webp',
    },
    {
        name: 'Cameroon',
        imageUrl: 'flags/cameroon.webp',
    },
    {
        name: 'Canada',
        imageUrl: 'flags/canada.webp',
    },
    {
        name: 'Cape Verde',
        imageUrl: 'flags/cape-verde.webp',
    },
    {
        name: 'Caribbean Netherlands',
        imageUrl: 'flags/caribbean-netherlands.webp',
    },
    {
        name: 'Cayman Islands',
        imageUrl: 'flags/cayman-islands.webp',
    },
    {
        name: 'Central African Republic',
        imageUrl: 'flags/central-african-republic.webp',
    },
    {
        name: 'Chad',
        imageUrl: 'flags/chad.webp',
    },
    {
        name: 'Chile',
        imageUrl: 'flags/chile.webp',
    },
    {
        name: 'China',
        imageUrl: 'flags/china.webp',
    },
    {
        name: 'Christmas Island',
        imageUrl: 'flags/christmas-island.webp',
    },
    {
        name: 'Cocos (Keeling) Islands',
        imageUrl: 'flags/cocos-keeling-islands.webp',
    },
    {
        name: 'Colombia',
        imageUrl: 'flags/colombia.webp',
    },
    {
        name: 'Comoros',
        imageUrl: 'flags/comoros.webp',
    },
    {
        name: 'Cook Islands',
        imageUrl: 'flags/cook-islands.webp',
    },
    {
        name: 'Costa Rica',
        imageUrl: 'flags/costa-rica.webp',
    },
    {
        name: "Côte d'Ivoire (Ivory Coast)",
        imageUrl: 'flags/cote-d-ivoire-ivory-coast.webp',
    },
    {
        name: 'Croatia',
        imageUrl: 'flags/croatia.webp',
    },
    {
        name: 'Cuba',
        imageUrl: 'flags/cuba.webp',
    },
    {
        name: 'Curaçao',
        imageUrl: 'flags/curacao.webp',
    },
    {
        name: 'Cyprus',
        imageUrl: 'flags/cyprus.webp',
    },
    {
        name: 'Czechia',
        imageUrl: 'flags/czechia.webp',
    },
    {
        name: 'Denmark',
        imageUrl: 'flags/denmark.webp',
    },
    {
        name: 'Djibouti',
        imageUrl: 'flags/djibouti.webp',
    },
    {
        name: 'Dominica',
        imageUrl: 'flags/dominica.webp',
    },
    {
        name: 'Dominican Republic',
        imageUrl: 'flags/dominican-republic.webp',
    },
    {
        name: 'DR Congo',
        imageUrl: 'flags/dr-congo.webp',
    },
    {
        name: 'Ecuador',
        imageUrl: 'flags/ecuador.webp',
    },
    {
        name: 'Egypt',
        imageUrl: 'flags/egypt.webp',
    },
    {
        name: 'El Salvador',
        imageUrl: 'flags/el-salvador.webp',
    },
    {
        name: 'Equatorial Guinea',
        imageUrl: 'flags/equatorial-guinea.webp',
    },
    {
        name: 'Eritrea',
        imageUrl: 'flags/eritrea.webp',
    },
    {
        name: 'Estonia',
        imageUrl: 'flags/estonia.webp',
    },
    {
        name: 'Eswatini (Swaziland)',
        imageUrl: 'flags/eswatini-swaziland.webp',
    },
    {
        name: 'Ethiopia',
        imageUrl: 'flags/ethiopia.webp',
    },
    {
        name: 'Falkland Islands',
        imageUrl: 'flags/falkland-islands.webp',
    },
    {
        name: 'Faroe Islands',
        imageUrl: 'flags/faroe-islands.webp',
    },
    {
        name: 'Fiji',
        imageUrl: 'flags/fiji.webp',
    },
    {
        name: 'Finland',
        imageUrl: 'flags/finland.webp',
    },
    {
        name: 'France',
        imageUrl: 'flags/france.webp',
    },
    {
        name: 'French Guiana',
        imageUrl: 'flags/french-guiana.webp',
    },
    {
        name: 'French Polynesia',
        imageUrl: 'flags/french-polynesia.webp',
    },
    {
        name: 'Gabon',
        imageUrl: 'flags/gabon.webp',
    },
    {
        name: 'Gambia',
        imageUrl: 'flags/gambia.webp',
    },
    {
        name: 'Georgia',
        imageUrl: 'flags/georgia.webp',
    },
    {
        name: 'Germany',
        imageUrl: 'flags/germany.webp',
    },
    {
        name: 'Ghana',
        imageUrl: 'flags/ghana.webp',
    },
    {
        name: 'Gibraltar',
        imageUrl: 'flags/gibraltar.webp',
    },
    {
        name: 'Greece',
        imageUrl: 'flags/greece.webp',
    },
    {
        name: 'Greenland',
        imageUrl: 'flags/greenland.webp',
    },
    {
        name: 'Grenada',
        imageUrl: 'flags/grenada.webp',
    },
    {
        name: 'Guadeloupe',
        imageUrl: 'flags/guadeloupe.webp',
    },
    {
        name: 'Guam',
        imageUrl: 'flags/guam.webp',
    },
    {
        name: 'Guatemala',
        imageUrl: 'flags/guatemala.webp',
    },
    {
        name: 'Guernsey',
        imageUrl: 'flags/guernsey.webp',
    },
    {
        name: 'Guinea',
        imageUrl: 'flags/guinea.webp',
    },
    {
        name: 'Guinea-Bissau',
        imageUrl: 'flags/guinea-bissau.webp',
    },
    {
        name: 'Guyana',
        imageUrl: 'flags/guyana.webp',
    },
    {
        name: 'Haiti',
        imageUrl: 'flags/haiti.webp',
    },
    {
        name: 'Honduras',
        imageUrl: 'flags/honduras.webp',
    },
    {
        name: 'Hong Kong',
        imageUrl: 'flags/hong-kong.webp',
    },
    {
        name: 'Hungary',
        imageUrl: 'flags/hungary.webp',
    },
    {
        name: 'Iceland',
        imageUrl: 'flags/iceland.webp',
    },
    {
        name: 'India',
        imageUrl: 'flags/india.webp',
    },
    {
        name: 'Indonesia',
        imageUrl: 'flags/indonesia.webp',
    },
    {
        name: 'Iran',
        imageUrl: 'flags/iran.webp',
    },
    {
        name: 'Iraq',
        imageUrl: 'flags/iraq.webp',
    },
    {
        name: 'Ireland',
        imageUrl: 'flags/ireland.webp',
    },
    {
        name: 'Isle of Man',
        imageUrl: 'flags/isle-of-man.webp',
    },
    {
        name: 'Israel',
        imageUrl: 'flags/israel.webp',
    },
    {
        name: 'Italy',
        imageUrl: 'flags/italy.webp',
    },
    {
        name: 'Jamaica',
        imageUrl: 'flags/jamaica.webp',
    },
    {
        name: 'Japan',
        imageUrl: 'flags/japan.webp',
    },
    {
        name: 'Jersey',
        imageUrl: 'flags/jersey.webp',
    },
    {
        name: 'Jordan',
        imageUrl: 'flags/jordan.webp',
    },
    {
        name: 'Kazakhstan',
        imageUrl: 'flags/kazakhstan.webp',
    },
    {
        name: 'Kenya',
        imageUrl: 'flags/kenya.webp',
    },
    {
        name: 'Kiribati',
        imageUrl: 'flags/kiribati.webp',
    },
    {
        name: 'Kuwait',
        imageUrl: 'flags/kuwait.webp',
    },
    {
        name: 'Kyrgyzstan',
        imageUrl: 'flags/kyrgyzstan.webp',
    },
    {
        name: 'Laos',
        imageUrl: 'flags/laos.webp',
    },
    {
        name: 'Latvia',
        imageUrl: 'flags/latvia.webp',
    },
    {
        name: 'Lebanon',
        imageUrl: 'flags/lebanon.webp',
    },
    {
        name: 'Lesotho',
        imageUrl: 'flags/lesotho.webp',
    },
    {
        name: 'Liberia',
        imageUrl: 'flags/liberia.webp',
    },
    {
        name: 'Libya',
        imageUrl: 'flags/libya.webp',
    },
    {
        name: 'Liechtenstein',
        imageUrl: 'flags/liechtenstein.webp',
    },
    {
        name: 'Lithuania',
        imageUrl: 'flags/lithuania.webp',
    },
    {
        name: 'Luxembourg',
        imageUrl: 'flags/luxembourg.webp',
    },
    {
        name: 'Macau',
        imageUrl: 'flags/macau.webp',
    },
    {
        name: 'Madagascar',
        imageUrl: 'flags/madagascar.webp',
    },
    {
        name: 'Malawi',
        imageUrl: 'flags/malawi.webp',
    },
    {
        name: 'Malaysia',
        imageUrl: 'flags/malaysia.webp',
    },
    {
        name: 'Maldives',
        imageUrl: 'flags/maldives.webp',
    },
    {
        name: 'Mali',
        imageUrl: 'flags/mali.webp',
    },
    {
        name: 'Malta',
        imageUrl: 'flags/malta.webp',
    },
    {
        name: 'Marshall Islands',
        imageUrl: 'flags/marshall-islands.webp',
    },
    {
        name: 'Martinique',
        imageUrl: 'flags/martinique.webp',
    },
    {
        name: 'Mauritania',
        imageUrl: 'flags/mauritania.webp',
    },
    {
        name: 'Mauritius',
        imageUrl: 'flags/mauritius.webp',
    },
    {
        name: 'Mayotte',
        imageUrl: 'flags/mayotte.webp',
    },
    {
        name: 'Mexico',
        imageUrl: 'flags/mexico.webp',
    },
    {
        name: 'Micronesia',
        imageUrl: 'flags/micronesia.webp',
    },
    {
        name: 'Moldova',
        imageUrl: 'flags/moldova.webp',
    },
    {
        name: 'Monaco',
        imageUrl: 'flags/monaco.webp',
    },
    {
        name: 'Mongolia',
        imageUrl: 'flags/mongolia.webp',
    },
    {
        name: 'Montenegro',
        imageUrl: 'flags/montenegro.webp',
    },
    {
        name: 'Montserrat',
        imageUrl: 'flags/montserrat.webp',
    },
    {
        name: 'Morocco',
        imageUrl: 'flags/morocco.webp',
    },
    {
        name: 'Mozambique',
        imageUrl: 'flags/mozambique.webp',
    },
    {
        name: 'Myanmar',
        imageUrl: 'flags/myanmar.webp',
    },
    {
        name: 'Namibia',
        imageUrl: 'flags/namibia.webp',
    },
    {
        name: 'Nauru',
        imageUrl: 'flags/nauru.webp',
    },
    {
        name: 'Nepal',
        imageUrl: 'flags/nepal.webp',
    },
    {
        name: 'Netherlands',
        imageUrl: 'flags/netherlands.webp',
    },
    {
        name: 'New Caledonia',
        imageUrl: 'flags/new-caledonia.webp',
    },
    {
        name: 'New Zealand',
        imageUrl: 'flags/new-zealand.webp',
    },
    {
        name: 'Nicaragua',
        imageUrl: 'flags/nicaragua.webp',
    },
    {
        name: 'Niger',
        imageUrl: 'flags/niger.webp',
    },
    {
        name: 'Nigeria',
        imageUrl: 'flags/nigeria.webp',
    },
    {
        name: 'Niue',
        imageUrl: 'flags/niue.webp',
    },
    {
        name: 'Norfolk Island',
        imageUrl: 'flags/norfolk-island.webp',
    },
    {
        name: 'North Korea',
        imageUrl: 'flags/north-korea.webp',
    },
    {
        name: 'North Macedonia',
        imageUrl: 'flags/north-macedonia.webp',
    },
    {
        name: 'Northern Mariana Islands',
        imageUrl: 'flags/northern-mariana-islands.webp',
    },
    {
        name: 'Norway',
        imageUrl: 'flags/norway.webp',
    },
    {
        name: 'Oman',
        imageUrl: 'flags/oman.webp',
    },
    {
        name: 'Pakistan',
        imageUrl: 'flags/pakistan.webp',
    },
    {
        name: 'Palau',
        imageUrl: 'flags/palau.webp',
    },
    {
        name: 'Palestine',
        imageUrl: 'flags/palestine.webp',
    },
    {
        name: 'Panama',
        imageUrl: 'flags/panama.webp',
    },
    {
        name: 'Papua New Guinea',
        imageUrl: 'flags/papua-new-guinea.webp',
    },
    {
        name: 'Paraguay',
        imageUrl: 'flags/paraguay.webp',
    },
    {
        name: 'Peru',
        imageUrl: 'flags/peru.webp',
    },
    {
        name: 'Philippines',
        imageUrl: 'flags/philippines.webp',
    },
    {
        name: 'Pitcairn Islands',
        imageUrl: 'flags/pitcairn-islands.webp',
    },
    {
        name: 'Poland',
        imageUrl: 'flags/poland.webp',
    },
    {
        name: 'Portugal',
        imageUrl: 'flags/portugal.webp',
    },
    {
        name: 'Puerto Rico',
        imageUrl: 'flags/puerto-rico.webp',
    },
    {
        name: 'Qatar',
        imageUrl: 'flags/qatar.webp',
    },
    {
        name: 'Republic of the Congo',
        imageUrl: 'flags/republic-of-the-congo.webp',
    },
    {
        name: 'Réunion',
        imageUrl: 'flags/reunion.webp',
    },
    {
        name: 'Romania',
        imageUrl: 'flags/romania.webp',
    },
    {
        name: 'Russia',
        imageUrl: 'flags/russia.webp',
    },
    {
        name: 'Rwanda',
        imageUrl: 'flags/rwanda.webp',
    },
    {
        name: 'Saint Barthélemy',
        imageUrl: 'flags/saint-barthelemy.webp',
    },
    {
        name: 'Saint Kitts and Nevis',
        imageUrl: 'flags/saint-kitts-and-nevis.webp',
    },
    {
        name: 'Saint Lucia',
        imageUrl: 'flags/saint-lucia.webp',
    },
    {
        name: 'Saint Martin',
        imageUrl: 'flags/saint-martin.webp',
    },
    {
        name: 'Saint Pierre and Miquelon',
        imageUrl: 'flags/saint-pierre-and-miquelon.webp',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        imageUrl: 'flags/saint-vincent-and-the-grenadines.webp',
    },
    {
        name: 'Samoa',
        imageUrl: 'flags/samoa.webp',
    },
    {
        name: 'San Marino',
        imageUrl: 'flags/san-marino.webp',
    },
    {
        name: 'São Tomé and Príncipe',
        imageUrl: 'flags/sao-tome-and-principe.webp',
    },
    {
        name: 'Saudi Arabia',
        imageUrl: 'flags/saudi-arabia.webp',
    },
    {
        name: 'Senegal',
        imageUrl: 'flags/senegal.webp',
    },
    {
        name: 'Serbia',
        imageUrl: 'flags/serbia.webp',
    },
    {
        name: 'Seychelles',
        imageUrl: 'flags/seychelles.webp',
    },
    {
        name: 'Sierra Leone',
        imageUrl: 'flags/sierra-leone.webp',
    },
    {
        name: 'Singapore',
        imageUrl: 'flags/singapore.webp',
    },
    {
        name: 'Sint Maarten',
        imageUrl: 'flags/sint-maarten.webp',
    },
    {
        name: 'Slovakia',
        imageUrl: 'flags/slovakia.webp',
    },
    {
        name: 'Slovenia',
        imageUrl: 'flags/slovenia.webp',
    },
    {
        name: 'Solomon Islands',
        imageUrl: 'flags/solomon-islands.webp',
    },
    {
        name: 'Somalia',
        imageUrl: 'flags/somalia.webp',
    },
    {
        name: 'South Africa',
        imageUrl: 'flags/south-africa.webp',
    },
    {
        name: 'South Korea',
        imageUrl: 'flags/south-korea.webp',
    },
    {
        name: 'South Sudan',
        imageUrl: 'flags/south-sudan.webp',
    },
    {
        name: 'Spain',
        imageUrl: 'flags/spain.webp',
    },
    {
        name: 'Sri Lanka',
        imageUrl: 'flags/sri-lanka.webp',
    },
    {
        name: 'Sudan',
        imageUrl: 'flags/sudan.webp',
    },
    {
        name: 'Suriname',
        imageUrl: 'flags/suriname.webp',
    },
    {
        name: 'Sweden',
        imageUrl: 'flags/sweden.webp',
    },
    {
        name: 'Switzerland',
        imageUrl: 'flags/switzerland.webp',
    },
    {
        name: 'Syria',
        imageUrl: 'flags/syria.webp',
    },
    {
        name: 'Taiwan',
        imageUrl: 'flags/taiwan.webp',
    },
    {
        name: 'Tajikistan',
        imageUrl: 'flags/tajikistan.webp',
    },
    {
        name: 'Tanzania',
        imageUrl: 'flags/tanzania.webp',
    },
    {
        name: 'Thailand',
        imageUrl: 'flags/thailand.webp',
    },
    {
        name: 'Timor-Leste',
        imageUrl: 'flags/timor-leste.webp',
    },
    {
        name: 'Togo',
        imageUrl: 'flags/togo.webp',
    },
    {
        name: 'Tokelau',
        imageUrl: 'flags/tokelau.webp',
    },
    {
        name: 'Tonga',
        imageUrl: 'flags/tonga.webp',
    },
    {
        name: 'Trinidad and Tobago',
        imageUrl: 'flags/trinidad-and-tobago.webp',
    },
    {
        name: 'Tunisia',
        imageUrl: 'flags/tunisia.webp',
    },
    {
        name: 'Turkey',
        imageUrl: 'flags/turkey.webp',
    },
    {
        name: 'Turkmenistan',
        imageUrl: 'flags/turkmenistan.webp',
    },
    {
        name: 'Turks and Caicos Islands',
        imageUrl: 'flags/turks-and-caicos-islands.webp',
    },
    {
        name: 'Tuvalu',
        imageUrl: 'flags/tuvalu.webp',
    },
    {
        name: 'Uganda',
        imageUrl: 'flags/uganda.webp',
    },
    {
        name: 'Ukraine',
        imageUrl: 'flags/ukraine.webp',
    },
    {
        name: 'United Arab Emirates',
        imageUrl: 'flags/united-arab-emirates.webp',
    },
    {
        name: 'United Kingdom',
        imageUrl: 'flags/united-kingdom.webp',
    },
    {
        name: 'United States',
        imageUrl: 'flags/united-states.webp',
    },
    {
        name: 'United States Virgin Islands',
        imageUrl: 'flags/united-states-virgin-islands.webp',
    },
    {
        name: 'Uruguay',
        imageUrl: 'flags/uruguay.webp',
    },
    {
        name: 'Uzbekistan',
        imageUrl: 'flags/uzbekistan.webp',
    },
    {
        name: 'Vanuatu',
        imageUrl: 'flags/vanuatu.webp',
    },
    {
        name: 'Vatican City (Holy See)',
        imageUrl: 'flags/vatican-city-holy-see.webp',
    },
    {
        name: 'Venezuela',
        imageUrl: 'flags/venezuela.webp',
    },
    {
        name: 'Vietnam',
        imageUrl: 'flags/vietnam.webp',
    },
    {
        name: 'Wallis and Futuna',
        imageUrl: 'flags/wallis-and-futuna.webp',
    },
    {
        name: 'Western Sahara',
        imageUrl: 'flags/western-sahara.webp',
    },
    {
        name: 'Yemen',
        imageUrl: 'flags/yemen.webp',
    },
    {
        name: 'Zambia',
        imageUrl: 'flags/zambia.webp',
    },
    {
        name: 'Zimbabwe',
        imageUrl: 'flags/zimbabwe.webp',
    },
]
