// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const footballCharacters: Character[] = [
    {
        name: '1. FC Heidenheim 1846',
        imageUrl: 'football/1-fc-heidenheim-1846.webp',
    },
    {
        name: '1. FC Köln',
        imageUrl: 'football/1-fc-koln.webp',
    },
    {
        name: '1. FC Union Berlin',
        imageUrl: 'football/1-fc-union-berlin.webp',
    },
    {
        name: '1. FSV Mainz 05',
        imageUrl: 'football/1-fsv-mainz-05.webp',
    },
    {
        name: 'AC Milan',
        imageUrl: 'football/ac-milan.webp',
    },
    {
        name: 'AC Pisa 1909',
        imageUrl: 'football/ac-pisa-1909.webp',
    },
    {
        name: 'ACF Fiorentina',
        imageUrl: 'football/acf-fiorentina.webp',
    },
    {
        name: 'AFC Bournemouth',
        imageUrl: 'football/afc-bournemouth.webp',
    },
    {
        name: 'AJ Auxerre',
        imageUrl: 'football/aj-auxerre.webp',
    },
    {
        name: 'Angers SCO',
        imageUrl: 'football/angers-sco.webp',
    },
    {
        name: 'Arsenal FC',
        imageUrl: 'football/arsenal-fc.webp',
    },
    {
        name: 'AS Monaco FC',
        imageUrl: 'football/as-monaco-fc.webp',
    },
    {
        name: 'AS Roma',
        imageUrl: 'football/as-roma.webp',
    },
    {
        name: 'Aston Villa FC',
        imageUrl: 'football/aston-villa-fc.webp',
    },
    {
        name: 'Atalanta BC',
        imageUrl: 'football/atalanta-bc.webp',
    },
    {
        name: 'Athletic Club',
        imageUrl: 'football/athletic-club.webp',
    },
    {
        name: 'Bayer 04 Leverkusen',
        imageUrl: 'football/bayer-04-leverkusen.webp',
    },
    {
        name: 'Bologna FC 1909',
        imageUrl: 'football/bologna-fc-1909.webp',
    },
    {
        name: 'Borussia Dortmund',
        imageUrl: 'football/borussia-dortmund.webp',
    },
    {
        name: 'Borussia Mönchengladbach',
        imageUrl: 'football/borussia-monchengladbach.webp',
    },
    {
        name: 'Brentford FC',
        imageUrl: 'football/brentford-fc.webp',
    },
    {
        name: 'Brighton & Hove Albion FC',
        imageUrl: 'football/brighton-hove-albion-fc.webp',
    },
    {
        name: 'Burnley FC',
        imageUrl: 'football/burnley-fc.webp',
    },
    {
        name: 'CA Osasuna',
        imageUrl: 'football/ca-osasuna.webp',
    },
    {
        name: 'Cagliari Calcio',
        imageUrl: 'football/cagliari-calcio.webp',
    },
    {
        name: 'Chelsea FC',
        imageUrl: 'football/chelsea-fc.webp',
    },
    {
        name: 'Club Atlético de Madrid',
        imageUrl: 'football/club-atletico-de-madrid.webp',
    },
    {
        name: 'Como 1907',
        imageUrl: 'football/como-1907.webp',
    },
    {
        name: 'Crystal Palace FC',
        imageUrl: 'football/crystal-palace-fc.webp',
    },
    {
        name: 'Deportivo Alavés',
        imageUrl: 'football/deportivo-alaves.webp',
    },
    {
        name: 'Eintracht Frankfurt',
        imageUrl: 'football/eintracht-frankfurt.webp',
    },
    {
        name: 'Elche CF',
        imageUrl: 'football/elche-cf.webp',
    },
    {
        name: 'Everton FC',
        imageUrl: 'football/everton-fc.webp',
    },
    {
        name: 'FC Augsburg',
        imageUrl: 'football/fc-augsburg.webp',
    },
    {
        name: 'FC Barcelona',
        imageUrl: 'football/fc-barcelona.webp',
    },
    {
        name: 'FC Bayern München',
        imageUrl: 'football/fc-bayern-munchen.webp',
    },
    {
        name: 'FC Internazionale Milano',
        imageUrl: 'football/fc-internazionale-milano.webp',
    },
    {
        name: 'FC Lorient',
        imageUrl: 'football/fc-lorient.webp',
    },
    {
        name: 'FC Metz',
        imageUrl: 'football/fc-metz.webp',
    },
    {
        name: 'FC Nantes',
        imageUrl: 'football/fc-nantes.webp',
    },
    {
        name: 'FC St. Pauli 1910',
        imageUrl: 'football/fc-st-pauli-1910.webp',
    },
    {
        name: 'Fulham FC',
        imageUrl: 'football/fulham-fc.webp',
    },
    {
        name: 'Genoa CFC',
        imageUrl: 'football/genoa-cfc.webp',
    },
    {
        name: 'Getafe CF',
        imageUrl: 'football/getafe-cf.webp',
    },
    {
        name: 'Girona FC',
        imageUrl: 'football/girona-fc.webp',
    },
    {
        name: 'Hamburger SV',
        imageUrl: 'football/hamburger-sv.webp',
    },
    {
        name: 'Hellas Verona FC',
        imageUrl: 'football/hellas-verona-fc.webp',
    },
    {
        name: 'Juventus FC',
        imageUrl: 'football/juventus-fc.webp',
    },
    {
        name: 'Le Havre AC',
        imageUrl: 'football/le-havre-ac.webp',
    },
    {
        name: 'Leeds United FC',
        imageUrl: 'football/leeds-united-fc.webp',
    },
    {
        name: 'Levante UD',
        imageUrl: 'football/levante-ud.webp',
    },
    {
        name: 'Lille OSC',
        imageUrl: 'football/lille-osc.webp',
    },
    {
        name: 'Liverpool FC',
        imageUrl: 'football/liverpool-fc.webp',
    },
    {
        name: 'Manchester City FC',
        imageUrl: 'football/manchester-city-fc.webp',
    },
    {
        name: 'Manchester United FC',
        imageUrl: 'football/manchester-united-fc.webp',
    },
    {
        name: 'Newcastle United FC',
        imageUrl: 'football/newcastle-united-fc.webp',
    },
    {
        name: 'Nottingham Forest FC',
        imageUrl: 'football/nottingham-forest-fc.webp',
    },
    {
        name: 'OGC Nice',
        imageUrl: 'football/ogc-nice.webp',
    },
    {
        name: 'Olympique de Marseille',
        imageUrl: 'football/olympique-de-marseille.webp',
    },
    {
        name: 'Olympique Lyonnais',
        imageUrl: 'football/olympique-lyonnais.webp',
    },
    {
        name: 'Paris FC',
        imageUrl: 'football/paris-fc.webp',
    },
    {
        name: 'Paris Saint-Germain FC',
        imageUrl: 'football/paris-saint-germain-fc.webp',
    },
    {
        name: 'Parma Calcio 1913',
        imageUrl: 'football/parma-calcio-1913.webp',
    },
    {
        name: 'Racing Club de Lens',
        imageUrl: 'football/racing-club-de-lens.webp',
    },
    {
        name: 'Rayo Vallecano de Madrid',
        imageUrl: 'football/rayo-vallecano-de-madrid.webp',
    },
    {
        name: 'RB Leipzig',
        imageUrl: 'football/rb-leipzig.webp',
    },
    {
        name: 'RC Celta de Vigo',
        imageUrl: 'football/rc-celta-de-vigo.webp',
    },
    {
        name: 'RC Strasbourg Alsace',
        imageUrl: 'football/rc-strasbourg-alsace.webp',
    },
    {
        name: 'RCD Espanyol de Barcelona',
        imageUrl: 'football/rcd-espanyol-de-barcelona.webp',
    },
    {
        name: 'RCD Mallorca',
        imageUrl: 'football/rcd-mallorca.webp',
    },
    {
        name: 'Real Betis Balompié',
        imageUrl: 'football/real-betis-balompie.webp',
    },
    {
        name: 'Real Madrid CF',
        imageUrl: 'football/real-madrid-cf.webp',
    },
    {
        name: 'Real Oviedo',
        imageUrl: 'football/real-oviedo.webp',
    },
    {
        name: 'Real Sociedad de Fútbol',
        imageUrl: 'football/real-sociedad-de-futbol.webp',
    },
    {
        name: 'SC Freiburg',
        imageUrl: 'football/sc-freiburg.webp',
    },
    {
        name: 'Sevilla FC',
        imageUrl: 'football/sevilla-fc.webp',
    },
    {
        name: 'SS Lazio',
        imageUrl: 'football/ss-lazio.webp',
    },
    {
        name: 'SSC Napoli',
        imageUrl: 'football/ssc-napoli.webp',
    },
    {
        name: 'Stade Brestois 29',
        imageUrl: 'football/stade-brestois-29.webp',
    },
    {
        name: 'Stade Rennais FC 1901',
        imageUrl: 'football/stade-rennais-fc-1901.webp',
    },
    {
        name: 'Sunderland AFC',
        imageUrl: 'football/sunderland-afc.webp',
    },
    {
        name: 'SV Werder Bremen',
        imageUrl: 'football/sv-werder-bremen.webp',
    },
    {
        name: 'Torino FC',
        imageUrl: 'football/torino-fc.webp',
    },
    {
        name: 'Tottenham Hotspur FC',
        imageUrl: 'football/tottenham-hotspur-fc.webp',
    },
    {
        name: 'Toulouse FC',
        imageUrl: 'football/toulouse-fc.webp',
    },
    {
        name: 'TSG 1899 Hoffenheim',
        imageUrl: 'football/tsg-1899-hoffenheim.webp',
    },
    {
        name: 'Udinese Calcio',
        imageUrl: 'football/udinese-calcio.webp',
    },
    {
        name: 'US Cremonese',
        imageUrl: 'football/us-cremonese.webp',
    },
    {
        name: 'US Lecce',
        imageUrl: 'football/us-lecce.webp',
    },
    {
        name: 'US Sassuolo Calcio',
        imageUrl: 'football/us-sassuolo-calcio.webp',
    },
    {
        name: 'Valencia CF',
        imageUrl: 'football/valencia-cf.webp',
    },
    {
        name: 'VfB Stuttgart',
        imageUrl: 'football/vfb-stuttgart.webp',
    },
    {
        name: 'VfL Wolfsburg',
        imageUrl: 'football/vfl-wolfsburg.webp',
    },
    {
        name: 'Villarreal CF',
        imageUrl: 'football/villarreal-cf.webp',
    },
    {
        name: 'West Ham United FC',
        imageUrl: 'football/west-ham-united-fc.webp',
    },
    {
        name: 'Wolverhampton Wanderers FC',
        imageUrl: 'football/wolverhampton-wanderers-fc.webp',
    },
]
