// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const footballCharacters: Character[] = [
    {
        name: '1. FC Heidenheim 1846',
        imageUrl: 'https://crests.football-data.org/44.png',
    },
    {
        name: '1. FC Köln',
        imageUrl: 'https://crests.football-data.org/1.png',
    },
    {
        name: '1. FC Union Berlin',
        imageUrl: 'https://crests.football-data.org/28.png',
    },
    {
        name: '1. FSV Mainz 05',
        imageUrl: 'https://crests.football-data.org/15.png',
    },
    {
        name: 'AC Milan',
        imageUrl: 'https://crests.football-data.org/98.png',
    },
    {
        name: 'AC Pisa 1909',
        imageUrl: 'https://crests.football-data.org/487.png',
    },
    {
        name: 'ACF Fiorentina',
        imageUrl: 'https://crests.football-data.org/99.png',
    },
    {
        name: 'AFC Ajax',
        imageUrl: 'https://crests.football-data.org/678.png',
    },
    {
        name: 'AFC Bournemouth',
        imageUrl: 'https://crests.football-data.org/bournemouth.png',
    },
    {
        name: 'AJ Auxerre',
        imageUrl: 'https://crests.football-data.org/519.png',
    },
    {
        name: 'Angers SCO',
        imageUrl: 'https://crests.football-data.org/532.png',
    },
    {
        name: 'Arsenal FC',
        imageUrl: 'https://crests.football-data.org/57.png',
    },
    {
        name: 'AS Monaco FC',
        imageUrl: 'https://crests.football-data.org/548.png',
    },
    {
        name: 'AS Roma',
        imageUrl: 'https://crests.football-data.org/100.png',
    },
    {
        name: 'Aston Villa FC',
        imageUrl: 'https://crests.football-data.org/58.png',
    },
    {
        name: 'Atalanta BC',
        imageUrl: 'https://crests.football-data.org/102.png',
    },
    {
        name: 'Athletic Club',
        imageUrl: 'https://crests.football-data.org/77.png',
    },
    {
        name: 'Bayer 04 Leverkusen',
        imageUrl: 'https://crests.football-data.org/3.png',
    },
    {
        name: 'Bologna FC 1909',
        imageUrl: 'https://crests.football-data.org/103.png',
    },
    {
        name: 'Borussia Dortmund',
        imageUrl: 'https://crests.football-data.org/4.png',
    },
    {
        name: 'Borussia Mönchengladbach',
        imageUrl: 'https://crests.football-data.org/18.png',
    },
    {
        name: 'Brentford FC',
        imageUrl: 'https://crests.football-data.org/402.png',
    },
    {
        name: 'Brighton & Hove Albion FC',
        imageUrl: 'https://crests.football-data.org/397.png',
    },
    {
        name: 'Burnley FC',
        imageUrl: 'https://crests.football-data.org/328.png',
    },
    {
        name: 'CA Osasuna',
        imageUrl: 'https://crests.football-data.org/79.png',
    },
    {
        name: 'Cagliari Calcio',
        imageUrl: 'https://crests.football-data.org/104.png',
    },
    {
        name: 'Chelsea FC',
        imageUrl: 'https://crests.football-data.org/61.png',
    },
    {
        name: 'Club Atlético de Madrid',
        imageUrl: 'https://crests.football-data.org/78.png',
    },
    {
        name: 'Club Brugge KV',
        imageUrl: 'https://crests.football-data.org/851.png',
    },
    {
        name: 'Como 1907',
        imageUrl: 'https://crests.football-data.org/7397.png',
    },
    {
        name: 'Crystal Palace FC',
        imageUrl: 'https://crests.football-data.org/354.png',
    },
    {
        name: 'Deportivo Alavés',
        imageUrl: 'https://crests.football-data.org/263.png',
    },
    {
        name: 'Eintracht Frankfurt',
        imageUrl: 'https://crests.football-data.org/19.png',
    },
    {
        name: 'Elche CF',
        imageUrl: 'https://crests.football-data.org/285.png',
    },
    {
        name: 'Everton FC',
        imageUrl: 'https://crests.football-data.org/62.png',
    },
    {
        name: 'FC Augsburg',
        imageUrl: 'https://crests.football-data.org/16.png',
    },
    {
        name: 'FC Barcelona',
        imageUrl: 'https://crests.football-data.org/81.png',
    },
    {
        name: 'FC Bayern München',
        imageUrl: 'https://crests.football-data.org/5.png',
    },
    {
        name: 'FC Internazionale Milano',
        imageUrl: 'https://crests.football-data.org/108.png',
    },
    {
        name: 'FC København',
        imageUrl: 'https://crests.football-data.org/1876.png',
    },
    {
        name: 'FC Lorient',
        imageUrl: 'https://crests.football-data.org/525.png',
    },
    {
        name: 'FC Metz',
        imageUrl: 'https://crests.football-data.org/545.png',
    },
    {
        name: 'FC Nantes',
        imageUrl: 'https://crests.football-data.org/543.png',
    },
    {
        name: 'FC St. Pauli 1910',
        imageUrl: 'https://crests.football-data.org/20.png',
    },
    {
        name: 'FK Bodø/Glimt',
        imageUrl: 'https://crests.football-data.org/5721.png',
    },
    {
        name: 'FK Kairat',
        imageUrl: 'https://crests.football-data.org/10601.png',
    },
    {
        name: 'Fulham FC',
        imageUrl: 'https://crests.football-data.org/63.png',
    },
    {
        name: 'Galatasaray SK',
        imageUrl: 'https://crests.football-data.org/610.png',
    },
    {
        name: 'Genoa CFC',
        imageUrl: 'https://crests.football-data.org/107.png',
    },
    {
        name: 'Getafe CF',
        imageUrl: 'https://crests.football-data.org/82.png',
    },
    {
        name: 'Girona FC',
        imageUrl: 'https://crests.football-data.org/298.png',
    },
    {
        name: 'Hamburger SV',
        imageUrl: 'https://crests.football-data.org/7.png',
    },
    {
        name: 'Hellas Verona FC',
        imageUrl: 'https://crests.football-data.org/450.png',
    },
    {
        name: 'Juventus FC',
        imageUrl: 'https://crests.football-data.org/109.png',
    },
    {
        name: 'Le Havre AC',
        imageUrl: 'https://crests.football-data.org/533.png',
    },
    {
        name: 'Leeds United FC',
        imageUrl: 'https://crests.football-data.org/341.png',
    },
    {
        name: 'Levante UD',
        imageUrl: 'https://crests.football-data.org/88.png',
    },
    {
        name: 'Lille OSC',
        imageUrl: 'https://crests.football-data.org/521.png',
    },
    {
        name: 'Liverpool FC',
        imageUrl: 'https://crests.football-data.org/64.png',
    },
    {
        name: 'Manchester City FC',
        imageUrl: 'https://crests.football-data.org/65.png',
    },
    {
        name: 'Manchester United FC',
        imageUrl: 'https://crests.football-data.org/66.png',
    },
    {
        name: 'Newcastle United FC',
        imageUrl: 'https://crests.football-data.org/67.png',
    },
    {
        name: 'Nottingham Forest FC',
        imageUrl: 'https://crests.football-data.org/351.png',
    },
    {
        name: 'OGC Nice',
        imageUrl: 'https://crests.football-data.org/522.png',
    },
    {
        name: 'Olympique de Marseille',
        imageUrl: 'https://crests.football-data.org/516.png',
    },
    {
        name: 'Olympique Lyonnais',
        imageUrl: 'https://crests.football-data.org/523.png',
    },
    {
        name: 'PAE Olympiakos SFP',
        imageUrl: 'https://crests.football-data.org/654.png',
    },
    {
        name: 'Paphos FC',
        imageUrl: 'https://crests.football-data.org/11034.png',
    },
    {
        name: 'Paris FC',
        imageUrl: 'https://crests.football-data.org/1045.png',
    },
    {
        name: 'Paris Saint-Germain FC',
        imageUrl: 'https://crests.football-data.org/524.png',
    },
    {
        name: 'Parma Calcio 1913',
        imageUrl: 'https://crests.football-data.org/112.png',
    },
    {
        name: 'PSV',
        imageUrl: 'https://crests.football-data.org/674.png',
    },
    {
        name: 'Qarabağ Ağdam FK',
        imageUrl: 'https://crests.football-data.org/611.png',
    },
    {
        name: 'Racing Club de Lens',
        imageUrl: 'https://crests.football-data.org/546.png',
    },
    {
        name: 'Rayo Vallecano de Madrid',
        imageUrl: 'https://crests.football-data.org/87.png',
    },
    {
        name: 'RB Leipzig',
        imageUrl: 'https://crests.football-data.org/721.png',
    },
    {
        name: 'RC Celta de Vigo',
        imageUrl: 'https://crests.football-data.org/558.png',
    },
    {
        name: 'RC Strasbourg Alsace',
        imageUrl: 'https://crests.football-data.org/576.png',
    },
    {
        name: 'RCD Espanyol de Barcelona',
        imageUrl: 'https://crests.football-data.org/80.png',
    },
    {
        name: 'RCD Mallorca',
        imageUrl: 'https://crests.football-data.org/89.png',
    },
    {
        name: 'Real Betis Balompié',
        imageUrl: 'https://crests.football-data.org/90.png',
    },
    {
        name: 'Real Madrid CF',
        imageUrl: 'https://crests.football-data.org/86.png',
    },
    {
        name: 'Real Oviedo',
        imageUrl: 'https://crests.football-data.org/1048.png',
    },
    {
        name: 'Real Sociedad de Fútbol',
        imageUrl: 'https://crests.football-data.org/92.png',
    },
    {
        name: 'Royale Union Saint-Gilloise',
        imageUrl: 'https://crests.football-data.org/3929.png',
    },
    {
        name: 'SC Freiburg',
        imageUrl: 'https://crests.football-data.org/17.png',
    },
    {
        name: 'Sevilla FC',
        imageUrl: 'https://crests.football-data.org/559.png',
    },
    {
        name: 'SK Slavia Praha',
        imageUrl: 'https://crests.football-data.org/930.png',
    },
    {
        name: 'Sport Lisboa e Benfica',
        imageUrl: 'https://crests.football-data.org/1903.png',
    },
    {
        name: 'Sporting Clube de Portugal',
        imageUrl: 'https://crests.football-data.org/498.png',
    },
    {
        name: 'SS Lazio',
        imageUrl: 'https://crests.football-data.org/110.png',
    },
    {
        name: 'SSC Napoli',
        imageUrl: 'https://crests.football-data.org/113.png',
    },
    {
        name: 'Stade Brestois 29',
        imageUrl: 'https://crests.football-data.org/512.png',
    },
    {
        name: 'Stade Rennais FC 1901',
        imageUrl: 'https://crests.football-data.org/529.png',
    },
    {
        name: 'Sunderland AFC',
        imageUrl: 'https://crests.football-data.org/71.png',
    },
    {
        name: 'SV Werder Bremen',
        imageUrl: 'https://crests.football-data.org/12.png',
    },
    {
        name: 'Torino FC',
        imageUrl: 'https://crests.football-data.org/586.png',
    },
    {
        name: 'Tottenham Hotspur FC',
        imageUrl: 'https://crests.football-data.org/73.png',
    },
    {
        name: 'Toulouse FC',
        imageUrl: 'https://crests.football-data.org/511.png',
    },
    {
        name: 'TSG 1899 Hoffenheim',
        imageUrl: 'https://crests.football-data.org/2.png',
    },
    {
        name: 'Udinese Calcio',
        imageUrl: 'https://crests.football-data.org/115.png',
    },
    {
        name: 'US Cremonese',
        imageUrl: 'https://crests.football-data.org/457.png',
    },
    {
        name: 'US Lecce',
        imageUrl: 'https://crests.football-data.org/5890.png',
    },
    {
        name: 'US Sassuolo Calcio',
        imageUrl: 'https://crests.football-data.org/471.png',
    },
    {
        name: 'Valencia CF',
        imageUrl: 'https://crests.football-data.org/95.png',
    },
    {
        name: 'VfB Stuttgart',
        imageUrl: 'https://crests.football-data.org/10.png',
    },
    {
        name: 'VfL Wolfsburg',
        imageUrl: 'https://crests.football-data.org/11.png',
    },
    {
        name: 'Villarreal CF',
        imageUrl: 'https://crests.football-data.org/94.png',
    },
    {
        name: 'West Ham United FC',
        imageUrl: 'https://crests.football-data.org/563.png',
    },
    {
        name: 'Wolverhampton Wanderers FC',
        imageUrl: 'https://crests.football-data.org/76.png',
    },
]
