// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const fortniteCharacters: Character[] = [
    {
        name: 'Alli',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_a_044_athena_commando_f_neoncatfashion_64jw3/featured.png',
    },
    {
        name: 'Arachne',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_249_athena_commando_f_blackwidow/featured.png',
    },
    {
        name: 'Ark',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_300_athena_commando_f_angel/featured.png',
    },
    {
        name: 'Ascendant Midas',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/character_piteouskicks/featured.png',
    },
    {
        name: 'Backlash',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_861_athena_commando_f_elastic_b/featured.png',
    },
    {
        name: 'Battle Hound',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_100_athena_commando_m_cuchulainn/featured.png',
    },
    {
        name: 'Blastoff',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_857_athena_commando_m_elastic_c/featured.png',
    },
    {
        name: 'Chomp Sr.',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_168_athena_commando_m_shark/featured.png',
    },
    {
        name: 'Crackshot',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_050_athena_commando_m_holidaynutcracker/featured.png',
    },
    {
        name: 'Criterion',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_152_athena_commando_f_carbideorange/featured.png',
    },
    {
        name: 'Cuddle Team Leader',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_069_athena_commando_f_pinkbear/featured.png',
    },
    {
        name: 'Cyclo',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_750_athena_commando_m_hurricane/featured.png',
    },
    {
        name: 'Dark Vanguard',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_105_athena_commando_f_spaceblack/featured.png',
    },
    {
        name: 'Dark Vertex',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_371_athena_commando_m_speedymidnight/featured.png',
    },
    {
        name: 'Deadeye',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_600_athena_commando_m_skeletonhunter/featured.png',
    },
    {
        name: 'Deadfire',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_250_athena_commando_m_evilcowboy/featured.png',
    },
    {
        name: 'DJ Bop',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_308_athena_commando_f_fortnitedj/featured.png',
    },
    {
        name: 'Dynamo Dancer',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_860_athena_commando_f_elastic/featured.png',
    },
    {
        name: 'Enforcer',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_200_athena_commando_m_darkpaintballer/featured.png',
    },
    {
        name: 'Eon',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_174_athena_commando_f_carbidewhite/featured.png',
    },
    {
        name: 'Fate',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_143_athena_commando_f_darkninja/featured.png',
    },
    {
        name: 'Firebrand',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_862_athena_commando_f_elastic_c/featured.png',
    },
    {
        name: 'Flytrap',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_132_athena_commando_m_venus/featured.png',
    },
    {
        name: 'Galaxia',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_935_athena_commando_f_eternity/featured.png',
    },
    {
        name: 'Galaxy Grappler',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_a_174_athena_commando_f_celestialglow/featured.png',
    },
    {
        name: 'Galaxy Scout',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_337_athena_commando_f_celestial/featured.png',
    },
    {
        name: 'Glimmer',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_298_athena_commando_f_icemaiden/featured.png',
    },
    {
        name: 'Glow',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_479_athena_commando_f_davinci/featured.png',
    },
    {
        name: 'Hime',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_199_athena_commando_f_bluesamurai/featured.png',
    },
    {
        name: 'Hunter',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_855_athena_commando_m_elastic/featured.png',
    },
    {
        name: 'Hypersonic',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_856_athena_commando_m_elastic_b/featured.png',
    },
    {
        name: 'Inferno',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_370_athena_commando_m_evilsuit/featured.png',
    },
    {
        name: 'John Wick',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_416_athena_commando_m_assassinsuit/featured.png',
    },
    {
        name: 'Joltara',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_864_athena_commando_f_elastic_e/featured.png',
    },
    {
        name: 'Krampus',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_314_athena_commando_m_krampus/featured.png',
    },
    {
        name: 'Leviathan',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_108_athena_commando_m_fishhead/featured.png',
    },
    {
        name: 'Love Ranger',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_070_athena_commando_m_cupid/featured.png',
    },
    {
        name: 'Magnus',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_164_athena_commando_m_viking/featured.png',
    },
    {
        name: 'Malice',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_369_athena_commando_f_devilrock/featured.png',
    },
    {
        name: 'Mecha Cuddle Master',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_a_105_athena_commando_f_spacecuddles_5teva/featured.png',
    },
    {
        name: 'Moisty Merman',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_130_athena_commando_m_merman/featured.png',
    },
    {
        name: 'Musha',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_198_athena_commando_m_bluesamurai/featured.png',
    },
    {
        name: 'Oblivion',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_153_athena_commando_f_carbideblack/featured.png',
    },
    {
        name: 'Omen',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_141_athena_commando_m_darkeagle/featured.png',
    },
    {
        name: 'Oppressor',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_508_athena_commando_m_syko/featured.png',
    },
    {
        name: 'Oro',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_675_athena_commando_m_thegoldenskeleton/featured.png',
    },
    {
        name: 'P.A.N.D.A Team Leader',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_187_athena_commando_f_fuzzybearpanda/featured.png',
    },
    {
        name: 'Piccolo',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/character_arcticicetalus/featured.png',
    },
    {
        name: 'Polarity',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_863_athena_commando_f_elastic_d/featured.png',
    },
    {
        name: 'Power Chord',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_097_athena_commando_f_rockerpunk/featured.png',
    },
    {
        name: 'Raptor',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_031_athena_commando_m_retro/featured.png',
    },
    {
        name: 'Ravage',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_194_athena_commando_f_ravenquill/featured.png',
    },
    {
        name: 'Raven',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_102_athena_commando_m_raven/featured.png',
    },
    {
        name: 'Red Knight',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_034_athena_commando_f_medieval/featured.png',
    },
    {
        name: 'Rex',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_093_athena_commando_m_dinosaur/featured.png',
    },
    {
        name: 'Ruin',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_378_athena_commando_m_furnaceface/featured.png',
    },
    {
        name: 'Shogun',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_257_athena_commando_m_samuraiultra/featured.png',
    },
    {
        name: 'Singularity',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_469_athena_commando_f_battlesuit/featured.png',
    },
    {
        name: 'Sky Stalker',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_142_athena_commando_m_wwiipilot/featured.png',
    },
    {
        name: 'Son Gohan',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/character_arcticiceblue/featured.png',
    },
    {
        name: 'Son Goku',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_a_462_athena_commando_m_stamina/featured.png',
    },
    {
        name: 'Sorana',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_615_athena_commando_f_bane/featured.png',
    },
    {
        name: 'Spider Knight',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_248_athena_commando_m_blackwidow/featured.png',
    },
    {
        name: 'Supersonic',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_385_athena_commando_m_pilotskull/featured.png',
    },
    {
        name: 'Tempest',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_430_athena_commando_m_stormsoldier/featured.png',
    },
    {
        name: 'The Ice Queen',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_330_athena_commando_f_icequeen/featured.png',
    },
    {
        name: 'The Mighty Volt',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_859_athena_commando_m_elastic_e/featured.png',
    },
    {
        name: 'The Prisoner',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_332_athena_commando_m_prisoner/featured.png',
    },
    {
        name: 'The Scientist',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_540_athena_commando_m_meteormanremix/featured.png',
    },
    {
        name: 'Tricera Ops',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_107_athena_commando_f_pajamaparty/featured.png',
    },
    {
        name: 'Valkyrie',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_222_athena_commando_f_darkviking/featured.png',
    },
    {
        name: 'Vegeta',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_a_463_athena_commando_m_staminavigor/featured.png',
    },
    {
        name: 'Velocity',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_412_athena_commando_f_raptor/featured.png',
    },
    {
        name: 'Vertex',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_160_athena_commando_m_speedyred/featured.png',
    },
    {
        name: 'Vi',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_a_009_athena_commando_f_foxwarrior_21b9r/featured.png',
    },
    {
        name: 'Wanderlust',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_858_athena_commando_m_elastic_d/featured.png',
    },
    {
        name: 'Wild Card',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_206_athena_commando_m_bling/featured.png',
    },
    {
        name: 'Wukong',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_071_athena_commando_m_wukong/featured.png',
    },
    {
        name: 'Zero',
        imageUrl:
            'https://fortnite-api.com/images/cosmetics/br/cid_573_athena_commando_m_haunt/featured.png',
    },
]
