// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const fullmetalAlchemistCharacters: Character[] = [
    {
        name: 'Alex Louis Armstrong',
        imageUrl: 'fullmetal-alchemist/alex-louis-armstrong.webp',
    },
    {
        name: 'Alphonse Elric',
        imageUrl: 'fullmetal-alchemist/alphonse-elric.webp',
    },
    {
        name: 'Barry the Chopper',
        imageUrl: 'fullmetal-alchemist/barry-the-chopper.webp',
    },
    {
        name: 'Black Hayate',
        imageUrl: 'fullmetal-alchemist/black-hayate.webp',
    },
    {
        name: 'Den Rockbell',
        imageUrl: 'fullmetal-alchemist/den-rockbell.webp',
    },
    {
        name: 'Edward Elric',
        imageUrl: 'fullmetal-alchemist/edward-elric.webp',
    },
    {
        name: 'Elicia Hughes',
        imageUrl: 'fullmetal-alchemist/elicia-hughes.webp',
    },
    {
        name: 'Envy',
        imageUrl: 'fullmetal-alchemist/envy.webp',
    },
    {
        name: 'Fu',
        imageUrl: 'fullmetal-alchemist/fu.webp',
    },
    {
        name: 'Gluttony',
        imageUrl: 'fullmetal-alchemist/gluttony.webp',
    },
    {
        name: 'Greed',
        imageUrl: 'fullmetal-alchemist/greed.webp',
    },
    {
        name: 'Homunculus',
        imageUrl: 'fullmetal-alchemist/homunculus.webp',
    },
    {
        name: 'Izumi Curtis',
        imageUrl: 'fullmetal-alchemist/izumi-curtis.webp',
    },
    {
        name: 'Jean Havoc',
        imageUrl: 'fullmetal-alchemist/jean-havoc.webp',
    },
    {
        name: 'Kain Fuery',
        imageUrl: 'fullmetal-alchemist/kain-fuery.webp',
    },
    {
        name: 'King Bradley',
        imageUrl: 'fullmetal-alchemist/king-bradley.webp',
    },
    {
        name: 'Lan Fan',
        imageUrl: 'fullmetal-alchemist/lan-fan.webp',
    },
    {
        name: 'Ling Yao',
        imageUrl: 'fullmetal-alchemist/ling-yao.webp',
    },
    {
        name: 'Lust',
        imageUrl: 'fullmetal-alchemist/lust.webp',
    },
    {
        name: 'Maes Hughes',
        imageUrl: 'fullmetal-alchemist/maes-hughes.webp',
    },
    {
        name: 'Maria Ross',
        imageUrl: 'fullmetal-alchemist/maria-ross.webp',
    },
    {
        name: 'Mei Chang',
        imageUrl: 'fullmetal-alchemist/mei-chang.webp',
    },
    {
        name: 'Miles',
        imageUrl: 'fullmetal-alchemist/miles.webp',
    },
    {
        name: 'Nina Tucker',
        imageUrl: 'fullmetal-alchemist/nina-tucker.webp',
    },
    {
        name: 'Olivier Mira Armstrong',
        imageUrl: 'fullmetal-alchemist/olivier-mira-armstrong.webp',
    },
    {
        name: 'Pinako Rockbell',
        imageUrl: 'fullmetal-alchemist/pinako-rockbell.webp',
    },
    {
        name: 'Riza Hawkeye',
        imageUrl: 'fullmetal-alchemist/riza-hawkeye.webp',
    },
    {
        name: 'Roy Mustang',
        imageUrl: 'fullmetal-alchemist/roy-mustang.webp',
    },
    {
        name: 'Scar',
        imageUrl: 'fullmetal-alchemist/scar.webp',
    },
    {
        name: 'Selim Bradley',
        imageUrl: 'fullmetal-alchemist/selim-bradley.webp',
    },
    {
        name: 'Shao May',
        imageUrl: 'fullmetal-alchemist/shao-may.webp',
    },
    {
        name: 'Sheska',
        imageUrl: 'fullmetal-alchemist/sheska.webp',
    },
    {
        name: 'Shou Tucker',
        imageUrl: 'fullmetal-alchemist/shou-tucker.webp',
    },
    {
        name: 'Sig Curtis',
        imageUrl: 'fullmetal-alchemist/sig-curtis.webp',
    },
    {
        name: 'Sloth',
        imageUrl: 'fullmetal-alchemist/sloth.webp',
    },
    {
        name: 'Solf J. Kimblee',
        imageUrl: 'fullmetal-alchemist/solf-j-kimblee.webp',
    },
    {
        name: 'Trisha Elric',
        imageUrl: 'fullmetal-alchemist/trisha-elric.webp',
    },
    {
        name: 'Truth',
        imageUrl: 'fullmetal-alchemist/truth.webp',
    },
    {
        name: 'Van Hohenheim',
        imageUrl: 'fullmetal-alchemist/van-hohenheim.webp',
    },
    {
        name: 'Winry Rockbell',
        imageUrl: 'fullmetal-alchemist/winry-rockbell.webp',
    },
]
