// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const fullmetalAlchemistCharacters: Character[] = [
    {
        name: 'Alex Louis Armstrong',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/71066.jpg?s=c20e0eaade03719e6637e381a63c8154',
    },
    {
        name: 'Alphonse Elric',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/54265.jpg?s=65c1a674adae3d7c5740d5711517285a',
    },
    {
        name: 'Barry the Chopper',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/52723.jpg?s=ae88023ff5b97c95f191e228f6543e3c',
    },
    {
        name: 'Black Hayate',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/81547.jpg?s=fc3b02fa7a612d9197588646c078cbd7',
    },
    {
        name: 'Den Rockbell',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/76638.jpg?s=77b8cab89d5a96433abc273a93aae576',
    },
    {
        name: 'Edward Elric',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/72533.jpg?s=d38cf4e2e5cbb46ddaf2b23345a03eae',
    },
    {
        name: 'Elicia Hughes',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/53527.jpg?s=fc4d6429738c2e4f65cc7b25fae26f32',
    },
    {
        name: 'Envy',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/79027.jpg?s=4bcce514aa7b51d229ffd84a0a4976d5',
    },
    {
        name: 'Fu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/70274.jpg?s=6ff0886f4ca3ad32641d41bd00ce7f29',
    },
    {
        name: 'Gluttony',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/74580.jpg?s=11c714a7cdd5e1f93eb63b797e49f1fd',
    },
    {
        name: 'Greed',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/78721.jpg?s=b19bb6258904972030cb3f41917f8a60',
    },
    {
        name: 'Homunculus',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/80675.jpg?s=d88162ea44efd5b1b9e6e3ac4ef61158',
    },
    {
        name: 'Izumi Curtis',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/85257.jpg?s=5e70b5c47afc7e05e9e5398bc8d2ea50',
    },
    {
        name: 'Jean Havoc',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/76640.jpg?s=5e8ee16c7a24338ca4db42068f9527e2',
    },
    {
        name: 'Kain Fuery',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/70276.jpg?s=24c93f1bf437f46a99a542ff4c355518',
    },
    {
        name: 'King Bradley',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/62053.jpg?s=181ba72d4c6ba5605bbfb63f1812f876',
    },
    {
        name: 'Lan Fan',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/59557.jpg?s=72be2a69e1284b0e0bf092deb460e3f8',
    },
    {
        name: 'Ling Yao',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/62602.jpg?s=c1c34cb6b91640be0fc8a4c4aadc14a1',
    },
    {
        name: 'Lust',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/81112.jpg?s=6d83fc7c4b8426d92bd5ab0779ff263d',
    },
    {
        name: 'Maes Hughes',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/73469.jpg?s=049daccbf5014073c0c8933c5388258a',
    },
    {
        name: 'Maria Ross',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/84105.jpg?s=f8ba5a22c98a98f1e99e45f001646000',
    },
    {
        name: 'Mei Chang',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/80248.jpg?s=0e6976dff1fa9de9242c0842a375c815',
    },
    {
        name: 'Miles',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/72473.jpg?s=fdc69990cef02da2101532ca1d81a055',
    },
    {
        name: 'Nina Tucker',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/35396.jpg?s=bfe784f50bbe9eee1fc38e5cbaf7de53',
    },
    {
        name: 'Olivier Mira Armstrong',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/83953.jpg?s=616c3cbf0f0a02068ac4f9bf7e52c746',
    },
    {
        name: 'Pinako Rockbell',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/81200.jpg?s=9f7679b78d37411e66a48e4f97b11670',
    },
    {
        name: 'Riza Hawkeye',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/451785.jpg?s=11bc1988772e66c4fce2ff3dee08b8da',
    },
    {
        name: 'Roy Mustang',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/510227.jpg?s=a9880198a26475fa0555f4690bab8cd3',
    },
    {
        name: 'Scar',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/31591.jpg?s=0f4cfb335f3a86eede76abc630a3fe9e',
    },
    {
        name: 'Selim Bradley',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/71041.jpg?s=8a07302c357dca92f5aa20b76cba70e7',
    },
    {
        name: 'Shao May',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/58046.jpg?s=73d921330c5a2cf2fb84625bc3f14cd9',
    },
    {
        name: 'Sheska',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/54925.jpg?s=206a610ce7f7b58e35525513ca6e9d8c',
    },
    {
        name: 'Shou Tucker',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/52232.jpg?s=e7266752f9c1853d8977fae6d1270f20',
    },
    {
        name: 'Sig Curtis',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/55433.jpg?s=c3a9b7b30287a53710c47c99763e9b59',
    },
    {
        name: 'Sloth',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/72474.jpg?s=afa4b186ea4db5df1948fbf9419f6f26',
    },
    {
        name: 'Solf J. Kimblee',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/73900.jpg?s=4e06a2216ff671ee62226717168af70e',
    },
    {
        name: 'Trisha Elric',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/59741.jpg?s=df3cb44032001d440f9211ba829092c3',
    },
    {
        name: 'Truth',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/93929.jpg?s=f97f764d9149f3718cccaff787c36869',
    },
    {
        name: 'Van Hohenheim',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/80676.jpg?s=9ea1723c8b75fa22716cabfd858d2497',
    },
    {
        name: 'Winry Rockbell',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/84336.jpg?s=b176965399deaee17a8c6304240a18f8',
    },
]
