// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const genshinCharacters: Character[] = [
    {
        name: 'Aino',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Aino.png',
    },
    {
        name: 'Albedo',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Albedo.png',
    },
    {
        name: 'Alhaitham',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Alhatham.png',
    },
    {
        name: 'Aloy',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Aloy.png',
    },
    {
        name: 'Amber',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ambor.png',
    },
    {
        name: 'Arataki Itto',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Itto.png',
    },
    {
        name: 'Arlecchino',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Arlecchino.png',
    },
    {
        name: 'Baizhu',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Baizhuer.png',
    },
    {
        name: 'Barbara',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Barbara.png',
    },
    {
        name: 'Beidou',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Beidou.png',
    },
    {
        name: 'Bennett',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Bennett.png',
    },
    {
        name: 'Candace',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Candace.png',
    },
    {
        name: 'Charlotte',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Charlotte.png',
    },
    {
        name: 'Chasca',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Chasca.png',
    },
    {
        name: 'Chevreuse',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Chevreuse.png',
    },
    {
        name: 'Chiori',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Chiori.png',
    },
    {
        name: 'Chongyun',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Chongyun.png',
    },
    {
        name: 'Citlali',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Citlali.png',
    },
    {
        name: 'Clorinde',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Clorinde.png',
    },
    {
        name: 'Collei',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Collei.png',
    },
    {
        name: 'Columbina',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Columbina.png',
    },
    {
        name: 'Cyno',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Cyno.png',
    },
    {
        name: 'Dahlia',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Dahlia.png',
    },
    {
        name: 'Dehya',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Dehya.png',
    },
    {
        name: 'Diluc',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Diluc.png',
    },
    {
        name: 'Diona',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Diona.png',
    },
    {
        name: 'Dori',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Dori.png',
    },
    {
        name: 'Durin',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Durin.png',
    },
    {
        name: 'Emilie',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Emilie.png',
    },
    {
        name: 'Escoffier',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Escoffier.png',
    },
    {
        name: 'Eula',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Eula.png',
    },
    {
        name: 'Faruzan',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Faruzan.png',
    },
    {
        name: 'Fischl',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Fischl.png',
    },
    {
        name: 'Flins',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Flins.png',
    },
    {
        name: 'Freminet',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Freminet.png',
    },
    {
        name: 'Furina',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Furina.png',
    },
    {
        name: 'Gaming',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Gaming.png',
    },
    {
        name: 'Ganyu',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ganyu.png',
    },
    {
        name: 'Gorou',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Gorou.png',
    },
    {
        name: 'Hu Tao',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Hutao.png',
    },
    {
        name: 'Iansan',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Iansan.png',
    },
    {
        name: 'Ifa',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ifa.png',
    },
    {
        name: 'Illuga',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Illuga.png',
    },
    {
        name: 'Ineffa',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ineffa.png',
    },
    {
        name: 'Jahoda',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Jahoda.png',
    },
    {
        name: 'Jean',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Qin.png',
    },
    {
        name: 'Kachina',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Kachina.png',
    },
    {
        name: 'Kaedehara Kazuha',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Kazuha.png',
    },
    {
        name: 'Kaeya',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Kaeya.png',
    },
    {
        name: 'Kamisato Ayaka',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ayaka.png',
    },
    {
        name: 'Kamisato Ayato',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ayato.png',
    },
    {
        name: 'Kaveh',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Kaveh.png',
    },
    {
        name: 'Keqing',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Keqing.png',
    },
    {
        name: 'Kinich',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Kinich.png',
    },
    {
        name: 'Kirara',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Momoka.png',
    },
    {
        name: 'Klee',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Klee.png',
    },
    {
        name: 'Kujou Sara',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Sara.png',
    },
    {
        name: 'Kuki Shinobu',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Shinobu.png',
    },
    {
        name: 'Lan Yan',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Lanyan.png',
    },
    {
        name: 'Lauma',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Lauma.png',
    },
    {
        name: 'Layla',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Layla.png',
    },
    {
        name: 'Lisa',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Lisa.png',
    },
    {
        name: 'Lynette',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Linette.png',
    },
    {
        name: 'Lyney',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Liney.png',
    },
    {
        name: 'Manekin',
        imageUrl:
            'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_MannequinBoy.png',
    },
    {
        name: 'Manekina',
        imageUrl:
            'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_MannequinGirl.png',
    },
    {
        name: 'Mavuika',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Mavuika.png',
    },
    {
        name: 'Mika',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Mika.png',
    },
    {
        name: 'Mona',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Mona.png',
    },
    {
        name: 'Mualani',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Mualani.png',
    },
    {
        name: 'Nahida',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Nahida.png',
    },
    {
        name: 'Navia',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Navia.png',
    },
    {
        name: 'Nefer',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Nefer.png',
    },
    {
        name: 'Neuvillette',
        imageUrl:
            'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Neuvillette.png',
    },
    {
        name: 'Nilou',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Nilou.png',
    },
    {
        name: 'Ningguang',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Ningguang.png',
    },
    {
        name: 'Noelle',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Noel.png',
    },
    {
        name: 'Ororon',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Olorun.png',
    },
    {
        name: 'Qiqi',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Qiqi.png',
    },
    {
        name: 'Raiden Shogun',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Shougun.png',
    },
    {
        name: 'Razor',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Razor.png',
    },
    {
        name: 'Rosaria',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Rosaria.png',
    },
    {
        name: 'Sangonomiya Kokomi',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Kokomi.png',
    },
    {
        name: 'Sayu',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Sayu.png',
    },
    {
        name: 'Sethos',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Sethos.png',
    },
    {
        name: 'Shenhe',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Shenhe.png',
    },
    {
        name: 'Shikanoin Heizou',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Heizo.png',
    },
    {
        name: 'Sigewinne',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Sigewinne.png',
    },
    {
        name: 'Skirk',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_SkirkNew.png',
    },
    {
        name: 'Sucrose',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Sucrose.png',
    },
    {
        name: 'Tartaglia',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Tartaglia.png',
    },
    {
        name: 'Thoma',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Tohma.png',
    },
    {
        name: 'Tighnari',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Tighnari.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerBoy.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerBoy.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerBoy.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerBoy.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerBoy.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerBoy.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerGirl.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerGirl.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerGirl.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerGirl.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerGirl.png',
    },
    {
        name: 'Traveler',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_PlayerGirl.png',
    },
    {
        name: 'Varesa',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Varesa.png',
    },
    {
        name: 'Varka',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Varka.png',
    },
    {
        name: 'Venti',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Venti.png',
    },
    {
        name: 'Wanderer',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Wanderer.png',
    },
    {
        name: 'Wriothesley',
        imageUrl:
            'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Wriothesley.png',
    },
    {
        name: 'Xiangling',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Xiangling.png',
    },
    {
        name: 'Xianyun',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Liuyun.png',
    },
    {
        name: 'Xiao',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Xiao.png',
    },
    {
        name: 'Xilonen',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Xilonen.png',
    },
    {
        name: 'Xingqiu',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Xingqiu.png',
    },
    {
        name: 'Xinyan',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Xinyan.png',
    },
    {
        name: 'Yae Miko',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Yae.png',
    },
    {
        name: 'Yanfei',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Feiyan.png',
    },
    {
        name: 'Yaoyao',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Yaoyao.png',
    },
    {
        name: 'Yelan',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Yelan.png',
    },
    {
        name: 'Yoimiya',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Yoimiya.png',
    },
    {
        name: 'Yumemizuki Mizuki',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Mizuki.png',
    },
    {
        name: 'Yun Jin',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Yunjin.png',
    },
    {
        name: 'Zhongli',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Zhongli.png',
    },
    {
        name: 'Zibai',
        imageUrl: 'https://gi.yatta.moe/assets/UI/UI_AvatarIcon_Zibai.png',
    },
]
