// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const genshinCharacters: Character[] = [
    {
        name: 'Aino',
        imageUrl: 'genshin-impact/aino.webp',
    },
    {
        name: 'Albedo',
        imageUrl: 'genshin-impact/albedo.webp',
    },
    {
        name: 'Alhaitham',
        imageUrl: 'genshin-impact/alhaitham.webp',
    },
    {
        name: 'Aloy',
        imageUrl: 'genshin-impact/aloy.webp',
    },
    {
        name: 'Amber',
        imageUrl: 'genshin-impact/amber.webp',
    },
    {
        name: 'Arataki Itto',
        imageUrl: 'genshin-impact/arataki-itto.webp',
    },
    {
        name: 'Arlecchino',
        imageUrl: 'genshin-impact/arlecchino.webp',
    },
    {
        name: 'Baizhu',
        imageUrl: 'genshin-impact/baizhu.webp',
    },
    {
        name: 'Barbara',
        imageUrl: 'genshin-impact/barbara.webp',
    },
    {
        name: 'Beidou',
        imageUrl: 'genshin-impact/beidou.webp',
    },
    {
        name: 'Bennett',
        imageUrl: 'genshin-impact/bennett.webp',
    },
    {
        name: 'Candace',
        imageUrl: 'genshin-impact/candace.webp',
    },
    {
        name: 'Charlotte',
        imageUrl: 'genshin-impact/charlotte.webp',
    },
    {
        name: 'Chasca',
        imageUrl: 'genshin-impact/chasca.webp',
    },
    {
        name: 'Chevreuse',
        imageUrl: 'genshin-impact/chevreuse.webp',
    },
    {
        name: 'Chiori',
        imageUrl: 'genshin-impact/chiori.webp',
    },
    {
        name: 'Chongyun',
        imageUrl: 'genshin-impact/chongyun.webp',
    },
    {
        name: 'Citlali',
        imageUrl: 'genshin-impact/citlali.webp',
    },
    {
        name: 'Clorinde',
        imageUrl: 'genshin-impact/clorinde.webp',
    },
    {
        name: 'Collei',
        imageUrl: 'genshin-impact/collei.webp',
    },
    {
        name: 'Columbina',
        imageUrl: 'genshin-impact/columbina.webp',
    },
    {
        name: 'Cyno',
        imageUrl: 'genshin-impact/cyno.webp',
    },
    {
        name: 'Dahlia',
        imageUrl: 'genshin-impact/dahlia.webp',
    },
    {
        name: 'Dehya',
        imageUrl: 'genshin-impact/dehya.webp',
    },
    {
        name: 'Diluc',
        imageUrl: 'genshin-impact/diluc.webp',
    },
    {
        name: 'Diona',
        imageUrl: 'genshin-impact/diona.webp',
    },
    {
        name: 'Dori',
        imageUrl: 'genshin-impact/dori.webp',
    },
    {
        name: 'Durin',
        imageUrl: 'genshin-impact/durin.webp',
    },
    {
        name: 'Emilie',
        imageUrl: 'genshin-impact/emilie.webp',
    },
    {
        name: 'Escoffier',
        imageUrl: 'genshin-impact/escoffier.webp',
    },
    {
        name: 'Eula',
        imageUrl: 'genshin-impact/eula.webp',
    },
    {
        name: 'Faruzan',
        imageUrl: 'genshin-impact/faruzan.webp',
    },
    {
        name: 'Fischl',
        imageUrl: 'genshin-impact/fischl.webp',
    },
    {
        name: 'Flins',
        imageUrl: 'genshin-impact/flins.webp',
    },
    {
        name: 'Freminet',
        imageUrl: 'genshin-impact/freminet.webp',
    },
    {
        name: 'Furina',
        imageUrl: 'genshin-impact/furina.webp',
    },
    {
        name: 'Gaming',
        imageUrl: 'genshin-impact/gaming.webp',
    },
    {
        name: 'Ganyu',
        imageUrl: 'genshin-impact/ganyu.webp',
    },
    {
        name: 'Gorou',
        imageUrl: 'genshin-impact/gorou.webp',
    },
    {
        name: 'Hu Tao',
        imageUrl: 'genshin-impact/hu-tao.webp',
    },
    {
        name: 'Iansan',
        imageUrl: 'genshin-impact/iansan.webp',
    },
    {
        name: 'Ifa',
        imageUrl: 'genshin-impact/ifa.webp',
    },
    {
        name: 'Illuga',
        imageUrl: 'genshin-impact/illuga.webp',
    },
    {
        name: 'Ineffa',
        imageUrl: 'genshin-impact/ineffa.webp',
    },
    {
        name: 'Jahoda',
        imageUrl: 'genshin-impact/jahoda.webp',
    },
    {
        name: 'Jean',
        imageUrl: 'genshin-impact/jean.webp',
    },
    {
        name: 'Kachina',
        imageUrl: 'genshin-impact/kachina.webp',
    },
    {
        name: 'Kaedehara Kazuha',
        imageUrl: 'genshin-impact/kaedehara-kazuha.webp',
    },
    {
        name: 'Kaeya',
        imageUrl: 'genshin-impact/kaeya.webp',
    },
    {
        name: 'Kamisato Ayaka',
        imageUrl: 'genshin-impact/kamisato-ayaka.webp',
    },
    {
        name: 'Kamisato Ayato',
        imageUrl: 'genshin-impact/kamisato-ayato.webp',
    },
    {
        name: 'Kaveh',
        imageUrl: 'genshin-impact/kaveh.webp',
    },
    {
        name: 'Keqing',
        imageUrl: 'genshin-impact/keqing.webp',
    },
    {
        name: 'Kinich',
        imageUrl: 'genshin-impact/kinich.webp',
    },
    {
        name: 'Kirara',
        imageUrl: 'genshin-impact/kirara.webp',
    },
    {
        name: 'Klee',
        imageUrl: 'genshin-impact/klee.webp',
    },
    {
        name: 'Kujou Sara',
        imageUrl: 'genshin-impact/kujou-sara.webp',
    },
    {
        name: 'Kuki Shinobu',
        imageUrl: 'genshin-impact/kuki-shinobu.webp',
    },
    {
        name: 'Lan Yan',
        imageUrl: 'genshin-impact/lan-yan.webp',
    },
    {
        name: 'Lauma',
        imageUrl: 'genshin-impact/lauma.webp',
    },
    {
        name: 'Layla',
        imageUrl: 'genshin-impact/layla.webp',
    },
    {
        name: 'Lisa',
        imageUrl: 'genshin-impact/lisa.webp',
    },
    {
        name: 'Lynette',
        imageUrl: 'genshin-impact/lynette.webp',
    },
    {
        name: 'Lyney',
        imageUrl: 'genshin-impact/lyney.webp',
    },
    {
        name: 'Manekin',
        imageUrl: 'genshin-impact/manekin.webp',
    },
    {
        name: 'Manekina',
        imageUrl: 'genshin-impact/manekina.webp',
    },
    {
        name: 'Mavuika',
        imageUrl: 'genshin-impact/mavuika.webp',
    },
    {
        name: 'Mika',
        imageUrl: 'genshin-impact/mika.webp',
    },
    {
        name: 'Mona',
        imageUrl: 'genshin-impact/mona.webp',
    },
    {
        name: 'Mualani',
        imageUrl: 'genshin-impact/mualani.webp',
    },
    {
        name: 'Nahida',
        imageUrl: 'genshin-impact/nahida.webp',
    },
    {
        name: 'Navia',
        imageUrl: 'genshin-impact/navia.webp',
    },
    {
        name: 'Nefer',
        imageUrl: 'genshin-impact/nefer.webp',
    },
    {
        name: 'Neuvillette',
        imageUrl: 'genshin-impact/neuvillette.webp',
    },
    {
        name: 'Nilou',
        imageUrl: 'genshin-impact/nilou.webp',
    },
    {
        name: 'Ningguang',
        imageUrl: 'genshin-impact/ningguang.webp',
    },
    {
        name: 'Noelle',
        imageUrl: 'genshin-impact/noelle.webp',
    },
    {
        name: 'Ororon',
        imageUrl: 'genshin-impact/ororon.webp',
    },
    {
        name: 'Qiqi',
        imageUrl: 'genshin-impact/qiqi.webp',
    },
    {
        name: 'Raiden Shogun',
        imageUrl: 'genshin-impact/raiden-shogun.webp',
    },
    {
        name: 'Razor',
        imageUrl: 'genshin-impact/razor.webp',
    },
    {
        name: 'Rosaria',
        imageUrl: 'genshin-impact/rosaria.webp',
    },
    {
        name: 'Sangonomiya Kokomi',
        imageUrl: 'genshin-impact/sangonomiya-kokomi.webp',
    },
    {
        name: 'Sayu',
        imageUrl: 'genshin-impact/sayu.webp',
    },
    {
        name: 'Sethos',
        imageUrl: 'genshin-impact/sethos.webp',
    },
    {
        name: 'Shenhe',
        imageUrl: 'genshin-impact/shenhe.webp',
    },
    {
        name: 'Shikanoin Heizou',
        imageUrl: 'genshin-impact/shikanoin-heizou.webp',
    },
    {
        name: 'Sigewinne',
        imageUrl: 'genshin-impact/sigewinne.webp',
    },
    {
        name: 'Skirk',
        imageUrl: 'genshin-impact/skirk.webp',
    },
    {
        name: 'Sucrose',
        imageUrl: 'genshin-impact/sucrose.webp',
    },
    {
        name: 'Tartaglia',
        imageUrl: 'genshin-impact/tartaglia.webp',
    },
    {
        name: 'Thoma',
        imageUrl: 'genshin-impact/thoma.webp',
    },
    {
        name: 'Tighnari',
        imageUrl: 'genshin-impact/tighnari.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-1.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-2.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-3.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-4.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-5.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-6.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-7.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-8.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-9.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-10.webp',
    },
    {
        name: 'Traveler',
        imageUrl: 'genshin-impact/traveler-11.webp',
    },
    {
        name: 'Varesa',
        imageUrl: 'genshin-impact/varesa.webp',
    },
    {
        name: 'Varka',
        imageUrl: 'genshin-impact/varka.webp',
    },
    {
        name: 'Venti',
        imageUrl: 'genshin-impact/venti.webp',
    },
    {
        name: 'Wanderer',
        imageUrl: 'genshin-impact/wanderer.webp',
    },
    {
        name: 'Wriothesley',
        imageUrl: 'genshin-impact/wriothesley.webp',
    },
    {
        name: 'Xiangling',
        imageUrl: 'genshin-impact/xiangling.webp',
    },
    {
        name: 'Xianyun',
        imageUrl: 'genshin-impact/xianyun.webp',
    },
    {
        name: 'Xiao',
        imageUrl: 'genshin-impact/xiao.webp',
    },
    {
        name: 'Xilonen',
        imageUrl: 'genshin-impact/xilonen.webp',
    },
    {
        name: 'Xingqiu',
        imageUrl: 'genshin-impact/xingqiu.webp',
    },
    {
        name: 'Xinyan',
        imageUrl: 'genshin-impact/xinyan.webp',
    },
    {
        name: 'Yae Miko',
        imageUrl: 'genshin-impact/yae-miko.webp',
    },
    {
        name: 'Yanfei',
        imageUrl: 'genshin-impact/yanfei.webp',
    },
    {
        name: 'Yaoyao',
        imageUrl: 'genshin-impact/yaoyao.webp',
    },
    {
        name: 'Yelan',
        imageUrl: 'genshin-impact/yelan.webp',
    },
    {
        name: 'Yoimiya',
        imageUrl: 'genshin-impact/yoimiya.webp',
    },
    {
        name: 'Yumemizuki Mizuki',
        imageUrl: 'genshin-impact/yumemizuki-mizuki.webp',
    },
    {
        name: 'Yun Jin',
        imageUrl: 'genshin-impact/yun-jin.webp',
    },
    {
        name: 'Zhongli',
        imageUrl: 'genshin-impact/zhongli.webp',
    },
    {
        name: 'Zibai',
        imageUrl: 'genshin-impact/zibai.webp',
    },
]
