// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const hunterXHunterCharacters: Character[] = [
    {
        name: 'Alluka Zoldyck',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/294552.jpg?s=b16da6ceef71780ab111310463ae0815',
    },
    {
        name: 'Baka Ki El Dogra',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/136507.jpg?s=2d3459da616f53aec4406315431486e7',
    },
    {
        name: 'Beans',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/146367.jpg?s=550803e11e847cacf4ec33c2fb2b018f',
    },
    {
        name: 'Biscuit Krueger',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/194667.jpg?s=b2a4def7e985c1ca4f4aac63a511ffc5',
    },
    {
        name: 'Canary',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/183995.jpg?s=f3daa267fcb40cde6f81813641aeb6ee',
    },
    {
        name: 'Chrollo Lucilfer',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/182387.jpg?s=82532b8deca18069b86e7f598e0ca914',
    },
    {
        name: 'Feitan Portor',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/174721.jpg?s=bf0a62d8405521bfb141e131c363f73d',
    },
    {
        name: 'Ging Freecss',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/231795.jpg?s=a02e50645c7dc0816f3e7108cbef2c42',
    },
    {
        name: 'Gon Freecss',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/174517.jpg?s=c8133cf450dc6bf13ba52d6781759101',
    },
    {
        name: 'Hisoka Morow',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/174561.jpg?s=74fd92ebbe0d14dec69aeba8eff36bb9',
    },
    {
        name: 'Ikalgo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/260383.jpg?s=5e249f1c0911e34be4c5adfb71ddeb46',
    },
    {
        name: 'Illumi Zoldyck',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/174521.jpg?s=3b9c5ccadb580670fc0942edd8d06a6d',
    },
    {
        name: 'Isaac Netero',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/257355.jpg?s=1371e4c5acb62a73bf7843b25b58d25d',
    },
    {
        name: 'Kalluto Zoldyck',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/246235.jpg?s=24e0366f5b53069bed3c60129f0d6af2',
    },
    {
        name: 'Killua Zoldyck',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/327920.jpg?s=afd533ace6e7ce81ccf877d3d97880bb',
    },
    {
        name: 'Kite',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/203429.jpg?s=682fcc486dc7f39ddb369bc7f69e4e2e',
    },
    {
        name: 'Knov',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/215471.jpg?s=9beb6998d43b2a342dcf270c95364f18',
    },
    {
        name: 'Knuckle Bine',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/572043.jpg?s=cf8198f5dc0f99572f017a5de720c4f7',
    },
    {
        name: 'Komugi',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/243865.jpg?s=ba3e72a4decf1f8b6bcc191e2ca6e265',
    },
    {
        name: 'Kurapika',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/549312.jpg?s=fc4bb9699591fdf742c7fee5593c961e',
    },
    {
        name: 'Leorio Paladiknight',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/549311.jpg?s=ba86161de766b11580c7fbdf23849cbc',
    },
    {
        name: 'Machi Komachine',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/182389.jpg?s=2917ed42c768d10f35b49cce9808ebd6',
    },
    {
        name: 'Meruem',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/243861.jpg?s=7d6b962cafaeb5d6ae91fa8b3d9d38a0',
    },
    {
        name: 'Morel McCarnathy',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/211097.jpg?s=520dbee58e5e4e2b649b4399a8a5a540',
    },
    {
        name: 'Narrator',
        imageUrl:
            'https://cdn.myanimelist.net/images/questionmark_23.gif?s=f7dcbc4a4603d18356d3dfef8abd655c',
    },
    {
        name: 'Neferpitou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/253673.jpg?s=1800b6a0931f971d9c6d47b9ca1cae1c',
    },
    {
        name: 'Nobunaga Hazama',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/183367.jpg?s=7e8818e2920ec5846ef09c776c151592',
    },
    {
        name: 'Pakunoda',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/533870.jpg?s=d39797057e8c2b1d7f02e23616598b07',
    },
    {
        name: 'Palm Siberia',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/211775.jpg?s=7de9548fa42afa4099e346cc1e95145d',
    },
    {
        name: 'Pariston Hill',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/252327.jpg?s=2b153d31b95336d7ecde25e62bd70944',
    },
    {
        name: 'Phinks Magkav',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/193009.jpg?s=f22bd5d9e9e5c4000e7356ae8be626cc',
    },
    {
        name: 'Ponzu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/155619.jpg?s=f76a4e32fa66b12ed7a42c984e4cbea9',
    },
    {
        name: 'Senritsu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/146977.jpg?s=928669cc0e151e0399b1eec9a5950911',
    },
    {
        name: 'Shaiapouf',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/563303.jpg?s=7a8cf7e7410d1961e71255b5e7da4b77',
    },
    {
        name: 'Shalnark Ryuseih',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/178463.jpg?s=365015871815a4c95e857758cb9f1a51',
    },
    {
        name: 'Shizuku Murasaki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/178469.jpg?s=427e08a13cdc14d8cd4fc2410c7bbf9e',
    },
    {
        name: 'Silva Zoldyck',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/198609.jpg?s=49ee8690106ec8d16c817bf4ac1b07be',
    },
    {
        name: 'Tonpa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/138893.jpg?s=cd92d2aec029df450cc2d425cb993012',
    },
    {
        name: 'Uvogin',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/198581.jpg?s=4ca5e00f4e05c9765c4cb1525aa00d21',
    },
    {
        name: 'Zeno Zoldyck',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/193007.jpg?s=7f84d59f56a0a5f43ce1eabf02326b55',
    },
]
