// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const hunterXHunterCharacters: Character[] = [
    {
        name: 'Alluka Zoldyck',
        imageUrl: 'hunter-x-hunter/alluka-zoldyck.webp',
    },
    {
        name: 'Baka Ki El Dogra',
        imageUrl: 'hunter-x-hunter/baka-ki-el-dogra.webp',
    },
    {
        name: 'Beans',
        imageUrl: 'hunter-x-hunter/beans.webp',
    },
    {
        name: 'Biscuit Krueger',
        imageUrl: 'hunter-x-hunter/biscuit-krueger.webp',
    },
    {
        name: 'Canary',
        imageUrl: 'hunter-x-hunter/canary.webp',
    },
    {
        name: 'Chrollo Lucilfer',
        imageUrl: 'hunter-x-hunter/chrollo-lucilfer.webp',
    },
    {
        name: 'Feitan Portor',
        imageUrl: 'hunter-x-hunter/feitan-portor.webp',
    },
    {
        name: 'Ging Freecss',
        imageUrl: 'hunter-x-hunter/ging-freecss.webp',
    },
    {
        name: 'Gon Freecss',
        imageUrl: 'hunter-x-hunter/gon-freecss.webp',
    },
    {
        name: 'Hisoka Morow',
        imageUrl: 'hunter-x-hunter/hisoka-morow.webp',
    },
    {
        name: 'Ikalgo',
        imageUrl: 'hunter-x-hunter/ikalgo.webp',
    },
    {
        name: 'Illumi Zoldyck',
        imageUrl: 'hunter-x-hunter/illumi-zoldyck.webp',
    },
    {
        name: 'Isaac Netero',
        imageUrl: 'hunter-x-hunter/isaac-netero.webp',
    },
    {
        name: 'Kalluto Zoldyck',
        imageUrl: 'hunter-x-hunter/kalluto-zoldyck.webp',
    },
    {
        name: 'Killua Zoldyck',
        imageUrl: 'hunter-x-hunter/killua-zoldyck.webp',
    },
    {
        name: 'Kite',
        imageUrl: 'hunter-x-hunter/kite.webp',
    },
    {
        name: 'Knov',
        imageUrl: 'hunter-x-hunter/knov.webp',
    },
    {
        name: 'Knuckle Bine',
        imageUrl: 'hunter-x-hunter/knuckle-bine.webp',
    },
    {
        name: 'Komugi',
        imageUrl: 'hunter-x-hunter/komugi.webp',
    },
    {
        name: 'Kurapika',
        imageUrl: 'hunter-x-hunter/kurapika.webp',
    },
    {
        name: 'Leorio Paladiknight',
        imageUrl: 'hunter-x-hunter/leorio-paladiknight.webp',
    },
    {
        name: 'Machi Komachine',
        imageUrl: 'hunter-x-hunter/machi-komachine.webp',
    },
    {
        name: 'Meruem',
        imageUrl: 'hunter-x-hunter/meruem.webp',
    },
    {
        name: 'Morel McCarnathy',
        imageUrl: 'hunter-x-hunter/morel-mccarnathy.webp',
    },
    {
        name: 'Narrator',
        imageUrl: 'hunter-x-hunter/narrator.webp',
    },
    {
        name: 'Neferpitou',
        imageUrl: 'hunter-x-hunter/neferpitou.webp',
    },
    {
        name: 'Nobunaga Hazama',
        imageUrl: 'hunter-x-hunter/nobunaga-hazama.webp',
    },
    {
        name: 'Pakunoda',
        imageUrl: 'hunter-x-hunter/pakunoda.webp',
    },
    {
        name: 'Palm Siberia',
        imageUrl: 'hunter-x-hunter/palm-siberia.webp',
    },
    {
        name: 'Pariston Hill',
        imageUrl: 'hunter-x-hunter/pariston-hill.webp',
    },
    {
        name: 'Phinks Magkav',
        imageUrl: 'hunter-x-hunter/phinks-magkav.webp',
    },
    {
        name: 'Ponzu',
        imageUrl: 'hunter-x-hunter/ponzu.webp',
    },
    {
        name: 'Senritsu',
        imageUrl: 'hunter-x-hunter/senritsu.webp',
    },
    {
        name: 'Shaiapouf',
        imageUrl: 'hunter-x-hunter/shaiapouf.webp',
    },
    {
        name: 'Shalnark Ryuseih',
        imageUrl: 'hunter-x-hunter/shalnark-ryuseih.webp',
    },
    {
        name: 'Shizuku Murasaki',
        imageUrl: 'hunter-x-hunter/shizuku-murasaki.webp',
    },
    {
        name: 'Silva Zoldyck',
        imageUrl: 'hunter-x-hunter/silva-zoldyck.webp',
    },
    {
        name: 'Tonpa',
        imageUrl: 'hunter-x-hunter/tonpa.webp',
    },
    {
        name: 'Uvogin',
        imageUrl: 'hunter-x-hunter/uvogin.webp',
    },
    {
        name: 'Zeno Zoldyck',
        imageUrl: 'hunter-x-hunter/zeno-zoldyck.webp',
    },
]
