// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const jujutsuKaisenCharacters: Character[] = [
    {
        name: 'Akari Nitta',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/436202.jpg?s=9a1aa77f51e4950baeb252fad4f1113b',
    },
    {
        name: 'Aoi Toudou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/427604.jpg?s=4471dfaee135cd387a053f4b6556b2b2',
    },
    {
        name: 'Chousou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/524177.jpg?s=91bbde7d801299f3ff1fb5d8388cc133',
    },
    {
        name: 'Dagon',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/564915.jpg?s=ffe03656fac00133a212bf5e7d7bc83b',
    },
    {
        name: 'Hanami',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/414242.jpg?s=4543a6b62596f1adf3c1f24fd2f96185',
    },
    {
        name: 'Haruta Shigemo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/435673.jpg?s=b3f4fcd0b4d7273b7e2105b0ad02cee5',
    },
    {
        name: 'Jougo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/415336.jpg?s=1c6800fbf4d7e4620a8600cd118a0506',
    },
    {
        name: 'Junpei Yoshino',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/434571.jpg?s=8c6f56ed8d59120e9e0d8b85c9997057',
    },
    {
        name: 'Kasumi Miwa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/431905.jpg?s=5baf76ca4b20bd7e4997b80689fda24f',
    },
    {
        name: 'Kento Nanami',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/581424.jpg?s=78de007092c9e32f3555753de4999ee6',
    },
    {
        name: 'Kiyotaka Ijichi',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/435400.jpg?s=7641415da13f5692548ab97229ec46c3',
    },
    {
        name: 'Koukichi Muta',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/444206.jpg?s=9642d0537cdf16690c55ebbcde0c890b',
    },
    {
        name: 'Mahito',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/446508.jpg?s=8cfa45381097f1e9a720982061ec087d',
    },
    {
        name: 'Mai Zenin',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/430336.jpg?s=b958cdf63203469623dcaccb38986280',
    },
    {
        name: 'Maki Zenin',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/423949.jpg?s=72edfa936ac89421e8d16970762d8b5b',
    },
    {
        name: 'Masamichi Yaga',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/431153.jpg?s=dc3960cff5fcde4f9feb70eeb49ff47f',
    },
    {
        name: 'Megumi Fushiguro',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/392689.jpg?s=2395a10b59bb54ec9891c74ef214fea1',
    },
    {
        name: 'Mei Mei',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/435405.jpg?s=59faccb30565d838c66cc66b88d96272',
    },
    {
        name: 'Momo Nishimiya',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/435453.jpg?s=0b7635eeca84125d7aacbdcd743b8eb9',
    },
    {
        name: 'Nagi Yoshino',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/435742.jpg?s=296c1f925d0971b21c1ea9665836a48a',
    },
    {
        name: 'Naobito Zenin',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/526907.jpg?s=8ede27d6dbfe6d7375ca69fe78570e1c',
    },
    {
        name: 'Nobara Kugisaki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/422313.jpg?s=053db48815610ce7fdc280f62a3499ce',
    },
    {
        name: 'Noritoshi Kamo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/430935.jpg?s=43c2932f2095864d481deb8b4f50f551',
    },
    {
        name: 'Panda',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/423950.jpg?s=d898dc5a3174aee1cdcd4108cbdb36c6',
    },
    {
        name: 'Rika Orimoto',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/488827.jpg?s=458a78d94d16e37a6bd9d54bb2092195',
    },
    {
        name: 'Satoru Gojou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/422168.jpg?s=7c1dfc26a9b3a6652da616a0fec7af01',
    },
    {
        name: 'Setsuko Sasaki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/419229.jpg?s=f0796fea6b95836ed7a55f52f3aff16c',
    },
    {
        name: 'Shouko Ieiri',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/423951.jpg?s=5287a63c8b798f195d1db973df2351de',
    },
    {
        name: 'Suguru Getou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/619361.jpg?s=f44b1c92fcebfa466ee403e1d77b5d45',
    },
    {
        name: 'Sukuna Ryoumen',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/431152.jpg?s=776045fc0fe9f2ecf8923f0f9c20f288',
    },
    {
        name: 'Takuma Ino',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/436201.jpg?s=659f941ad1937269825fbfe1a857d94c',
    },
    {
        name: 'Toge Inumaki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/521636.jpg?s=ef7b20ebe6e134fc94303c86e5cd1268',
    },
    {
        name: 'Tsumiki Fushiguro',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/437005.jpg?s=2a852781a432ec72ded62564ca762e9f',
    },
    {
        name: 'Uraume',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/436733.jpg?s=c8089d5c1e35e2368a53f771ad49cf8b',
    },
    {
        name: 'Utahime Iori',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/435404.jpg?s=1627d13c26f9f395bd3c4f286c743bfc',
    },
    {
        name: 'Wasuke Itadori',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/470647.jpg?s=319174a02b6088aa43789ea4b6227c0d',
    },
    {
        name: 'Yoshinobu Gakuganji',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/432951.jpg?s=6075ec5edcf8f70b87a8e774b89270ed',
    },
    {
        name: 'Yuki Tsukumo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/531741.jpg?s=4d1059a04269c9d0e6213c9a268633ea',
    },
    {
        name: 'Yuuji Itadori',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/467646.jpg?s=9e1cb7b0c6c7f145661e8ee93f32215d',
    },
    {
        name: 'Yuuta Okkotsu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/461503.jpg?s=dda1109b054b3b2e6198d91527cfc7ac',
    },
]
