// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const leagueOfLegendsCharacters: Character[] = [
    {
        name: 'Aatrox',
        imageUrl: 'league-of-legends/aatrox.webp',
    },
    {
        name: 'Ahri',
        imageUrl: 'league-of-legends/ahri.webp',
    },
    {
        name: 'Akali',
        imageUrl: 'league-of-legends/akali.webp',
    },
    {
        name: 'Akshan',
        imageUrl: 'league-of-legends/akshan.webp',
    },
    {
        name: 'Alistar',
        imageUrl: 'league-of-legends/alistar.webp',
    },
    {
        name: 'Ambessa',
        imageUrl: 'league-of-legends/ambessa.webp',
    },
    {
        name: 'Amumu',
        imageUrl: 'league-of-legends/amumu.webp',
    },
    {
        name: 'Anivia',
        imageUrl: 'league-of-legends/anivia.webp',
    },
    {
        name: 'Annie',
        imageUrl: 'league-of-legends/annie.webp',
    },
    {
        name: 'Aphelios',
        imageUrl: 'league-of-legends/aphelios.webp',
    },
    {
        name: 'Ashe',
        imageUrl: 'league-of-legends/ashe.webp',
    },
    {
        name: 'Aurelion Sol',
        imageUrl: 'league-of-legends/aurelion-sol.webp',
    },
    {
        name: 'Aurora',
        imageUrl: 'league-of-legends/aurora.webp',
    },
    {
        name: 'Azir',
        imageUrl: 'league-of-legends/azir.webp',
    },
    {
        name: 'Bard',
        imageUrl: 'league-of-legends/bard.webp',
    },
    {
        name: "Bel'Veth",
        imageUrl: 'league-of-legends/bel-veth.webp',
    },
    {
        name: 'Blitzcrank',
        imageUrl: 'league-of-legends/blitzcrank.webp',
    },
    {
        name: 'Brand',
        imageUrl: 'league-of-legends/brand.webp',
    },
    {
        name: 'Braum',
        imageUrl: 'league-of-legends/braum.webp',
    },
    {
        name: 'Briar',
        imageUrl: 'league-of-legends/briar.webp',
    },
    {
        name: 'Caitlyn',
        imageUrl: 'league-of-legends/caitlyn.webp',
    },
    {
        name: 'Camille',
        imageUrl: 'league-of-legends/camille.webp',
    },
    {
        name: 'Cassiopeia',
        imageUrl: 'league-of-legends/cassiopeia.webp',
    },
    {
        name: "Cho'Gath",
        imageUrl: 'league-of-legends/cho-gath.webp',
    },
    {
        name: 'Corki',
        imageUrl: 'league-of-legends/corki.webp',
    },
    {
        name: 'Darius',
        imageUrl: 'league-of-legends/darius.webp',
    },
    {
        name: 'Diana',
        imageUrl: 'league-of-legends/diana.webp',
    },
    {
        name: 'Dr. Mundo',
        imageUrl: 'league-of-legends/dr-mundo.webp',
    },
    {
        name: 'Draven',
        imageUrl: 'league-of-legends/draven.webp',
    },
    {
        name: 'Ekko',
        imageUrl: 'league-of-legends/ekko.webp',
    },
    {
        name: 'Elise',
        imageUrl: 'league-of-legends/elise.webp',
    },
    {
        name: 'Evelynn',
        imageUrl: 'league-of-legends/evelynn.webp',
    },
    {
        name: 'Ezreal',
        imageUrl: 'league-of-legends/ezreal.webp',
    },
    {
        name: 'Fiddlesticks',
        imageUrl: 'league-of-legends/fiddlesticks.webp',
    },
    {
        name: 'Fiora',
        imageUrl: 'league-of-legends/fiora.webp',
    },
    {
        name: 'Fizz',
        imageUrl: 'league-of-legends/fizz.webp',
    },
    {
        name: 'Galio',
        imageUrl: 'league-of-legends/galio.webp',
    },
    {
        name: 'Gangplank',
        imageUrl: 'league-of-legends/gangplank.webp',
    },
    {
        name: 'Garen',
        imageUrl: 'league-of-legends/garen.webp',
    },
    {
        name: 'Gnar',
        imageUrl: 'league-of-legends/gnar.webp',
    },
    {
        name: 'Gragas',
        imageUrl: 'league-of-legends/gragas.webp',
    },
    {
        name: 'Graves',
        imageUrl: 'league-of-legends/graves.webp',
    },
    {
        name: 'Gwen',
        imageUrl: 'league-of-legends/gwen.webp',
    },
    {
        name: 'Hecarim',
        imageUrl: 'league-of-legends/hecarim.webp',
    },
    {
        name: 'Heimerdinger',
        imageUrl: 'league-of-legends/heimerdinger.webp',
    },
    {
        name: 'Hwei',
        imageUrl: 'league-of-legends/hwei.webp',
    },
    {
        name: 'Illaoi',
        imageUrl: 'league-of-legends/illaoi.webp',
    },
    {
        name: 'Irelia',
        imageUrl: 'league-of-legends/irelia.webp',
    },
    {
        name: 'Ivern',
        imageUrl: 'league-of-legends/ivern.webp',
    },
    {
        name: 'Janna',
        imageUrl: 'league-of-legends/janna.webp',
    },
    {
        name: 'Jarvan IV',
        imageUrl: 'league-of-legends/jarvan-iv.webp',
    },
    {
        name: 'Jax',
        imageUrl: 'league-of-legends/jax.webp',
    },
    {
        name: 'Jayce',
        imageUrl: 'league-of-legends/jayce.webp',
    },
    {
        name: 'Jhin',
        imageUrl: 'league-of-legends/jhin.webp',
    },
    {
        name: 'Jinx',
        imageUrl: 'league-of-legends/jinx.webp',
    },
    {
        name: "K'Sante",
        imageUrl: 'league-of-legends/k-sante.webp',
    },
    {
        name: "Kai'Sa",
        imageUrl: 'league-of-legends/kai-sa.webp',
    },
    {
        name: 'Kalista',
        imageUrl: 'league-of-legends/kalista.webp',
    },
    {
        name: 'Karma',
        imageUrl: 'league-of-legends/karma.webp',
    },
    {
        name: 'Karthus',
        imageUrl: 'league-of-legends/karthus.webp',
    },
    {
        name: 'Kassadin',
        imageUrl: 'league-of-legends/kassadin.webp',
    },
    {
        name: 'Katarina',
        imageUrl: 'league-of-legends/katarina.webp',
    },
    {
        name: 'Kayle',
        imageUrl: 'league-of-legends/kayle.webp',
    },
    {
        name: 'Kayn',
        imageUrl: 'league-of-legends/kayn.webp',
    },
    {
        name: 'Kennen',
        imageUrl: 'league-of-legends/kennen.webp',
    },
    {
        name: "Kha'Zix",
        imageUrl: 'league-of-legends/kha-zix.webp',
    },
    {
        name: 'Kindred',
        imageUrl: 'league-of-legends/kindred.webp',
    },
    {
        name: 'Kled',
        imageUrl: 'league-of-legends/kled.webp',
    },
    {
        name: "Kog'Maw",
        imageUrl: 'league-of-legends/kog-maw.webp',
    },
    {
        name: 'LeBlanc',
        imageUrl: 'league-of-legends/leblanc.webp',
    },
    {
        name: 'Lee Sin',
        imageUrl: 'league-of-legends/lee-sin.webp',
    },
    {
        name: 'Leona',
        imageUrl: 'league-of-legends/leona.webp',
    },
    {
        name: 'Lillia',
        imageUrl: 'league-of-legends/lillia.webp',
    },
    {
        name: 'Lissandra',
        imageUrl: 'league-of-legends/lissandra.webp',
    },
    {
        name: 'Lucian',
        imageUrl: 'league-of-legends/lucian.webp',
    },
    {
        name: 'Lulu',
        imageUrl: 'league-of-legends/lulu.webp',
    },
    {
        name: 'Lux',
        imageUrl: 'league-of-legends/lux.webp',
    },
    {
        name: 'Malphite',
        imageUrl: 'league-of-legends/malphite.webp',
    },
    {
        name: 'Malzahar',
        imageUrl: 'league-of-legends/malzahar.webp',
    },
    {
        name: 'Maokai',
        imageUrl: 'league-of-legends/maokai.webp',
    },
    {
        name: 'Master Yi',
        imageUrl: 'league-of-legends/master-yi.webp',
    },
    {
        name: 'Mel',
        imageUrl: 'league-of-legends/mel.webp',
    },
    {
        name: 'Milio',
        imageUrl: 'league-of-legends/milio.webp',
    },
    {
        name: 'Miss Fortune',
        imageUrl: 'league-of-legends/miss-fortune.webp',
    },
    {
        name: 'Mordekaiser',
        imageUrl: 'league-of-legends/mordekaiser.webp',
    },
    {
        name: 'Morgana',
        imageUrl: 'league-of-legends/morgana.webp',
    },
    {
        name: 'Naafiri',
        imageUrl: 'league-of-legends/naafiri.webp',
    },
    {
        name: 'Nami',
        imageUrl: 'league-of-legends/nami.webp',
    },
    {
        name: 'Nasus',
        imageUrl: 'league-of-legends/nasus.webp',
    },
    {
        name: 'Nautilus',
        imageUrl: 'league-of-legends/nautilus.webp',
    },
    {
        name: 'Neeko',
        imageUrl: 'league-of-legends/neeko.webp',
    },
    {
        name: 'Nidalee',
        imageUrl: 'league-of-legends/nidalee.webp',
    },
    {
        name: 'Nilah',
        imageUrl: 'league-of-legends/nilah.webp',
    },
    {
        name: 'Nocturne',
        imageUrl: 'league-of-legends/nocturne.webp',
    },
    {
        name: 'Nunu & Willump',
        imageUrl: 'league-of-legends/nunu-willump.webp',
    },
    {
        name: 'Olaf',
        imageUrl: 'league-of-legends/olaf.webp',
    },
    {
        name: 'Orianna',
        imageUrl: 'league-of-legends/orianna.webp',
    },
    {
        name: 'Ornn',
        imageUrl: 'league-of-legends/ornn.webp',
    },
    {
        name: 'Pantheon',
        imageUrl: 'league-of-legends/pantheon.webp',
    },
    {
        name: 'Poppy',
        imageUrl: 'league-of-legends/poppy.webp',
    },
    {
        name: 'Pyke',
        imageUrl: 'league-of-legends/pyke.webp',
    },
    {
        name: 'Qiyana',
        imageUrl: 'league-of-legends/qiyana.webp',
    },
    {
        name: 'Quinn',
        imageUrl: 'league-of-legends/quinn.webp',
    },
    {
        name: 'Rakan',
        imageUrl: 'league-of-legends/rakan.webp',
    },
    {
        name: 'Rammus',
        imageUrl: 'league-of-legends/rammus.webp',
    },
    {
        name: "Rek'Sai",
        imageUrl: 'league-of-legends/rek-sai.webp',
    },
    {
        name: 'Rell',
        imageUrl: 'league-of-legends/rell.webp',
    },
    {
        name: 'Renata Glasc',
        imageUrl: 'league-of-legends/renata-glasc.webp',
    },
    {
        name: 'Renekton',
        imageUrl: 'league-of-legends/renekton.webp',
    },
    {
        name: 'Rengar',
        imageUrl: 'league-of-legends/rengar.webp',
    },
    {
        name: 'Riven',
        imageUrl: 'league-of-legends/riven.webp',
    },
    {
        name: 'Rumble',
        imageUrl: 'league-of-legends/rumble.webp',
    },
    {
        name: 'Ryze',
        imageUrl: 'league-of-legends/ryze.webp',
    },
    {
        name: 'Samira',
        imageUrl: 'league-of-legends/samira.webp',
    },
    {
        name: 'Sejuani',
        imageUrl: 'league-of-legends/sejuani.webp',
    },
    {
        name: 'Senna',
        imageUrl: 'league-of-legends/senna.webp',
    },
    {
        name: 'Seraphine',
        imageUrl: 'league-of-legends/seraphine.webp',
    },
    {
        name: 'Sett',
        imageUrl: 'league-of-legends/sett.webp',
    },
    {
        name: 'Shaco',
        imageUrl: 'league-of-legends/shaco.webp',
    },
    {
        name: 'Shen',
        imageUrl: 'league-of-legends/shen.webp',
    },
    {
        name: 'Shyvana',
        imageUrl: 'league-of-legends/shyvana.webp',
    },
    {
        name: 'Singed',
        imageUrl: 'league-of-legends/singed.webp',
    },
    {
        name: 'Sion',
        imageUrl: 'league-of-legends/sion.webp',
    },
    {
        name: 'Sivir',
        imageUrl: 'league-of-legends/sivir.webp',
    },
    {
        name: 'Skarner',
        imageUrl: 'league-of-legends/skarner.webp',
    },
    {
        name: 'Smolder',
        imageUrl: 'league-of-legends/smolder.webp',
    },
    {
        name: 'Sona',
        imageUrl: 'league-of-legends/sona.webp',
    },
    {
        name: 'Soraka',
        imageUrl: 'league-of-legends/soraka.webp',
    },
    {
        name: 'Swain',
        imageUrl: 'league-of-legends/swain.webp',
    },
    {
        name: 'Sylas',
        imageUrl: 'league-of-legends/sylas.webp',
    },
    {
        name: 'Syndra',
        imageUrl: 'league-of-legends/syndra.webp',
    },
    {
        name: 'Tahm Kench',
        imageUrl: 'league-of-legends/tahm-kench.webp',
    },
    {
        name: 'Taliyah',
        imageUrl: 'league-of-legends/taliyah.webp',
    },
    {
        name: 'Talon',
        imageUrl: 'league-of-legends/talon.webp',
    },
    {
        name: 'Taric',
        imageUrl: 'league-of-legends/taric.webp',
    },
    {
        name: 'Teemo',
        imageUrl: 'league-of-legends/teemo.webp',
    },
    {
        name: 'Thresh',
        imageUrl: 'league-of-legends/thresh.webp',
    },
    {
        name: 'Tristana',
        imageUrl: 'league-of-legends/tristana.webp',
    },
    {
        name: 'Trundle',
        imageUrl: 'league-of-legends/trundle.webp',
    },
    {
        name: 'Tryndamere',
        imageUrl: 'league-of-legends/tryndamere.webp',
    },
    {
        name: 'Twisted Fate',
        imageUrl: 'league-of-legends/twisted-fate.webp',
    },
    {
        name: 'Twitch',
        imageUrl: 'league-of-legends/twitch.webp',
    },
    {
        name: 'Udyr',
        imageUrl: 'league-of-legends/udyr.webp',
    },
    {
        name: 'Urgot',
        imageUrl: 'league-of-legends/urgot.webp',
    },
    {
        name: 'Varus',
        imageUrl: 'league-of-legends/varus.webp',
    },
    {
        name: 'Vayne',
        imageUrl: 'league-of-legends/vayne.webp',
    },
    {
        name: 'Veigar',
        imageUrl: 'league-of-legends/veigar.webp',
    },
    {
        name: "Vel'Koz",
        imageUrl: 'league-of-legends/vel-koz.webp',
    },
    {
        name: 'Vex',
        imageUrl: 'league-of-legends/vex.webp',
    },
    {
        name: 'Vi',
        imageUrl: 'league-of-legends/vi.webp',
    },
    {
        name: 'Viego',
        imageUrl: 'league-of-legends/viego.webp',
    },
    {
        name: 'Viktor',
        imageUrl: 'league-of-legends/viktor.webp',
    },
    {
        name: 'Vladimir',
        imageUrl: 'league-of-legends/vladimir.webp',
    },
    {
        name: 'Volibear',
        imageUrl: 'league-of-legends/volibear.webp',
    },
    {
        name: 'Warwick',
        imageUrl: 'league-of-legends/warwick.webp',
    },
    {
        name: 'Wukong',
        imageUrl: 'league-of-legends/wukong.webp',
    },
    {
        name: 'Xayah',
        imageUrl: 'league-of-legends/xayah.webp',
    },
    {
        name: 'Xerath',
        imageUrl: 'league-of-legends/xerath.webp',
    },
    {
        name: 'Xin Zhao',
        imageUrl: 'league-of-legends/xin-zhao.webp',
    },
    {
        name: 'Yasuo',
        imageUrl: 'league-of-legends/yasuo.webp',
    },
    {
        name: 'Yone',
        imageUrl: 'league-of-legends/yone.webp',
    },
    {
        name: 'Yorick',
        imageUrl: 'league-of-legends/yorick.webp',
    },
    {
        name: 'Yunara',
        imageUrl: 'league-of-legends/yunara.webp',
    },
    {
        name: 'Yuumi',
        imageUrl: 'league-of-legends/yuumi.webp',
    },
    {
        name: 'Zaahen',
        imageUrl: 'league-of-legends/zaahen.webp',
    },
    {
        name: 'Zac',
        imageUrl: 'league-of-legends/zac.webp',
    },
    {
        name: 'Zed',
        imageUrl: 'league-of-legends/zed.webp',
    },
    {
        name: 'Zeri',
        imageUrl: 'league-of-legends/zeri.webp',
    },
    {
        name: 'Ziggs',
        imageUrl: 'league-of-legends/ziggs.webp',
    },
    {
        name: 'Zilean',
        imageUrl: 'league-of-legends/zilean.webp',
    },
    {
        name: 'Zoe',
        imageUrl: 'league-of-legends/zoe.webp',
    },
    {
        name: 'Zyra',
        imageUrl: 'league-of-legends/zyra.webp',
    },
]
