// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const movieCharacters: Character[] = [
    {
        name: '¿Quieres ser mi hijo?',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg',
    },
    {
        name: '12 Angry Men',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2QXLVh32JKaWTjFJU3n8aIxRK9P.jpg',
    },
    {
        name: 'A Brighter Summer Day',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3l8fOAwiN3N5n3hHnZ51eog7Zu2.jpg',
    },
    {
        name: "A Dog's Will",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/imcOp1kJsCsAFCoOtY5OnPrFbAf.jpg',
    },
    {
        name: 'A Silent Voice: The Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg',
    },
    {
        name: 'American History X',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/x2drgoXYZ8484lqyDj7L1CEVR4T.jpg',
    },
    {
        name: 'Apocalypse Now',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg',
    },
    {
        name: 'Avengers: Endgame',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
    },
    {
        name: 'Avengers: Infinity War',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    },
    {
        name: 'Back to the Future',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg',
    },
    {
        name: 'Chainsaw Man - The Movie: Reze Arc',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
    },
    {
        name: 'Cinema Paradiso',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg',
    },
    {
        name: 'City Lights',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg',
    },
    {
        name: 'City Lights',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg',
    },
    {
        name: 'City of God',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg',
    },
    {
        name: 'Clouds',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/d0OdD1I8qAfETvE9Rp9Voq7R8LR.jpg',
    },
    {
        name: 'Counterattack',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/38I76hGcFY6xB47pjm7pZwkfuAF.jpg',
    },
    {
        name: 'Dead Poets Society',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/l5NbiHKUmahlAT3Q1ig8Tyl9xrc.jpg',
    },
    {
        name: 'Dedicated to my ex',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xc4bTXVwYNXi10jG9dwcaYt5IpU.jpg',
    },
    {
        name: 'Dilwale Dulhania Le Jayenge',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
    },
    {
        name: 'Dou kyu sei – Classmates',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
    },
    {
        name: 'Fight Club',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    },
    {
        name: 'Forrest Gump',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
    },
    {
        name: "Gabriel's Inferno",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
    },
    {
        name: "Gabriel's Inferno: Part II",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
    },
    {
        name: "Gabriel's Inferno: Part III",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg',
    },
    {
        name: 'Given',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pegCub2zdYD5As43AOmGsIctuKc.jpg',
    },
    {
        name: 'Gladiator',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    },
    {
        name: 'GoodFellas',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
    },
    {
        name: 'Grave of the Fireflies',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
    },
    {
        name: 'Green Book',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg',
    },
    {
        name: 'Harakiri',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3nPwMd3KviJWaHzG9fZCqlwWMas.jpg',
    },
    {
        name: 'High and Low',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tgNjemQPG96uIezpiUiXFcer5ga.jpg',
    },
    {
        name: 'Hope',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg',
    },
    {
        name: 'Hotarubi no Mori e',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg',
    },
    {
        name: "Howl's Moving Castle",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg',
    },
    {
        name: 'I Want to Eat Your Pancreas',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qpV8kvRfAntV7D4aOOsLIz7OdPc.jpg',
    },
    {
        name: 'Ikiru',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg',
    },
    {
        name: 'Impossible Things',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
    },
    {
        name: 'Inception',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
    },
    {
        name: 'Interstellar',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    },
    {
        name: "It's a Wonderful Life",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg',
    },
    {
        name: 'Josee, the Tiger and the Fish',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/z1D8xi9x4uEhyFruo7uEHXUMD4K.jpg',
    },
    {
        name: 'Klaus',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/q125RHUDgR4gjwh1QkfYuJLYkL.jpg',
    },
    {
        name: 'Le Trou',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xyZhiOz5NHVBUKlpioxjwajy7pm.jpg',
    },
    {
        name: 'Léon: The Professional',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bxB2q91nKYp8JNzqE7t7TWBVupB.jpg',
    },
    {
        name: 'Life in a Year',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bP7u19opmHXYeTCUwGjlLldmUMc.jpg',
    },
    {
        name: 'Life Is Beautiful',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
    },
    {
        name: 'Lucy Shimmers and the Prince of Peace',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yfnJ5qIYx7q33fY4jqv9Pu95RSg.jpg',
    },
    {
        name: 'Miracle in Cell No. 7',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bOth4QmNyEkalwahfPCfiXjNh1r.jpg',
    },
    {
        name: 'Modern Times',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7uoiKOEjxBBW0AgDGQWrlfGQ90w.jpg',
    },
    {
        name: 'Neon Genesis Evangelion: The End of Evangelion',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/j6G24dqI4WgUtChhWjfnI4lnmiK.jpg',
    },
    {
        name: 'Oldboy',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg',
    },
    {
        name: 'Once Upon a Studio',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aiy3G1cYWV3LgKZHY6a3jL8bjYL.jpg',
    },
    {
        name: 'Once Upon a Time in America',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg',
    },
    {
        name: 'Once Upon a Time in the West',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qbYgqOczabWNn2XKwgMtVrntD6P.jpg',
    },
    {
        name: "One Flew Over the Cuckoo's Nest",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg',
    },
    {
        name: 'Out of the Clear Blue Sky',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/o9cSEHrXzPOO4OIoT9yrdxc216w.jpg',
    },
    {
        name: 'Parasite',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    },
    {
        name: 'Paths of Glory',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tJXwtzOSNUC8dxJfrdvkNtGrrgW.jpg',
    },
    {
        name: 'Perfect Blue',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6WTiOCfDPP8XV4jqfloiVWf7KHq.jpg',
    },
    {
        name: 'Princess Mononoke',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cMYCDADoLKLbB83g4WnJegaZimC.jpg',
    },
    {
        name: 'Psycho',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg',
    },
    {
        name: 'Pulp Fiction',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
    },
    {
        name: 'Radical',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lOAJYpX608aT0ApIv63ZTnol27Y.jpg',
    },
    {
        name: 'Rear Window',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ILVF0eJxHMddjxeQhswFtpMtqx.jpg',
    },
    {
        name: 'Saving Private Ryan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg',
    },
    {
        name: "Schindler's List",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    },
    {
        name: 'Se7en',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg',
    },
    {
        name: 'Seven Samurai',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
    },
    {
        name: 'Spider-Man: Across the Spider-Verse',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    },
    {
        name: 'Spider-Man: Into the Spider-Verse',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    },
    {
        name: 'Spirited Away',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    },
    {
        name: 'Sunset Boulevard',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zt8aQ6ksqK6p1AopC5zVTDS9pKT.jpg',
    },
    {
        name: 'The Dark Knight',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    },
    {
        name: 'The Empire Strikes Back',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg',
    },
    {
        name: 'The Forge',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oranxontIQRmhuyQlkoAwxpeBYz.jpg',
    },
    {
        name: 'The Godfather',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    },
    {
        name: 'The Godfather Part II',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
    },
    {
        name: 'The Good, the Bad and the Ugly',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
    },
    {
        name: 'The Great Dictator',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg',
    },
    {
        name: 'The Green Mile',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
    },
    {
        name: 'The Intouchables',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg',
    },
    {
        name: 'The Legend of 1900',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iOcbJ5pxokOPDRgieVDbsFMrCc6.jpg',
    },
    {
        name: 'The Legend of Hei',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4jfbKKLpqts3i2h2obkrONcjTg1.jpg',
    },
    {
        name: 'The Lion King',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
    },
    {
        name: 'The Lord of the Rings: The Fellowship of the Ring',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    },
    {
        name: 'The Lord of the Rings: The Return of the King',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    },
    {
        name: 'The Lord of the Rings: The Two Towers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
    },
    {
        name: 'The Matrix',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/p96dm7sCMn4VYAStA6siNz30G1r.jpg',
    },
    {
        name: 'The Pianist',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
    },
    {
        name: 'The Quintessential Quintuplets Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg',
    },
    {
        name: 'The Shawshank Redemption',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    },
    {
        name: 'The Silence of the Lambs',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
    },
    {
        name: 'The Wild Robot',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    },
    {
        name: 'Violet Evergarden: The Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bajajkoErDst0JxdFyBkABiF9rW.jpg',
    },
    {
        name: 'We All Loved Each Other So Much',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zGGWYpiKNwjpKxelPxOMqJnUgDs.jpg',
    },
    {
        name: 'Whiplash',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    },
    {
        name: 'Wolf Children',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3Nllh6JgcrFdtOn6iFOWHudNInd.jpg',
    },
    {
        name: 'Your Name.',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg',
    },
]
