// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const movieCharacters: Character[] = [
    {
        name: 'A Minecraft Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg',
    },
    {
        name: 'A Working Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg',
    },
    {
        name: 'Alien: Covenant',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg',
    },
    {
        name: 'Avatar',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg',
    },
    {
        name: 'Avatar: Fire and Ash',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
    },
    {
        name: 'Avatar: The Way of Water',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    },
    {
        name: 'Avengers: Infinity War',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    },
    {
        name: 'Back to the Future',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg',
    },
    {
        name: 'Ballerina',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg',
    },
    {
        name: 'Barbie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    },
    {
        name: 'Blade Runner 2049',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    },
    {
        name: 'Bugonia',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rSdOua3wKMEaFWDcKAYWRjXQWOt.jpg',
    },
    {
        name: 'Deadpool',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
    },
    {
        name: 'Deadpool & Wolverine',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    },
    {
        name: 'Despicable Me 4',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
    },
    {
        name: 'Dune',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg',
    },
    {
        name: 'Dune: Part Two',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    },
    {
        name: 'F1',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tLMG65ZpCbC64aPaXGoCgPPLwb4.jpg',
    },
    {
        name: 'Fast X',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    },
    {
        name: 'Fifty Shades of Grey',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg',
    },
    {
        name: 'Fight Club',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    },
    {
        name: 'Final Destination Bloodlines',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg',
    },
    {
        name: 'Forrest Gump',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
    },
    {
        name: 'Frankenstein',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/g4JtvGlQO7DByTI6frUobqvSL3R.jpg',
    },
    {
        name: 'Frozen',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/itAKcobTYGpYT8Phwjd8c9hleTo.jpg',
    },
    {
        name: 'GoodFellas',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
    },
    {
        name: 'Hamnet',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vbeyOZm2bvBXcbgPD3v6o94epPX.jpg',
    },
    {
        name: 'Harry Potter and the Chamber of Secrets',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg',
    },
    {
        name: "Harry Potter and the Philosopher's Stone",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    },
    {
        name: "He's Just Not That Into You",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jip2ap24Y6JxEgzVRyNqyYssnyR.jpg',
    },
    {
        name: 'Hidden Strike',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zsbolOkw8RhTU4DKOrpf4M7KCmi.jpg',
    },
    {
        name: 'How to Train Your Dragon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/41dfWUWtg1kUZcJYe6Zk6ewxzMu.jpg',
    },
    {
        name: 'Inception',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
    },
    {
        name: 'Inside Out 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    },
    {
        name: 'Interstellar',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
    },
    {
        name: 'Iron Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
    },
    {
        name: 'Iron Man 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
    },
    {
        name: 'Joker',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    },
    {
        name: 'Joy Ride',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1LVGjf1QWgkNNPQssZtuT1GYKoP.jpg',
    },
    {
        name: 'Jurassic World Rebirth',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg',
    },
    {
        name: 'KPop Demon Hunters',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zT7Lhw3BhJbMkRqm9Zlx2YGMsY0.jpg',
    },
    {
        name: 'Liar Liar',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/p1habYSdC7oD3WygQ5lynU5G5rV.jpg',
    },
    {
        name: 'Lilo & Stitch',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ckQzKpQJO4ZQDCN5evdpKcfm7Ys.jpg',
    },
    {
        name: 'Marty Supreme',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg',
    },
    {
        name: 'Mission: Impossible - The Final Reckoning',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg',
    },
    {
        name: 'Moana 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg',
    },
    {
        name: 'Nobody',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg',
    },
    {
        name: 'Nobody 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iyxwxDZCpIm0vIORaHpmgJv2BGF.jpg',
    },
    {
        name: "Now You See Me: Now You Don't",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oD3Eey4e4Z259XLm3eD3WGcoJAh.jpg',
    },
    {
        name: 'One Battle After Another',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lbBWwxBht4JFP5PsuJ5onpMqugW.jpg',
    },
    {
        name: 'Oppenheimer',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    },
    {
        name: 'Pirates of the Caribbean: The Curse of the Black Pearl',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/poHwCZeWzJCShH7tOjg8RIoyjcw.jpg',
    },
    {
        name: 'Predator: Badlands',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/erTRAi241eYF4K8KoGGOI8kFPox.jpg',
    },
    {
        name: 'Pulp Fiction',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
    },
    {
        name: 'Scary Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fVQFPRuw3yWXojYDJvA5EoFjUOY.jpg',
    },
    {
        name: "Schindler's List",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    },
    {
        name: 'Scream',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lr9ZIrmuwVmZhpZuTCW8D9g0ZJe.jpg',
    },
    {
        name: 'Se7en',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg',
    },
    {
        name: 'Shrek',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg',
    },
    {
        name: 'Sinners',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/705nQHqe4JGdEisrQmVYmXyjs1U.jpg',
    },
    {
        name: 'Sonic the Hedgehog 3',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg',
    },
    {
        name: 'Spider-Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kjdJntyBeEvqm9w97QGBdxPptzj.jpg',
    },
    {
        name: 'Spider-Man: Across the Spider-Verse',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    },
    {
        name: 'Spider-Man: Into the Spider-Verse',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    },
    {
        name: 'Spider-Man: No Way Home',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    },
    {
        name: 'Star Wars',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
    },
    {
        name: 'Star Wars: The Last Jedi',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg',
    },
    {
        name: 'Superman',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ldyfo0BKmz5rWtJJKCvwaNS4cJT.jpg',
    },
    {
        name: 'The Avengers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    },
    {
        name: 'The Dark Knight',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    },
    {
        name: 'The Devil Wears Prada',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8912AsVuS7Sj915apArUFbv6F9L.jpg',
    },
    {
        name: 'The Faculty',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5XetJwmAiDC0EtH23NIXaqFn3Wl.jpg',
    },
    {
        name: 'The Family Plan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg',
    },
    {
        name: 'The Fantastic 4: First Steps',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nf5qaSEvyYSNeFH0YhSs5EsBLX9.jpg',
    },
    {
        name: 'The Godfather',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    },
    {
        name: 'The Godfather Part II',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
    },
    {
        name: 'The Gorge',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg',
    },
    {
        name: 'The Green Mile',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
    },
    {
        name: 'The Hobbit: The Battle of the Five Armies',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xT98tLqatZPQApyRmlPL12LtiWp.jpg',
    },
    {
        name: 'The Housemaid',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
    },
    {
        name: 'The Hundred-Foot Journey',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1vFhSr7INoulu18smHqicft05i8.jpg',
    },
    {
        name: 'The Lion King',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
    },
    {
        name: 'The Lord of the Rings: The Fellowship of the Ring',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    },
    {
        name: 'The Lord of the Rings: The Return of the King',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    },
    {
        name: 'The Matrix',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/p96dm7sCMn4VYAStA6siNz30G1r.jpg',
    },
    {
        name: 'The Naked Gun',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rwla9vqzrKVVKVKiOuROTIXGsxj.jpg',
    },
    {
        name: 'The Rip',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eZo31Dhl5BQ6GfbMNf3oU0tUvPZ.jpg',
    },
    {
        name: 'The Running Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dKL78O9zxczVgjtNcQ9UkbYLzqX.jpg',
    },
    {
        name: 'The Shawshank Redemption',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    },
    {
        name: 'The Super Mario Bros. Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    },
    {
        name: 'The Terminator',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qvktm0BHcnmDpul4Hz01GIazWPr.jpg',
    },
    {
        name: 'The Wild Robot',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    },
    {
        name: 'Titanic',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
    },
    {
        name: 'Top Gun: Maverick',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    },
    {
        name: 'Toy Story',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
    },
    {
        name: 'TRON: Ares',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/chpWmskl3aKm1aTZqUHRCtviwPy.jpg',
    },
    {
        name: 'Weapons',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg',
    },
    {
        name: 'xXx',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg',
    },
    {
        name: 'Zootopia',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg',
    },
    {
        name: 'Zootopia 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg',
    },
]
