// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const movieCharacters: Character[] = [
    {
        name: '"Wuthering Heights"',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3YBce6dTh1D5oCMITXk2S5QhPt.jpg',
    },
    {
        name: '28 Years Later: The Bone Temple',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kK1BGkG3KAvWB0WMV1DfOx9yTMZ.jpg',
    },
    {
        name: "A Fox's Tale",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9JmD7mrimja0tpHMhiA231h6JHx.jpg',
    },
    {
        name: 'Alien: Covenant',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg',
    },
    {
        name: 'Alpha',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iE3P4LFSJCBX5PRWxbPs7DQh7yI.jpg',
    },
    {
        name: 'Anaconda',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qxMv3HwAB3XPuwNLMhVRg795Ktp.jpg',
    },
    {
        name: 'Avatar: Fire and Ash',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
    },
    {
        name: 'Bāhubali: The Epic',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/z9YIo2qscyaXYgRqIdRJtND3bw8.jpg',
    },
    {
        name: 'Bizet: Carmen',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tYtzaMu0rzWcp2jUHD7IvRo0La.jpg',
    },
    {
        name: 'Blades of the Guardians: Wind Rises in the Desert',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/AbunjMKX4P1sDNlKfhYrWkIoRD9.jpg',
    },
    {
        name: 'Bloodline Killer',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wHmzCQwBzT6m8wtZdXHOIITn82B.jpg',
    },
    {
        name: 'Caring Cabin',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zC84wmZcQPanuKQg5288go9QQ2P.jpg',
    },
    {
        name: 'Chainsaw Man - The Movie: Reze Arc',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
    },
    {
        name: 'Cold Storage',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3HA2iiq982e01EKXJvPFyfMADVM.jpg',
    },
    {
        name: 'Crime 101',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/heMdO64ys1hR896YE2jvTv8JlBX.jpg',
    },
    {
        name: 'Crime 101',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/heMdO64ys1hR896YE2jvTv8JlBX.jpg',
    },
    {
        name: 'David',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7lFG1WrCwAxBfyGK8ahlBVzXno7.jpg',
    },
    {
        name: 'Dracula',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/libhghrUSBSEdHgF9uP1SQES0nQ.jpg',
    },
    {
        name: 'EVANGELION 30th Anniversary Special Screening',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jWKTLEbJCsbfIQV4IsiU9H1qRAN.jpg',
    },
    {
        name: 'F1',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vqBmyAj0Xm9LnS1xe1MSlMAJyHq.jpg',
    },
    {
        name: 'Firecreek',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zypuu5aEoyM5tadMAkbNm3Kccq9.jpg',
    },
    {
        name: 'Frankenstein',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/g4JtvGlQO7DByTI6frUobqvSL3R.jpg',
    },
    {
        name: 'From the Ashes',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aEUH2ECoZHvSmoMzJpca0STF2CZ.jpg',
    },
    {
        name: 'Ginger & Rosa',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5EmQri2RwjN5zELdAtUY52k71pN.jpg',
    },
    {
        name: 'GOAT',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
    },
    {
        name: "Good Luck, Have Fun, Don't Die",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rWcfOdY7TU6lTdazWj0ebDZnAfO.jpg',
    },
    {
        name: 'Greenland 2: Migration',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg',
    },
    {
        name: 'Hamnet',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vbeyOZm2bvBXcbgPD3v6o94epPX.jpg',
    },
    {
        name: 'Hellfire',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tQti9QTf13MfzNpXguijgNh7ojE.jpg',
    },
    {
        name: 'Hidden Strike',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zsbolOkw8RhTU4DKOrpf4M7KCmi.jpg',
    },
    {
        name: 'Hoppers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
    },
    {
        name: 'House on Eden',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2xVyCvnuVVRpYohPxrvwxZiH49r.jpg',
    },
    {
        name: 'Hunting Season',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cbryTyaWdqrKpQCw6K7zm2jrB5v.jpg',
    },
    {
        name: 'Ice Skater',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/m93BKabB7Je8WQACed58BXeHNNR.jpg',
    },
    {
        name: 'Interstellar',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    },
    {
        name: 'Jay Kelly',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lEXYpY9X17pGC7xYYy17Guv0L3J.jpg',
    },
    {
        name: 'Joy Ride',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1LVGjf1QWgkNNPQssZtuT1GYKoP.jpg',
    },
    {
        name: 'JUJUTSU KAISEN: Execution',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/v0s3dx6am0RzfsuK3KdEy8ZoCDs.jpg',
    },
    {
        name: 'Kasganj',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4pIXubnvdR0K0W4bIC389auCo3l.jpg',
    },
    {
        name: 'KPop Demon Hunters',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zT7Lhw3BhJbMkRqm9Zlx2YGMsY0.jpg',
    },
    {
        name: 'Leberkäsjunkie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gMCNiOVCSxg4C7per145CVVFd18.jpg',
    },
    {
        name: 'Marty Supreme',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg',
    },
    {
        name: 'Mercy',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pyok1kZJCfyuFapYXzHcy7BLlQa.jpg',
    },
    {
        name: 'Mouseboat Massacre',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ctKqevqOwbeVg5GLQLu5VvnCjan.jpg',
    },
    {
        name: 'Muzzle: City of Wolves',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8qTMRmC07XCGidnKQFLbRM3FoDU.jpg',
    },
    {
        name: 'My Fault',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
    },
    {
        name: 'Nobody',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg',
    },
    {
        name: "Now You See Me: Now You Don't",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oD3Eey4e4Z259XLm3eD3WGcoJAh.jpg',
    },
    {
        name: 'One Battle After Another',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lbBWwxBht4JFP5PsuJ5onpMqugW.jpg',
    },
    {
        name: 'One Battle After Another',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lbBWwxBht4JFP5PsuJ5onpMqugW.jpg',
    },
    {
        name: 'Oscar Shaw',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tsE3nySukwrfUjouz8vzvKTcXNC.jpg',
    },
    {
        name: 'Peaky Blinders: The Immortal Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gRMalasZEzsZi4w2VFuYusfSfqf.jpg',
    },
    {
        name: 'Petmalu',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bgaEjqLHzrHFLtXxf0iKtcdF4rP.jpg',
    },
    {
        name: 'Playdate',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fGodXWqJkkkbSebPIlxLSygV8GY.jpg',
    },
    {
        name: 'Pose',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qhyyyWrHUbl6QG4udAJj17CBa5.jpg',
    },
    {
        name: 'Predator: Badlands',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/erTRAi241eYF4K8KoGGOI8kFPox.jpg',
    },
    {
        name: 'Project Hail Mary',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vOhW7Lbt4kZAqe0vJhVC4Ced9x2.jpg',
    },
    {
        name: 'Reminders of Him',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7L6rceYgzQ0NeHD7PRDNrRoQ291.jpg',
    },
    {
        name: 'Return to Silent Hill',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fqAGFN2K2kDL0EHxvJaXzaMUkkt.jpg',
    },
    {
        name: 'Scream 7',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg',
    },
    {
        name: 'Sentimental Value',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pz9NCWxxOk3o0W3v1Zkhawrwb4i.jpg',
    },
    {
        name: 'SHARE?',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9HZv3pcDFZDSl8pdzxohHQZa1y3.jpg',
    },
    {
        name: 'Shelter',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg',
    },
    {
        name: 'Sinners',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fWPgbnt2LSqkQ6cdQc0SZN9CpLm.jpg',
    },
    {
        name: 'Sinners',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fWPgbnt2LSqkQ6cdQc0SZN9CpLm.jpg',
    },
    {
        name: 'Solo Mio',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/efSsZJaddeq0LOABZqpCXdMxv9P.jpg',
    },
    {
        name: 'State of Fear',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3Eaqedg8MAlnP51GYY8MCSIdTnV.jpg',
    },
    {
        name: 'The Alamo',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aZrWYkxCCwSPKp4VjVvn46uHbIX.jpg',
    },
    {
        name: 'The Avengers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    },
    {
        name: 'The Aviary',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/u6HUQcOQsgkFFO8xCITfxQz6ivc.jpg',
    },
    {
        name: 'The Bluff',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/w0jwjFmRu2or7LQqh1tSMFjq0At.jpg',
    },
    {
        name: 'The Bride!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg',
    },
    {
        name: 'The Empire',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2GQ5GMsx7Ri4gJsMDU2aDLbMg1S.jpg',
    },
    {
        name: 'The Family Plan 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/semFxuYx6HcrkZzslgAkBqfJvZk.jpg',
    },
    {
        name: 'The Feast',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/z7qDuUII2IgJ1I7HgElWn44d3JA.jpg',
    },
    {
        name: 'The Flood',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mvjqqklMpHwOxc40rn7dMhGT0Fc.jpg',
    },
    {
        name: 'The Godfather',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    },
    {
        name: 'The Good Boy',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wWMLpfTmPV3dW4fYF5YJ04j0N4N.jpg',
    },
    {
        name: 'The Housemaid',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
    },
    {
        name: 'The Internship',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fYqSOkix4rbDiZW0ACNnvZCpT6X.jpg',
    },
    {
        name: 'The Rip',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eZo31Dhl5BQ6GfbMNf3oU0tUvPZ.jpg',
    },
    {
        name: 'The Running Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dKL78O9zxczVgjtNcQ9UkbYLzqX.jpg',
    },
    {
        name: "The Shadow's Edge",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg',
    },
    {
        name: 'The Shawshank Redemption',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    },
    {
        name: 'The Super Mario Galaxy Movie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
    },
    {
        name: 'The Wrecking Crew',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg',
    },
    {
        name: 'Torrente for President',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yrDKwAdZRJjoQ9RZwzRGPpMC7U1.jpg',
    },
    {
        name: 'Trap House',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6tpAPeuuqbVnYWWPoOLEDLSBU7a.jpg',
    },
    {
        name: 'Troll 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/p6xAExLNFbHcLfvSuvLPoM8aqZU.jpg',
    },
    {
        name: 'Turbulence',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jRuiKL4S9UpLma2ZlM47xIu2gbe.jpg',
    },
    {
        name: 'Vanaveera',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oBYExKI8E3bTzQjPkofhpV2EJon.jpg',
    },
    {
        name: 'War Machine',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tlPgDzwIE7VYYIIAGCTUOnN4wI1.jpg',
    },
    {
        name: 'Weapons',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg',
    },
    {
        name: 'Whistle',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/84vAcFwxoObBuMWANWQXCg0Umg8.jpg',
    },
    {
        name: 'Wildcat',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/h893ImjM6Fsv5DFhKJdlZFZIJno.jpg',
    },
    {
        name: 'Worldbreaker',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4xx25oYs08myEelHiSbOuVi80Ki.jpg',
    },
    {
        name: 'xXx',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg',
    },
    {
        name: 'Your Heart Will Be Broken',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iGpMm603GUKH2SiXB2S5m4sZ17t.jpg',
    },
    {
        name: 'Zombie Prom',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6HvTONoBSrToDrHO9x6lk3cAVhx.jpg',
    },
    {
        name: 'Zootopia 2',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg',
    },
]
