// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const myHeroAcademiaCharacters: Character[] = [
    {
        name: 'All For One',
        imageUrl: 'my-hero-academia/all-for-one.webp',
    },
    {
        name: 'All Might',
        imageUrl: 'my-hero-academia/all-might.webp',
    },
    {
        name: 'Chiyo Shuuzenji',
        imageUrl: 'my-hero-academia/chiyo-shuuzenji.webp',
    },
    {
        name: 'Denki Kaminari',
        imageUrl: 'my-hero-academia/denki-kaminari.webp',
    },
    {
        name: 'Ectoplasm',
        imageUrl: 'my-hero-academia/ectoplasm.webp',
    },
    {
        name: 'Eijirou Kirishima',
        imageUrl: 'my-hero-academia/eijirou-kirishima.webp',
    },
    {
        name: 'Female Reporter',
        imageUrl: 'my-hero-academia/female-reporter.webp',
    },
    {
        name: 'Fumikage Tokoyami',
        imageUrl: 'my-hero-academia/fumikage-tokoyami.webp',
    },
    {
        name: 'Hanta Sero',
        imageUrl: 'my-hero-academia/hanta-sero.webp',
    },
    {
        name: 'Hizashi Yamada',
        imageUrl: 'my-hero-academia/hizashi-yamada.webp',
    },
    {
        name: 'Inko Midoriya',
        imageUrl: 'my-hero-academia/inko-midoriya.webp',
    },
    {
        name: 'Izuku Midoriya',
        imageUrl: 'my-hero-academia/izuku-midoriya.webp',
    },
    {
        name: 'Katsuki Bakugou',
        imageUrl: 'my-hero-academia/katsuki-bakugou.webp',
    },
    {
        name: 'Ken Ishiyama',
        imageUrl: 'my-hero-academia/ken-ishiyama.webp',
    },
    {
        name: 'Kouji Kouda',
        imageUrl: 'my-hero-academia/kouji-kouda.webp',
    },
    {
        name: 'Kurogiri',
        imageUrl: 'my-hero-academia/kurogiri.webp',
    },
    {
        name: 'Kyouka Jirou',
        imageUrl: 'my-hero-academia/kyouka-jirou.webp',
    },
    {
        name: 'Mashirao Ojiro',
        imageUrl: 'my-hero-academia/mashirao-ojiro.webp',
    },
    {
        name: 'Mezou Shouji',
        imageUrl: 'my-hero-academia/mezou-shouji.webp',
    },
    {
        name: 'Mina Ashido',
        imageUrl: 'my-hero-academia/mina-ashido.webp',
    },
    {
        name: 'Minoru Mineta',
        imageUrl: 'my-hero-academia/minoru-mineta.webp',
    },
    {
        name: 'Momo Yaoyorozu',
        imageUrl: 'my-hero-academia/momo-yaoyorozu.webp',
    },
    {
        name: 'Naomasa Tsukauchi',
        imageUrl: 'my-hero-academia/naomasa-tsukauchi.webp',
    },
    {
        name: 'Nemuri Kayama',
        imageUrl: 'my-hero-academia/nemuri-kayama.webp',
    },
    {
        name: 'Nezu',
        imageUrl: 'my-hero-academia/nezu.webp',
    },
    {
        name: 'Noumu',
        imageUrl: 'my-hero-academia/noumu.webp',
    },
    {
        name: 'Ochako Uraraka',
        imageUrl: 'my-hero-academia/ochako-uraraka.webp',
    },
    {
        name: 'Sansa Tamagawa',
        imageUrl: 'my-hero-academia/sansa-tamagawa.webp',
    },
    {
        name: 'Sekijirou Kan',
        imageUrl: 'my-hero-academia/sekijirou-kan.webp',
    },
    {
        name: 'Shinji Nishiya',
        imageUrl: 'my-hero-academia/shinji-nishiya.webp',
    },
    {
        name: 'Shouta Aizawa',
        imageUrl: 'my-hero-academia/shouta-aizawa.webp',
    },
    {
        name: 'Shouto Todoroki',
        imageUrl: 'my-hero-academia/shouto-todoroki.webp',
    },
    {
        name: 'Snipe',
        imageUrl: 'my-hero-academia/snipe.webp',
    },
    {
        name: 'Tenya Iida',
        imageUrl: 'my-hero-academia/tenya-iida.webp',
    },
    {
        name: 'Thirteen',
        imageUrl: 'my-hero-academia/thirteen.webp',
    },
    {
        name: 'Tomura Shigaraki',
        imageUrl: 'my-hero-academia/tomura-shigaraki.webp',
    },
    {
        name: 'Tooru Hagakure',
        imageUrl: 'my-hero-academia/tooru-hagakure.webp',
    },
    {
        name: 'Tsuyu Asui',
        imageUrl: 'my-hero-academia/tsuyu-asui.webp',
    },
    {
        name: 'Yuu Takeyama',
        imageUrl: 'my-hero-academia/yuu-takeyama.webp',
    },
    {
        name: 'Yuuga Aoyama',
        imageUrl: 'my-hero-academia/yuuga-aoyama.webp',
    },
]
