// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const myHeroAcademiaCharacters: Character[] = [
    {
        name: 'All For One',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/370136.jpg?s=9a8bbc134d9c1719cacb71c58d863e72',
    },
    {
        name: 'All Might',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/310613.jpg?s=2bb273c38247c38003176367645e6488',
    },
    {
        name: 'Chiyo Shuuzenji',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/333080.jpg?s=d737742a6e5c6ad3bc1c3ddba6c4dfa9',
    },
    {
        name: 'Denki Kaminari',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/329527.jpg?s=bdd623918f5fa850d8f2e877318a4a0b',
    },
    {
        name: 'Ectoplasm',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/331374.jpg?s=008f85b12e070b86d3da6144c2e37c1b',
    },
    {
        name: 'Eijirou Kirishima',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/329529.jpg?s=cbfca4fce697447408c68a94d519b1b0',
    },
    {
        name: 'Female Reporter',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/336359.jpg?s=172bbefb9ff8f9dd129fb8b4ec390aaf',
    },
    {
        name: 'Fumikage Tokoyami',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/299402.jpg?s=d73e716fbb2763b3ba1a77289939bf12',
    },
    {
        name: 'Hanta Sero',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/301034.jpg?s=9c53e5d0b43a194eafe90943baec6d10',
    },
    {
        name: 'Hizashi Yamada',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/301650.jpg?s=1c11c5030e2f9c76e778081a463dba39',
    },
    {
        name: 'Inko Midoriya',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/301940.jpg?s=0c9bd5d7f899ceb146caeb1b5ba1ce14',
    },
    {
        name: 'Izuku Midoriya',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/299404.jpg?s=6a448d3702c1d3185ed7ad8f0b8484f0',
    },
    {
        name: 'Katsuki Bakugou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/299406.jpg?s=7ce7f3b38b2ebe0fd31b3a313fa14fe9',
    },
    {
        name: 'Ken Ishiyama',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/333078.jpg?s=daf44d725c55e25c7ffbf6547bdcab53',
    },
    {
        name: 'Kouji Kouda',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/301044.jpg?s=b41351f86e128d6086aa27f93bc94dbe',
    },
    {
        name: 'Kurogiri',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/333082.jpg?s=de23c1013cf7e99bb13844aa120ae158',
    },
    {
        name: 'Kyouka Jirou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/300745.jpg?s=c0e7c66c088b06ea9d3806ce852e84f4',
    },
    {
        name: 'Mashirao Ojiro',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/329531.jpg?s=9b030ce4a029fcaf5f7061a8068f62cb',
    },
    {
        name: 'Mezou Shouji',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/300743.jpg?s=befe73757260a13762736dbb49a0e177',
    },
    {
        name: 'Mina Ashido',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/329525.jpg?s=9d19261a645b157c6533a9c883b4a2df',
    },
    {
        name: 'Minoru Mineta',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/299413.jpg?s=741bc5ed3c8c36569aa514e7a7addec8',
    },
    {
        name: 'Momo Yaoyorozu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/562316.jpg?s=bd0f31951d784f77f2d5b78e568b6115',
    },
    {
        name: 'Naomasa Tsukauchi',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/584633.jpg?s=f5c71cf137032221b0f8832a53a94b8e',
    },
    {
        name: 'Nemuri Kayama',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/366576.jpg?s=ef9b62fe75f8744d82dc6b206d3e33fb',
    },
    {
        name: 'Nezu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/333081.jpg?s=9fa8fc86b6a27cd8cc68f9e2e39d3610',
    },
    {
        name: 'Noumu',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/305706.jpg?s=431596169beb4c541533a05fb017acb2',
    },
    {
        name: 'Ochako Uraraka',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/299421.jpg?s=5c7499bacd3f2c8f4238253a5877c757',
    },
    {
        name: 'Sansa Tamagawa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/589323.jpg?s=b068abc388b7f4dabd3c3f7cbcfc8bfc',
    },
    {
        name: 'Sekijirou Kan',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/326355.jpg?s=2d5694f827c0dc22ea9c9774ce69f914',
    },
    {
        name: 'Shinji Nishiya',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/301653.jpg?s=9dacc3b0620370d2481ea656a213e39b',
    },
    {
        name: 'Shouta Aizawa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/301855.jpg?s=30bde8aa7f840805f22ab894a1eca521',
    },
    {
        name: 'Shouto Todoroki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/332527.jpg?s=575a733f7d22b2b94a12194e051932de',
    },
    {
        name: 'Snipe',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/517346.jpg?s=89a19d192c9d3ecc49f6631376621454',
    },
    {
        name: 'Tenya Iida',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/299417.jpg?s=ae97d822ef7c4cdbe392766389c3f5f1',
    },
    {
        name: 'Thirteen',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/333084.jpg?s=092ed0eb7997393d0852acd05db826ee',
    },
    {
        name: 'Tomura Shigaraki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/272139.jpg?s=ee7d051f5ff04bd4fe6830e0d268cb10',
    },
    {
        name: 'Tooru Hagakure',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/301045.jpg?s=cc99e993a37c8b98554a18f81c26b538',
    },
    {
        name: 'Tsuyu Asui',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/299409.jpg?s=007a26c2a56f15a578815945d1bb2d53',
    },
    {
        name: 'Yuu Takeyama',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/301652.jpg?s=3caf80080ec5cc1f183ea957607085fb',
    },
    {
        name: 'Yuuga Aoyama',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/300752.jpg?s=9d07d0a55f0a3237206588553b8bf1d1',
    },
]
