// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const narutoCharacters: Character[] = [
    {
        name: 'A (Fourth Raikage)',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/4/4c/Fourth_Raikage_2.png',
    },
    {
        name: 'Akamaru',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/0/09/Akamaru_p1.png',
    },
    {
        name: 'Asura Ōtsutsuki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/5/56/Asura_%C5%8Ctsutsuki.png',
    },
    {
        name: 'Azure Fang',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/9/98/Azure_Fang.png',
    },
    {
        name: 'Boruto Uzumaki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/d/de/Boruto_Infobox.png',
    },
    {
        name: 'Chōji Akimichi',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/7d/Ch%C5%8Dji_Akimichi.png',
    },
    {
        name: 'Crimson Fist',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/7d/Crimson_Fist.png',
    },
    {
        name: 'Danzō Shimura',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/1/17/Danz%C5%8D.png',
    },
    {
        name: 'Deidara',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/0/06/Deidara.png',
    },
    {
        name: 'Fudō',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/4/45/Fud%C5%8D.png',
    },
    {
        name: 'Gaara',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/2/20/Gaara_in_Part_I.png',
    },
    {
        name: 'Hagoromo Ōtsutsuki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/6/62/Hagoromo.png',
    },
    {
        name: 'Hashirama Senju',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/7e/Hashirama_Senju.png',
    },
    {
        name: 'Hinata Hyūga',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/9/97/Hinata.png',
    },
    {
        name: 'Hiruzen Sarutobi',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/e/e4/Hiruzen_Sarutobi.png',
    },
    {
        name: 'Ino Yamanaka',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/d/dd/Ino.png',
    },
    {
        name: 'Inojin Yamanaka',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/e/e6/Inojin_movie.png',
    },
    {
        name: 'Isobu',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/d/df/Isobu.png',
    },
    {
        name: 'Itachi Uchiha',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/b/bb/Itachi.png',
    },
    {
        name: 'Iwabee Yuino',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/0/0b/Iwabee_Yuino.png',
    },
    {
        name: 'Jiraiya',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/2/21/Profile_Jiraiya.png',
    },
    {
        name: 'Jūgo',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/4/42/Jugo.png',
    },
    {
        name: 'Kabuto Yakushi',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/c/c9/Kabuto_Part_1.png',
    },
    {
        name: 'Kaguya Ōtsutsuki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/6/6c/Kaguya_%C5%8Ctsutsuki.png',
    },
    {
        name: 'Kakashi Hatake',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png',
    },
    {
        name: 'Kankurō',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/7d/Kankur%C5%8D1.png',
    },
    {
        name: 'Kiba Inuzuka',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/0/03/Kiba.png',
    },
    {
        name: 'Killer B',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/6/63/Killer_B.png',
    },
    {
        name: 'Kisame Hoshigaki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/2/25/Kisame.png',
    },
    {
        name: 'Koji Kashin',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/f/f2/Koji.png',
    },
    {
        name: 'Konohamaru Sarutobi',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/8/89/Konohamaru_p1.png',
    },
    {
        name: 'Madara Uchiha',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/f/fd/Madara.png',
    },
    {
        name: 'Might Guy',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/3/31/Might_Guy.png',
    },
    {
        name: 'Minato Namikaze',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/71/Minato_Namikaze.png',
    },
    {
        name: 'Mitsuki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/5/5c/Mitsuki.png',
    },
    {
        name: 'Nangō',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/c/cf/Nango.png',
    },
    {
        name: 'Naruto Uzumaki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_Part_I.png',
    },
    {
        name: 'Obito Uchiha',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/4/4a/Obito_Uchiha.png',
    },
    {
        name: 'Orochimaru',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/1/14/Orochimaru_Infobox.png',
    },
    {
        name: 'Rock Lee',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/9/97/Rock_Lee_Part_I.png',
    },
    {
        name: 'Sai',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/0/07/Sai_Infobox.png',
    },
    {
        name: 'Sakura Haruno',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/6/64/Sakura_Part_1.png',
    },
    {
        name: 'Sarada Uchiha',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/9/9a/Sarada_Infobox.png',
    },
    {
        name: 'Sasori',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/f/f7/Sasori.png',
    },
    {
        name: 'Sasuke Uchiha',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_1.png',
    },
    {
        name: 'Scarlet Blaze',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/e/eb/Scarlet_Blaze.png',
    },
    {
        name: 'Shikadai Nara',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/3/3d/Shikadai_Nara.png',
    },
    {
        name: 'Shikamaru Nara',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/4/44/Shikamaru_Part_I.png',
    },
    {
        name: 'Shima',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/6/69/Shima.png',
    },
    {
        name: 'Shinki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/78/Shinki.png',
    },
    {
        name: 'Shino Aburame',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/9/9c/Shino.png',
    },
    {
        name: 'Tayuya',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/7/78/Tayuya_Shot.png',
    },
    {
        name: 'Temari',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/b/bb/Temari_newshot.png',
    },
    {
        name: 'Tenten',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/d/da/Tenten_Part_1.png',
    },
    {
        name: 'Tobirama Senju',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/b/be/Tobirama_Senju.png',
    },
    {
        name: 'Toneri Ōtsutsuki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/3/3c/Toneri.png',
    },
    {
        name: 'Tsunade',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/b/b3/Tsunade_infobox2.png',
    },
    {
        name: 'Urashiki Ōtsutsuki',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/f/f6/Urashiki.png',
    },
    {
        name: 'Utakata',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/2/27/Utakata.png',
    },
    {
        name: 'Yamato',
        imageUrl:
            'https://static.wikia.nocookie.net/naruto/images/f/f7/Yamato_newshot.png',
    },
]
