// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const narutoCharacters: Character[] = [
    {
        name: 'A (Fourth Raikage)',
        imageUrl: 'naruto/a-fourth-raikage.webp',
    },
    {
        name: 'Akamaru',
        imageUrl: 'naruto/akamaru.webp',
    },
    {
        name: 'Asura Ōtsutsuki',
        imageUrl: 'naruto/asura-otsutsuki.webp',
    },
    {
        name: 'Azure Fang',
        imageUrl: 'naruto/azure-fang.webp',
    },
    {
        name: 'Boruto Uzumaki',
        imageUrl: 'naruto/boruto-uzumaki.webp',
    },
    {
        name: 'Chōji Akimichi',
        imageUrl: 'naruto/choji-akimichi.webp',
    },
    {
        name: 'Danzō Shimura',
        imageUrl: 'naruto/danzo-shimura.webp',
    },
    {
        name: 'Deidara',
        imageUrl: 'naruto/deidara.webp',
    },
    {
        name: 'Gaara',
        imageUrl: 'naruto/gaara.webp',
    },
    {
        name: 'Hagoromo Ōtsutsuki',
        imageUrl: 'naruto/hagoromo-otsutsuki.webp',
    },
    {
        name: 'Hashirama Senju',
        imageUrl: 'naruto/hashirama-senju.webp',
    },
    {
        name: 'Hinata Hyūga',
        imageUrl: 'naruto/hinata-hyuga.webp',
    },
    {
        name: 'Hiruzen Sarutobi',
        imageUrl: 'naruto/hiruzen-sarutobi.webp',
    },
    {
        name: 'Ino Yamanaka',
        imageUrl: 'naruto/ino-yamanaka.webp',
    },
    {
        name: 'Inojin Yamanaka',
        imageUrl: 'naruto/inojin-yamanaka.webp',
    },
    {
        name: 'Isobu',
        imageUrl: 'naruto/isobu.webp',
    },
    {
        name: 'Itachi Uchiha',
        imageUrl: 'naruto/itachi-uchiha.webp',
    },
    {
        name: 'Iwabee Yuino',
        imageUrl: 'naruto/iwabee-yuino.webp',
    },
    {
        name: 'Jūgo',
        imageUrl: 'naruto/jugo.webp',
    },
    {
        name: 'Kabuto Yakushi',
        imageUrl: 'naruto/kabuto-yakushi.webp',
    },
    {
        name: 'Kaguya Ōtsutsuki',
        imageUrl: 'naruto/kaguya-otsutsuki.webp',
    },
    {
        name: 'Kakashi Hatake',
        imageUrl: 'naruto/kakashi-hatake.webp',
    },
    {
        name: 'Kankurō',
        imageUrl: 'naruto/kankuro.webp',
    },
    {
        name: 'Kiba Inuzuka',
        imageUrl: 'naruto/kiba-inuzuka.webp',
    },
    {
        name: 'Killer B',
        imageUrl: 'naruto/killer-b.webp',
    },
    {
        name: 'Kisame Hoshigaki',
        imageUrl: 'naruto/kisame-hoshigaki.webp',
    },
    {
        name: 'Koji Kashin',
        imageUrl: 'naruto/koji-kashin.webp',
    },
    {
        name: 'Konohamaru Sarutobi',
        imageUrl: 'naruto/konohamaru-sarutobi.webp',
    },
    {
        name: 'Madara Uchiha',
        imageUrl: 'naruto/madara-uchiha.webp',
    },
    {
        name: 'Might Guy',
        imageUrl: 'naruto/might-guy.webp',
    },
    {
        name: 'Minato Namikaze',
        imageUrl: 'naruto/minato-namikaze.webp',
    },
    {
        name: 'Mitsuki',
        imageUrl: 'naruto/mitsuki.webp',
    },
    {
        name: 'Naruto Uzumaki',
        imageUrl: 'naruto/naruto-uzumaki.webp',
    },
    {
        name: 'Obito Uchiha',
        imageUrl: 'naruto/obito-uchiha.webp',
    },
    {
        name: 'Orochimaru',
        imageUrl: 'naruto/orochimaru.webp',
    },
    {
        name: 'Rock Lee',
        imageUrl: 'naruto/rock-lee.webp',
    },
    {
        name: 'Sai',
        imageUrl: 'naruto/sai.webp',
    },
    {
        name: 'Sakura Haruno',
        imageUrl: 'naruto/sakura-haruno.webp',
    },
    {
        name: 'Sarada Uchiha',
        imageUrl: 'naruto/sarada-uchiha.webp',
    },
    {
        name: 'Sasori',
        imageUrl: 'naruto/sasori.webp',
    },
    {
        name: 'Sasuke Uchiha',
        imageUrl: 'naruto/sasuke-uchiha.webp',
    },
    {
        name: 'Scarlet Blaze',
        imageUrl: 'naruto/scarlet-blaze.webp',
    },
    {
        name: 'Shikadai Nara',
        imageUrl: 'naruto/shikadai-nara.webp',
    },
    {
        name: 'Shikamaru Nara',
        imageUrl: 'naruto/shikamaru-nara.webp',
    },
    {
        name: 'Shima',
        imageUrl: 'naruto/shima.webp',
    },
    {
        name: 'Shinki',
        imageUrl: 'naruto/shinki.webp',
    },
    {
        name: 'Shino Aburame',
        imageUrl: 'naruto/shino-aburame.webp',
    },
    {
        name: 'Tayuya',
        imageUrl: 'naruto/tayuya.webp',
    },
    {
        name: 'Temari',
        imageUrl: 'naruto/temari.webp',
    },
    {
        name: 'Tenten',
        imageUrl: 'naruto/tenten.webp',
    },
    {
        name: 'Tobirama Senju',
        imageUrl: 'naruto/tobirama-senju.webp',
    },
    {
        name: 'Toneri Ōtsutsuki',
        imageUrl: 'naruto/toneri-otsutsuki.webp',
    },
    {
        name: 'Tsunade',
        imageUrl: 'naruto/tsunade.webp',
    },
    {
        name: 'Urashiki Ōtsutsuki',
        imageUrl: 'naruto/urashiki-otsutsuki.webp',
    },
    {
        name: 'Utakata',
        imageUrl: 'naruto/utakata.webp',
    },
    {
        name: 'Yamato',
        imageUrl: 'naruto/yamato.webp',
    },
]
