// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const onePieceCharacters: Character[] = [
    {
        name: 'Ace Portgas D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/72220.jpg?s=e92b075a899b3b5d3cdac70615d8853b',
    },
    {
        name: 'Bartolomeo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/249217.jpg?s=eaa65690ad5f400644fd183aa38de18b',
    },
    {
        name: 'Bentham',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/146037.jpg?s=44cac4a3a8b339fd81ca4fed968dcc7b',
    },
    {
        name: 'Bepo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/51353.jpg?s=40b7450df511f6b4c14be5b2a9ee4cfa',
    },
    {
        name: 'Bonney Jewelry',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/146045.jpg?s=24f035b0b9d4c44ea8c9ffe315b1ef1e',
    },
    {
        name: 'Borsalino',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/96168.jpg?s=7c613bd175781463b30215b36fdee4be',
    },
    {
        name: 'Brook',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/161005.jpg?s=8e3191d4d9691fffe3dafaefaf086014',
    },
    {
        name: 'Buggy',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/69112.jpg?s=2bb908ba252c0eaafa779c6d868f379a',
    },
    {
        name: 'Caesar Clown',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/235823.jpg?s=d4adbc93b537a3f85039be9d08c7def9',
    },
    {
        name: 'Carrot',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/323766.jpg?s=9ebc986391a1190f4a4df2774db0f02f',
    },
    {
        name: 'Chopper Tony Tony',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/100536.jpg?s=9536cd3e6fe65064a110b8d8b2f2808e',
    },
    {
        name: 'Crocodile',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/100535.jpg?s=3acba3e9944b9f3d1160fff13f6920c3',
    },
    {
        name: 'Doflamingo Donquixote',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/349513.jpg?s=d4c15f9b8af8e82e7c05e30b4d1453b8',
    },
    {
        name: 'Dragon Monkey D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/193567.jpg?s=5595b229d83ad170578a7c0ed884e346',
    },
    {
        name: 'Enel',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/55111.jpg?s=0a63e7550ac912dd962e350f7b3276f6',
    },
    {
        name: 'Franky',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/210053.jpg?s=58f71be3af78384ac43869b8c681efaf',
    },
    {
        name: 'Garp Monkey D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/509073.jpg?s=8b287628076463de432fb5aedc5b9882',
    },
    {
        name: 'Hancock Boa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/146013.jpg?s=cb2628e503ecea60dc2619b4aedf3247',
    },
    {
        name: 'Hiluluk',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/61610.jpg?s=b4ef0ef554012c72472ce9e5c2b73061',
    },
    {
        name: 'Isshou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/235827.jpg?s=5cc48628a507f3b61f14410d37fd0001',
    },
    {
        name: 'Ivankov Emporio',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/81182.jpg?s=472544a0b803dbcc90102cb4dd6a55dd',
    },
    {
        name: 'Jinbe',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/307148.jpg?s=20f8bf1d3a9854be84b67367849b1322',
    },
    {
        name: 'Kaidou',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/492819.jpg?s=8503e58c06a6c01d16a01621e2002554',
    },
    {
        name: 'Karoo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/64158.jpg?s=41dbaaea36f24977da02481c17b9a9c5',
    },
    {
        name: 'Katakuri Charlotte',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/342776.jpg?s=f470538ebc96929c2d1ba1e27b7a9f63',
    },
    {
        name: 'Kid Eustass',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/12/146187.jpg?s=2dbc3ca21d5d033e5441c16b2a218793',
    },
    {
        name: 'Koby',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/49289.jpg?s=d90ab7c5bd0c2a16f362fbaf4c241f43',
    },
    {
        name: 'Kuma Bartholomew',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/54820.jpg?s=c38c3907abd07e5c46d36fd2a3c11e63',
    },
    {
        name: 'Kuzan',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/96167.jpg?s=74c9e2760d84abd09f828138cc2ad74f',
    },
    {
        name: 'Law Trafalgar',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/10/258757.jpg?s=a537201b5cb91a6905765fee2de00012',
    },
    {
        name: 'Linlin Charlotte',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/337166.jpg?s=3b95915f0c2d215e28e9f45a7201250f',
    },
    {
        name: 'Lucci Rob',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/71509.jpg?s=fac02a589d526c1b519764ce6721f3d1',
    },
    {
        name: 'Luffy Monkey D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/310307.jpg?s=3a27ab33bee665febfba970f24f203ba',
    },
    {
        name: 'Marco',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/100226.jpg?s=a7a5c0a4e8423614b5a681df711e3515',
    },
    {
        name: 'Mihawk Dracule',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/7/69747.jpg?s=b65e6e98b004f965b7c3783b34cdccb6',
    },
    {
        name: 'Monet',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/235837.jpg?s=5a17e63e41a24fa82dd38c19a8df487a',
    },
    {
        name: 'Nami',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/59914.jpg?s=302fa4565e9cbd5368b6ca4da51e1a0c',
    },
    {
        name: 'Newgate Edward',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/100236.jpg?s=7d8b2cff3cdb3b4cae84ff79ddf906cf',
    },
    {
        name: 'Oden Kozuki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/4/433930.jpg?s=9eadde24f4f24e1fe27bf90913183b5c',
    },
    {
        name: 'Perona',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/136777.jpg?s=5da27457890f4a61a4affab397ec202c',
    },
    {
        name: 'Rayleigh Silvers',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/141861.jpg?s=6007c12796bddfe07abbfbdce1b95c46',
    },
    {
        name: 'Reiju Vinsmoke',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/343184.jpg?s=7bd0dd02465b8863ac8caf140e5f15a2',
    },
    {
        name: 'Robin Nico',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/363700.jpg?s=3e7fa6074c0d30c8bede3905680e983c',
    },
    {
        name: 'Roger Gol D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/51747.jpg?s=ae111a084d5f0cba17856337c956bc36',
    },
    {
        name: 'Rosinante Donquixote',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/13/288038.jpg?s=82d48aa53e9927a25f7f0384e4beca67',
    },
    {
        name: 'Sabo',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/15/131855.jpg?s=59b1e7a4a656b27d660740ba85e4e93d',
    },
    {
        name: 'Sakazuki',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/306908.jpg?s=4c7849616d1f127b9ba0888c182f70f3',
    },
    {
        name: 'Sanji',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/136769.jpg?s=52b8fdfc38114a389d83dd5301842556',
    },
    {
        name: 'Senor Pink',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/235809.jpg?s=8bcd643003104bf5a22211f9a606df6f',
    },
    {
        name: 'Shanks',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/307639.jpg?s=175776bc9b9338bdc8f64520b1699548',
    },
    {
        name: 'Smoker',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/5/235841.jpg?s=c18bb601180251c415f4f76a16b84825',
    },
    {
        name: 'Tashigi',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/266983.jpg?s=eccecdea1dd47393ac88de7f45edbba2',
    },
    {
        name: 'Teach Marshall D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/2/109536.jpg?s=85059e538bfbb1e609787c63cdc8c31e',
    },
    {
        name: 'Ulti',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/8/453421.jpg?s=40d1c7539b216bf9dd72c4a70c6f2dff',
    },
    {
        name: 'Usopp',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/16/188076.jpg?s=f24eccad7d76e7747895a9a945d8a3ed',
    },
    {
        name: 'Uta',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/11/506689.jpg?s=b58b76402ef0398ca1263b0cb1f51117',
    },
    {
        name: 'Vivi Nefertari',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/9/298188.jpg?s=767c001fbe4c980713fc2bb71ca988b5',
    },
    {
        name: 'Xebec Rocks D.',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/6/619345.jpg?s=fee812e21df89c11c1ac69881cedd37e',
    },
    {
        name: 'Yamato',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/14/490104.jpg?s=4a01b7f2e3293f5ca0219e7f03f1bc26',
    },
    {
        name: 'Zoro Roronoa',
        imageUrl:
            'https://cdn.myanimelist.net/images/characters/3/100534.jpg?s=4a00840eacc26e9ad86bae6f505e4826',
    },
]
