// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const overwatchCharacters: Character[] = [
    {
        name: 'Ana',
        imageUrl: 'overwatch/ana.webp',
    },
    {
        name: 'Anran',
        imageUrl: 'overwatch/anran.webp',
    },
    {
        name: 'Ashe',
        imageUrl: 'overwatch/ashe.webp',
    },
    {
        name: 'Baptiste',
        imageUrl: 'overwatch/baptiste.webp',
    },
    {
        name: 'Bastion',
        imageUrl: 'overwatch/bastion.webp',
    },
    {
        name: 'Brigitte',
        imageUrl: 'overwatch/brigitte.webp',
    },
    {
        name: 'Cassidy',
        imageUrl: 'overwatch/cassidy.webp',
    },
    {
        name: 'D.Va',
        imageUrl: 'overwatch/d-va.webp',
    },
    {
        name: 'Domina',
        imageUrl: 'overwatch/domina.webp',
    },
    {
        name: 'Doomfist',
        imageUrl: 'overwatch/doomfist.webp',
    },
    {
        name: 'Echo',
        imageUrl: 'overwatch/echo.webp',
    },
    {
        name: 'Emre',
        imageUrl: 'overwatch/emre.webp',
    },
    {
        name: 'Freja',
        imageUrl: 'overwatch/freja.webp',
    },
    {
        name: 'Genji',
        imageUrl: 'overwatch/genji.webp',
    },
    {
        name: 'Hanzo',
        imageUrl: 'overwatch/hanzo.webp',
    },
    {
        name: 'Hazard',
        imageUrl: 'overwatch/hazard.webp',
    },
    {
        name: 'Illari',
        imageUrl: 'overwatch/illari.webp',
    },
    {
        name: 'Jetpack Cat',
        imageUrl: 'overwatch/jetpack-cat.webp',
    },
    {
        name: 'Junker Queen',
        imageUrl: 'overwatch/junker-queen.webp',
    },
    {
        name: 'Junkrat',
        imageUrl: 'overwatch/junkrat.webp',
    },
    {
        name: 'Juno',
        imageUrl: 'overwatch/juno.webp',
    },
    {
        name: 'Kiriko',
        imageUrl: 'overwatch/kiriko.webp',
    },
    {
        name: 'Lifeweaver',
        imageUrl: 'overwatch/lifeweaver.webp',
    },
    {
        name: 'Lúcio',
        imageUrl: 'overwatch/lucio.webp',
    },
    {
        name: 'Mauga',
        imageUrl: 'overwatch/mauga.webp',
    },
    {
        name: 'Mei',
        imageUrl: 'overwatch/mei.webp',
    },
    {
        name: 'Mercy',
        imageUrl: 'overwatch/mercy.webp',
    },
    {
        name: 'Mizuki',
        imageUrl: 'overwatch/mizuki.webp',
    },
    {
        name: 'Moira',
        imageUrl: 'overwatch/moira.webp',
    },
    {
        name: 'Orisa',
        imageUrl: 'overwatch/orisa.webp',
    },
    {
        name: 'Pharah',
        imageUrl: 'overwatch/pharah.webp',
    },
    {
        name: 'Ramattra',
        imageUrl: 'overwatch/ramattra.webp',
    },
    {
        name: 'Reaper',
        imageUrl: 'overwatch/reaper.webp',
    },
    {
        name: 'Reinhardt',
        imageUrl: 'overwatch/reinhardt.webp',
    },
    {
        name: 'Roadhog',
        imageUrl: 'overwatch/roadhog.webp',
    },
    {
        name: 'Sigma',
        imageUrl: 'overwatch/sigma.webp',
    },
    {
        name: 'Sojourn',
        imageUrl: 'overwatch/sojourn.webp',
    },
    {
        name: 'Soldier: 76',
        imageUrl: 'overwatch/soldier-76.webp',
    },
    {
        name: 'Sombra',
        imageUrl: 'overwatch/sombra.webp',
    },
    {
        name: 'Symmetra',
        imageUrl: 'overwatch/symmetra.webp',
    },
    {
        name: 'Torbjörn',
        imageUrl: 'overwatch/torbjorn.webp',
    },
    {
        name: 'Tracer',
        imageUrl: 'overwatch/tracer.webp',
    },
    {
        name: 'Vendetta',
        imageUrl: 'overwatch/vendetta.webp',
    },
    {
        name: 'Venture',
        imageUrl: 'overwatch/venture.webp',
    },
    {
        name: 'Widowmaker',
        imageUrl: 'overwatch/widowmaker.webp',
    },
    {
        name: 'Winston',
        imageUrl: 'overwatch/winston.webp',
    },
    {
        name: 'Wrecking Ball',
        imageUrl: 'overwatch/wrecking-ball.webp',
    },
    {
        name: 'Wuyang',
        imageUrl: 'overwatch/wuyang.webp',
    },
    {
        name: 'Zarya',
        imageUrl: 'overwatch/zarya.webp',
    },
    {
        name: 'Zenyatta',
        imageUrl: 'overwatch/zenyatta.webp',
    },
]
