// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const peopleCharacters: Character[] = [
    {
        name: 'Adam Pearson',
        imageUrl: 'people/adam-pearson.webp',
    },
    {
        name: 'Alexandra Daddario',
        imageUrl: 'people/alexandra-daddario.webp',
    },
    {
        name: 'Ana de Armas',
        imageUrl: 'people/ana-de-armas.webp',
    },
    {
        name: 'Angelina Jolie',
        imageUrl: 'people/angelina-jolie.webp',
    },
    {
        name: 'Anne Hathaway',
        imageUrl: 'people/anne-hathaway.webp',
    },
    {
        name: 'Anne-Lise Heimburger',
        imageUrl: 'people/anne-lise-heimburger.webp',
    },
    {
        name: 'Anya Taylor-Joy',
        imageUrl: 'people/anya-taylor-joy.webp',
    },
    {
        name: 'Brad Pitt',
        imageUrl: 'people/brad-pitt.webp',
    },
    {
        name: 'Charithra Chandran',
        imageUrl: 'people/charithra-chandran.webp',
    },
    {
        name: 'Deng Kai',
        imageUrl: 'people/deng-kai.webp',
    },
    {
        name: 'Elle Chapman',
        imageUrl: 'people/elle-chapman.webp',
    },
    {
        name: 'Elle Fanning',
        imageUrl: 'people/elle-fanning.webp',
    },
    {
        name: 'Emil Hostina',
        imageUrl: 'people/emil-hostina.webp',
    },
    {
        name: 'Emily Rudd',
        imageUrl: 'people/emily-rudd.webp',
    },
    {
        name: 'Emma Stone',
        imageUrl: 'people/emma-stone.webp',
    },
    {
        name: 'Ester Expósito',
        imageUrl: 'people/ester-exposito.webp',
    },
    {
        name: 'Holly Cattle',
        imageUrl: 'people/holly-cattle.webp',
    },
    {
        name: "Jack O'Connell",
        imageUrl: 'people/jack-o-connell.webp',
    },
    {
        name: 'Jackie Chan',
        imageUrl: 'people/jackie-chan.webp',
    },
    {
        name: 'Jacob Elordi',
        imageUrl: 'people/jacob-elordi.webp',
    },
    {
        name: 'Jason Statham',
        imageUrl: 'people/jason-statham.webp',
    },
    {
        name: 'Jenna Ortega',
        imageUrl: 'people/jenna-ortega.webp',
    },
    {
        name: 'Kaori Asô',
        imageUrl: 'people/kaori-aso.webp',
    },
    {
        name: 'Kavya Anil',
        imageUrl: 'people/kavya-anil.webp',
    },
    {
        name: 'Keanu Reeves',
        imageUrl: 'people/keanu-reeves.webp',
    },
    {
        name: 'Kitty de Hoyos',
        imageUrl: 'people/kitty-de-hoyos.webp',
    },
    {
        name: 'Laura Yenga',
        imageUrl: 'people/laura-yenga.webp',
    },
    {
        name: 'Lin Muran',
        imageUrl: 'people/lin-muran.webp',
    },
    {
        name: 'Margot Robbie',
        imageUrl: 'people/margot-robbie.webp',
    },
    {
        name: 'Matt Clark',
        imageUrl: 'people/matt-clark.webp',
    },
    {
        name: 'Mckenna Grace',
        imageUrl: 'people/mckenna-grace.webp',
    },
    {
        name: 'Megan Fox',
        imageUrl: 'people/megan-fox.webp',
    },
    {
        name: 'Michael B. Jordan',
        imageUrl: 'people/michael-b-jordan.webp',
    },
    {
        name: 'Mila Kunis',
        imageUrl: 'people/mila-kunis.webp',
    },
    {
        name: 'Millie Bobby Brown',
        imageUrl: 'people/millie-bobby-brown.webp',
    },
    {
        name: 'Minami Hamabe',
        imageUrl: 'people/minami-hamabe.webp',
    },
    {
        name: 'Pedro Pascal',
        imageUrl: 'people/pedro-pascal.webp',
    },
    {
        name: 'Romina Power',
        imageUrl: 'people/romina-power.webp',
    },
    {
        name: 'Ryan Gosling',
        imageUrl: 'people/ryan-gosling.webp',
    },
    {
        name: 'Sadie Sink',
        imageUrl: 'people/sadie-sink.webp',
    },
    {
        name: 'Sean Penn',
        imageUrl: 'people/sean-penn.webp',
    },
    {
        name: 'Shad Moss',
        imageUrl: 'people/shad-moss.webp',
    },
    {
        name: 'Sydney Sweeney',
        imageUrl: 'people/sydney-sweeney.webp',
    },
    {
        name: 'Timothée Chalamet',
        imageUrl: 'people/timothee-chalamet.webp',
    },
    {
        name: 'Tom Cruise',
        imageUrl: 'people/tom-cruise.webp',
    },
    {
        name: 'Tom Hardy',
        imageUrl: 'people/tom-hardy.webp',
    },
    {
        name: 'Tom Holland',
        imageUrl: 'people/tom-holland.webp',
    },
    {
        name: 'Vin Diesel',
        imageUrl: 'people/vin-diesel.webp',
    },
    {
        name: 'Yui Koike',
        imageUrl: 'people/yui-koike.webp',
    },
    {
        name: 'Zendaya',
        imageUrl: 'people/zendaya.webp',
    },
]
