// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const peopleCharacters: Character[] = [
    {
        name: 'Adam Pearson',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xRDaT60nU48yBDD20A2hSmSALZX.jpg',
    },
    {
        name: 'Alan Ritchson',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/92YNEEpCyugkTzPprJwZpvVtvuK.jpg',
    },
    {
        name: 'Alexandra Daddario',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mP3N1LTIaIG5Q0BHyt1XxjtIyYi.jpg',
    },
    {
        name: 'Amy Madigan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xgtQOuPAmQZXWUO2PXetNpXm08A.jpg',
    },
    {
        name: 'Ana de Armas',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tkBWBvcLTihUcVf6iwbMQTFqEEv.jpg',
    },
    {
        name: 'Anne Hathaway',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nbccV2pMoyLTCeg5DQip24Eq0Jp.jpg',
    },
    {
        name: 'Anne-Lise Heimburger',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tiACLgeJ0omEWIbk6aiR4ScF7la.jpg',
    },
    {
        name: 'Brad Pitt',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cckcYc2v0yh1tc9QjRelptcOBko.jpg',
    },
    {
        name: 'Charithra Chandran',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xLFgJmfXjd2Nnbjx3ZtavReGwjK.jpg',
    },
    {
        name: 'Deng Kai',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cefuRdyIZaVf0jaO5a0agqZWvMC.jpg',
    },
    {
        name: 'Elle Chapman',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mdsFuoFKxeocWYrFYLaV37UdsKb.jpg',
    },
    {
        name: 'Elle Fanning',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/e8CUyxQSE99y5IOfzSLtHC0B0Ch.jpg',
    },
    {
        name: 'Emil Hostina',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yFBZwxGOHnxi8qokkgTIDdwylUn.jpg',
    },
    {
        name: 'Emily Rudd',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/y23GTdDPcryBVtSWjY9q2O9nzwV.jpg',
    },
    {
        name: 'Emma Stone',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/erYRVpgj0XfIOeHXijDBIl2hBgN.jpg',
    },
    {
        name: 'Ester Expósito',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/d6ZbK4k612DHKS7ct66QLHl5hfc.jpg',
    },
    {
        name: 'Holly Cattle',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/36K45CHuO7KHx2id8RFT4XPYGlw.jpg',
    },
    {
        name: 'Ian Somerhalder',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tSrMGbxGYhda5f2870mfTtn9CG7.jpg',
    },
    {
        name: "Jack O'Connell",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9RrqnB1BRaWWHEjlWVVAna0sdBB.jpg',
    },
    {
        name: 'Jackie Chan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg',
    },
    {
        name: 'Jacob Elordi',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qZNRPWCP2c5d0YaYLTzHXU9Rdoe.jpg',
    },
    {
        name: 'Jason Statham',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pXGSq2UpcDE2NMF8LR56QZf5U1q.jpg',
    },
    {
        name: 'Jenna Ortega',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dQb6COORkv8liT5FMtXdHuvjUsb.jpg',
    },
    {
        name: 'Jennifer Runyon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1j0Vt7pUROiNvI4ga0KfsNQnlWc.jpg',
    },
    {
        name: 'Jessie Buckley',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dvgO1rCqxKRqy44Q8zHNj8uvXNk.jpg',
    },
    {
        name: 'Ji Chang-wook',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sBmHrO5Tn27Ot5hy0yAKniROmNb.jpg',
    },
    {
        name: 'Kaori Asô',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/AoAjVf5jNfGPEIQGJL7FKNy05N0.jpg',
    },
    {
        name: 'Kavya Anil',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xDWp5KQtKrgnwYGLY4H6eXabqKW.jpg',
    },
    {
        name: 'Kitty de Hoyos',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oIVIprBuZZU8nIKzMzZ1ORolIG2.jpg',
    },
    {
        name: 'Laura Yenga',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qr6P2QoVSE7rsiRjZVuRSDUNOyJ.jpg',
    },
    {
        name: 'Leonardo DiCaprio',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg',
    },
    {
        name: 'Margot Robbie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8LqG2N6j98lFGMpuYsRUAhOunSd.jpg',
    },
    {
        name: 'Matt Clark',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/n5TJz5CaTqRXLpAOl0wHJXrPQOk.jpg',
    },
    {
        name: 'Megan Fox',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zQp2YM0zbC27Ws97LNbyicysk8p.jpg',
    },
    {
        name: 'Michael B. Jordan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sMBpav8cK7t7Nk0yf4tuNOqNUyW.jpg',
    },
    {
        name: 'Millie Bobby Brown',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/k9KGzGDVhXKfOGpoN62MNuXL28q.jpg',
    },
    {
        name: 'Millie Bobby Brown',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/k9KGzGDVhXKfOGpoN62MNuXL28q.jpg',
    },
    {
        name: 'Minami Hamabe',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eQN8N2chINckvQDiNqzDXI0v9vN.jpg',
    },
    {
        name: 'Ryan Gosling',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg',
    },
    {
        name: 'Scarlett Johansson',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mjReG6rR7NPMEIWb1T4YWtV11ty.jpg',
    },
    {
        name: 'Sean Penn',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9glqNTVpFpdN1nFklKaHPUyCwR6.jpg',
    },
    {
        name: 'Shad Moss',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xsvJmcOQiocYcKtRmfiQbjzVrVw.jpg',
    },
    {
        name: 'Sydney Sweeney',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uDnIdU4KGjQg7liFvb9wnALvg95.jpg',
    },
    {
        name: 'Tian Xiwei',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ci7uOTYUSk4Utg9gHvqVnqCPIUn.jpg',
    },
    {
        name: 'Timothée Chalamet',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dFxpwRpmzpVfP1zjluH68DeQhyj.jpg',
    },
    {
        name: 'Tom Cruise',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/maf8PhSvDCdEwjEMbYfGpojR5RP.jpg',
    },
    {
        name: 'Tom Hanks',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eKF1sGJRrZJbfBG1KirPt1cfNd3.jpg',
    },
    {
        name: 'Vin Diesel',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nZdVry7lnUkE24PnXakok9okvL4.jpg',
    },
    {
        name: 'Yui Koike',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bkxHIit5LI96JkaHRmCfqfUSz0S.jpg',
    },
    {
        name: 'Zhang Linghe',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qJtnyHBnv7t7sNCei2By1CJ9hwL.jpg',
    },
]
