// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const pokemonCharacters: Character[] = [
    {
        name: 'Bulbasaur',
        imageUrl: 'pokemon/bulbasaur.webp',
    },
    {
        name: 'Ivysaur',
        imageUrl: 'pokemon/ivysaur.webp',
    },
    {
        name: 'Venusaur',
        imageUrl: 'pokemon/venusaur.webp',
    },
    {
        name: 'Charmander',
        imageUrl: 'pokemon/charmander.webp',
    },
    {
        name: 'Charmeleon',
        imageUrl: 'pokemon/charmeleon.webp',
    },
    {
        name: 'Charizard',
        imageUrl: 'pokemon/charizard.webp',
    },
    {
        name: 'Squirtle',
        imageUrl: 'pokemon/squirtle.webp',
    },
    {
        name: 'Wartortle',
        imageUrl: 'pokemon/wartortle.webp',
    },
    {
        name: 'Blastoise',
        imageUrl: 'pokemon/blastoise.webp',
    },
    {
        name: 'Caterpie',
        imageUrl: 'pokemon/caterpie.webp',
    },
    {
        name: 'Metapod',
        imageUrl: 'pokemon/metapod.webp',
    },
    {
        name: 'Butterfree',
        imageUrl: 'pokemon/butterfree.webp',
    },
    {
        name: 'Weedle',
        imageUrl: 'pokemon/weedle.webp',
    },
    {
        name: 'Kakuna',
        imageUrl: 'pokemon/kakuna.webp',
    },
    {
        name: 'Beedrill',
        imageUrl: 'pokemon/beedrill.webp',
    },
    {
        name: 'Pidgey',
        imageUrl: 'pokemon/pidgey.webp',
    },
    {
        name: 'Pidgeotto',
        imageUrl: 'pokemon/pidgeotto.webp',
    },
    {
        name: 'Pidgeot',
        imageUrl: 'pokemon/pidgeot.webp',
    },
    {
        name: 'Rattata',
        imageUrl: 'pokemon/rattata.webp',
    },
    {
        name: 'Raticate',
        imageUrl: 'pokemon/raticate.webp',
    },
    {
        name: 'Spearow',
        imageUrl: 'pokemon/spearow.webp',
    },
    {
        name: 'Fearow',
        imageUrl: 'pokemon/fearow.webp',
    },
    {
        name: 'Ekans',
        imageUrl: 'pokemon/ekans.webp',
    },
    {
        name: 'Arbok',
        imageUrl: 'pokemon/arbok.webp',
    },
    {
        name: 'Pikachu',
        imageUrl: 'pokemon/pikachu.webp',
    },
    {
        name: 'Raichu',
        imageUrl: 'pokemon/raichu.webp',
    },
    {
        name: 'Sandshrew',
        imageUrl: 'pokemon/sandshrew.webp',
    },
    {
        name: 'Sandslash',
        imageUrl: 'pokemon/sandslash.webp',
    },
    {
        name: 'Nidoran f',
        imageUrl: 'pokemon/nidoran-f.webp',
    },
    {
        name: 'Nidorina',
        imageUrl: 'pokemon/nidorina.webp',
    },
    {
        name: 'Nidoqueen',
        imageUrl: 'pokemon/nidoqueen.webp',
    },
    {
        name: 'Nidoran m',
        imageUrl: 'pokemon/nidoran-m.webp',
    },
    {
        name: 'Nidorino',
        imageUrl: 'pokemon/nidorino.webp',
    },
    {
        name: 'Nidoking',
        imageUrl: 'pokemon/nidoking.webp',
    },
    {
        name: 'Clefairy',
        imageUrl: 'pokemon/clefairy.webp',
    },
    {
        name: 'Clefable',
        imageUrl: 'pokemon/clefable.webp',
    },
    {
        name: 'Vulpix',
        imageUrl: 'pokemon/vulpix.webp',
    },
    {
        name: 'Ninetales',
        imageUrl: 'pokemon/ninetales.webp',
    },
    {
        name: 'Jigglypuff',
        imageUrl: 'pokemon/jigglypuff.webp',
    },
    {
        name: 'Wigglytuff',
        imageUrl: 'pokemon/wigglytuff.webp',
    },
    {
        name: 'Zubat',
        imageUrl: 'pokemon/zubat.webp',
    },
    {
        name: 'Golbat',
        imageUrl: 'pokemon/golbat.webp',
    },
    {
        name: 'Oddish',
        imageUrl: 'pokemon/oddish.webp',
    },
    {
        name: 'Gloom',
        imageUrl: 'pokemon/gloom.webp',
    },
    {
        name: 'Vileplume',
        imageUrl: 'pokemon/vileplume.webp',
    },
    {
        name: 'Paras',
        imageUrl: 'pokemon/paras.webp',
    },
    {
        name: 'Parasect',
        imageUrl: 'pokemon/parasect.webp',
    },
    {
        name: 'Venonat',
        imageUrl: 'pokemon/venonat.webp',
    },
    {
        name: 'Venomoth',
        imageUrl: 'pokemon/venomoth.webp',
    },
    {
        name: 'Diglett',
        imageUrl: 'pokemon/diglett.webp',
    },
    {
        name: 'Dugtrio',
        imageUrl: 'pokemon/dugtrio.webp',
    },
    {
        name: 'Meowth',
        imageUrl: 'pokemon/meowth.webp',
    },
    {
        name: 'Persian',
        imageUrl: 'pokemon/persian.webp',
    },
    {
        name: 'Psyduck',
        imageUrl: 'pokemon/psyduck.webp',
    },
    {
        name: 'Golduck',
        imageUrl: 'pokemon/golduck.webp',
    },
    {
        name: 'Mankey',
        imageUrl: 'pokemon/mankey.webp',
    },
    {
        name: 'Primeape',
        imageUrl: 'pokemon/primeape.webp',
    },
    {
        name: 'Growlithe',
        imageUrl: 'pokemon/growlithe.webp',
    },
    {
        name: 'Arcanine',
        imageUrl: 'pokemon/arcanine.webp',
    },
    {
        name: 'Poliwag',
        imageUrl: 'pokemon/poliwag.webp',
    },
    {
        name: 'Poliwhirl',
        imageUrl: 'pokemon/poliwhirl.webp',
    },
    {
        name: 'Poliwrath',
        imageUrl: 'pokemon/poliwrath.webp',
    },
    {
        name: 'Abra',
        imageUrl: 'pokemon/abra.webp',
    },
    {
        name: 'Kadabra',
        imageUrl: 'pokemon/kadabra.webp',
    },
    {
        name: 'Alakazam',
        imageUrl: 'pokemon/alakazam.webp',
    },
    {
        name: 'Machop',
        imageUrl: 'pokemon/machop.webp',
    },
    {
        name: 'Machoke',
        imageUrl: 'pokemon/machoke.webp',
    },
    {
        name: 'Machamp',
        imageUrl: 'pokemon/machamp.webp',
    },
    {
        name: 'Bellsprout',
        imageUrl: 'pokemon/bellsprout.webp',
    },
    {
        name: 'Weepinbell',
        imageUrl: 'pokemon/weepinbell.webp',
    },
    {
        name: 'Victreebel',
        imageUrl: 'pokemon/victreebel.webp',
    },
    {
        name: 'Tentacool',
        imageUrl: 'pokemon/tentacool.webp',
    },
    {
        name: 'Tentacruel',
        imageUrl: 'pokemon/tentacruel.webp',
    },
    {
        name: 'Geodude',
        imageUrl: 'pokemon/geodude.webp',
    },
    {
        name: 'Graveler',
        imageUrl: 'pokemon/graveler.webp',
    },
    {
        name: 'Golem',
        imageUrl: 'pokemon/golem.webp',
    },
    {
        name: 'Ponyta',
        imageUrl: 'pokemon/ponyta.webp',
    },
    {
        name: 'Rapidash',
        imageUrl: 'pokemon/rapidash.webp',
    },
    {
        name: 'Slowpoke',
        imageUrl: 'pokemon/slowpoke.webp',
    },
    {
        name: 'Slowbro',
        imageUrl: 'pokemon/slowbro.webp',
    },
    {
        name: 'Magnemite',
        imageUrl: 'pokemon/magnemite.webp',
    },
    {
        name: 'Magneton',
        imageUrl: 'pokemon/magneton.webp',
    },
    {
        name: 'Farfetchd',
        imageUrl: 'pokemon/farfetchd.webp',
    },
    {
        name: 'Doduo',
        imageUrl: 'pokemon/doduo.webp',
    },
    {
        name: 'Dodrio',
        imageUrl: 'pokemon/dodrio.webp',
    },
    {
        name: 'Seel',
        imageUrl: 'pokemon/seel.webp',
    },
    {
        name: 'Dewgong',
        imageUrl: 'pokemon/dewgong.webp',
    },
    {
        name: 'Grimer',
        imageUrl: 'pokemon/grimer.webp',
    },
    {
        name: 'Muk',
        imageUrl: 'pokemon/muk.webp',
    },
    {
        name: 'Shellder',
        imageUrl: 'pokemon/shellder.webp',
    },
    {
        name: 'Cloyster',
        imageUrl: 'pokemon/cloyster.webp',
    },
    {
        name: 'Gastly',
        imageUrl: 'pokemon/gastly.webp',
    },
    {
        name: 'Haunter',
        imageUrl: 'pokemon/haunter.webp',
    },
    {
        name: 'Gengar',
        imageUrl: 'pokemon/gengar.webp',
    },
    {
        name: 'Onix',
        imageUrl: 'pokemon/onix.webp',
    },
    {
        name: 'Drowzee',
        imageUrl: 'pokemon/drowzee.webp',
    },
    {
        name: 'Hypno',
        imageUrl: 'pokemon/hypno.webp',
    },
    {
        name: 'Krabby',
        imageUrl: 'pokemon/krabby.webp',
    },
    {
        name: 'Kingler',
        imageUrl: 'pokemon/kingler.webp',
    },
    {
        name: 'Voltorb',
        imageUrl: 'pokemon/voltorb.webp',
    },
    {
        name: 'Electrode',
        imageUrl: 'pokemon/electrode.webp',
    },
    {
        name: 'Exeggcute',
        imageUrl: 'pokemon/exeggcute.webp',
    },
    {
        name: 'Exeggutor',
        imageUrl: 'pokemon/exeggutor.webp',
    },
    {
        name: 'Cubone',
        imageUrl: 'pokemon/cubone.webp',
    },
    {
        name: 'Marowak',
        imageUrl: 'pokemon/marowak.webp',
    },
    {
        name: 'Hitmonlee',
        imageUrl: 'pokemon/hitmonlee.webp',
    },
    {
        name: 'Hitmonchan',
        imageUrl: 'pokemon/hitmonchan.webp',
    },
    {
        name: 'Lickitung',
        imageUrl: 'pokemon/lickitung.webp',
    },
    {
        name: 'Koffing',
        imageUrl: 'pokemon/koffing.webp',
    },
    {
        name: 'Weezing',
        imageUrl: 'pokemon/weezing.webp',
    },
    {
        name: 'Rhyhorn',
        imageUrl: 'pokemon/rhyhorn.webp',
    },
    {
        name: 'Rhydon',
        imageUrl: 'pokemon/rhydon.webp',
    },
    {
        name: 'Chansey',
        imageUrl: 'pokemon/chansey.webp',
    },
    {
        name: 'Tangela',
        imageUrl: 'pokemon/tangela.webp',
    },
    {
        name: 'Kangaskhan',
        imageUrl: 'pokemon/kangaskhan.webp',
    },
    {
        name: 'Horsea',
        imageUrl: 'pokemon/horsea.webp',
    },
    {
        name: 'Seadra',
        imageUrl: 'pokemon/seadra.webp',
    },
    {
        name: 'Goldeen',
        imageUrl: 'pokemon/goldeen.webp',
    },
    {
        name: 'Seaking',
        imageUrl: 'pokemon/seaking.webp',
    },
    {
        name: 'Staryu',
        imageUrl: 'pokemon/staryu.webp',
    },
    {
        name: 'Starmie',
        imageUrl: 'pokemon/starmie.webp',
    },
    {
        name: 'Mr mime',
        imageUrl: 'pokemon/mr-mime.webp',
    },
    {
        name: 'Scyther',
        imageUrl: 'pokemon/scyther.webp',
    },
    {
        name: 'Jynx',
        imageUrl: 'pokemon/jynx.webp',
    },
    {
        name: 'Electabuzz',
        imageUrl: 'pokemon/electabuzz.webp',
    },
    {
        name: 'Magmar',
        imageUrl: 'pokemon/magmar.webp',
    },
    {
        name: 'Pinsir',
        imageUrl: 'pokemon/pinsir.webp',
    },
    {
        name: 'Tauros',
        imageUrl: 'pokemon/tauros.webp',
    },
    {
        name: 'Magikarp',
        imageUrl: 'pokemon/magikarp.webp',
    },
    {
        name: 'Gyarados',
        imageUrl: 'pokemon/gyarados.webp',
    },
    {
        name: 'Lapras',
        imageUrl: 'pokemon/lapras.webp',
    },
    {
        name: 'Ditto',
        imageUrl: 'pokemon/ditto.webp',
    },
    {
        name: 'Eevee',
        imageUrl: 'pokemon/eevee.webp',
    },
    {
        name: 'Vaporeon',
        imageUrl: 'pokemon/vaporeon.webp',
    },
    {
        name: 'Jolteon',
        imageUrl: 'pokemon/jolteon.webp',
    },
    {
        name: 'Flareon',
        imageUrl: 'pokemon/flareon.webp',
    },
    {
        name: 'Porygon',
        imageUrl: 'pokemon/porygon.webp',
    },
    {
        name: 'Omanyte',
        imageUrl: 'pokemon/omanyte.webp',
    },
    {
        name: 'Omastar',
        imageUrl: 'pokemon/omastar.webp',
    },
    {
        name: 'Kabuto',
        imageUrl: 'pokemon/kabuto.webp',
    },
    {
        name: 'Kabutops',
        imageUrl: 'pokemon/kabutops.webp',
    },
    {
        name: 'Aerodactyl',
        imageUrl: 'pokemon/aerodactyl.webp',
    },
    {
        name: 'Snorlax',
        imageUrl: 'pokemon/snorlax.webp',
    },
    {
        name: 'Articuno',
        imageUrl: 'pokemon/articuno.webp',
    },
    {
        name: 'Zapdos',
        imageUrl: 'pokemon/zapdos.webp',
    },
    {
        name: 'Moltres',
        imageUrl: 'pokemon/moltres.webp',
    },
    {
        name: 'Dratini',
        imageUrl: 'pokemon/dratini.webp',
    },
    {
        name: 'Dragonair',
        imageUrl: 'pokemon/dragonair.webp',
    },
    {
        name: 'Dragonite',
        imageUrl: 'pokemon/dragonite.webp',
    },
    {
        name: 'Mewtwo',
        imageUrl: 'pokemon/mewtwo.webp',
    },
    {
        name: 'Mew',
        imageUrl: 'pokemon/mew.webp',
    },
]
