// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const rickAndMortyCharacters: Character[] = [
    {
        name: 'Aqua Rick',
        imageUrl: 'rick-and-morty/aqua-rick.webp',
    },
    {
        name: 'Arbolian Mentirososian',
        imageUrl: 'rick-and-morty/arbolian-mentirososian.webp',
    },
    {
        name: 'Arcade Alien',
        imageUrl: 'rick-and-morty/arcade-alien.webp',
    },
    {
        name: 'Attila Starwar',
        imageUrl: 'rick-and-morty/attila-starwar.webp',
    },
    {
        name: 'Benjamin',
        imageUrl: 'rick-and-morty/benjamin.webp',
    },
    {
        name: 'Bepisian',
        imageUrl: 'rick-and-morty/bepisian.webp',
    },
    {
        name: 'Beth Smith',
        imageUrl: 'rick-and-morty/beth-smith.webp',
    },
    {
        name: 'Beth Smith',
        imageUrl: 'rick-and-morty/beth-smith-1.webp',
    },
    {
        name: 'Birdperson',
        imageUrl: 'rick-and-morty/birdperson.webp',
    },
    {
        name: 'Brad',
        imageUrl: 'rick-and-morty/brad.webp',
    },
    {
        name: 'Cyclops Rick',
        imageUrl: 'rick-and-morty/cyclops-rick.webp',
    },
    {
        name: 'Cynthia',
        imageUrl: 'rick-and-morty/cynthia.webp',
    },
    {
        name: 'Evil Morty',
        imageUrl: 'rick-and-morty/evil-morty.webp',
    },
    {
        name: 'Flansian',
        imageUrl: 'rick-and-morty/flansian.webp',
    },
    {
        name: 'Fulgora',
        imageUrl: 'rick-and-morty/fulgora.webp',
    },
    {
        name: 'Gar Gloonch',
        imageUrl: 'rick-and-morty/gar-gloonch.webp',
    },
    {
        name: 'Garblovian',
        imageUrl: 'rick-and-morty/garblovian.webp',
    },
    {
        name: 'Greebybobe',
        imageUrl: 'rick-and-morty/greebybobe.webp',
    },
    {
        name: 'Jerry Smith',
        imageUrl: 'rick-and-morty/jerry-smith.webp',
    },
    {
        name: 'Jerry Smith',
        imageUrl: 'rick-and-morty/jerry-smith-1.webp',
    },
    {
        name: 'Jessica',
        imageUrl: 'rick-and-morty/jessica.webp',
    },
    {
        name: 'Jessica',
        imageUrl: 'rick-and-morty/jessica-1.webp',
    },
    {
        name: "Jessica's Friend",
        imageUrl: 'rick-and-morty/jessica-s-friend.webp',
    },
    {
        name: 'Larva Alien',
        imageUrl: 'rick-and-morty/larva-alien.webp',
    },
    {
        name: 'Loggins',
        imageUrl: 'rick-and-morty/loggins.webp',
    },
    {
        name: 'Maximums Rickimus',
        imageUrl: 'rick-and-morty/maximums-rickimus.webp',
    },
    {
        name: 'MC Haps',
        imageUrl: 'rick-and-morty/mc-haps.webp',
    },
    {
        name: 'Morty Smith',
        imageUrl: 'rick-and-morty/morty-smith.webp',
    },
    {
        name: 'Mr. Goldenfold',
        imageUrl: 'rick-and-morty/mr-goldenfold.webp',
    },
    {
        name: 'Mr. Goldenfold',
        imageUrl: 'rick-and-morty/mr-goldenfold-1.webp',
    },
    {
        name: 'Mr. Meeseeks',
        imageUrl: 'rick-and-morty/mr-meeseeks.webp',
    },
    {
        name: 'Mr. Poopybutthole',
        imageUrl: 'rick-and-morty/mr-poopybutthole.webp',
    },
    {
        name: 'Mrs. Sanchez',
        imageUrl: 'rick-and-morty/mrs-sanchez.webp',
    },
    {
        name: 'Nancy',
        imageUrl: 'rick-and-morty/nancy.webp',
    },
    {
        name: 'Phoenixperson',
        imageUrl: 'rick-and-morty/phoenixperson.webp',
    },
    {
        name: 'President Curtis',
        imageUrl: 'rick-and-morty/president-curtis.webp',
    },
    {
        name: 'Principal Vagina',
        imageUrl: 'rick-and-morty/principal-vagina.webp',
    },
    {
        name: 'Principal Vagina',
        imageUrl: 'rick-and-morty/principal-vagina-1.webp',
    },
    {
        name: 'Pripudlian',
        imageUrl: 'rick-and-morty/pripudlian.webp',
    },
    {
        name: 'Quantum Rick',
        imageUrl: 'rick-and-morty/quantum-rick.webp',
    },
    {
        name: 'Revolio Clockberg Jr.',
        imageUrl: 'rick-and-morty/revolio-clockberg-jr.webp',
    },
    {
        name: 'Rick Sanchez',
        imageUrl: 'rick-and-morty/rick-sanchez.webp',
    },
    {
        name: 'Ricktiminus Sancheziminius',
        imageUrl: 'rick-and-morty/ricktiminus-sancheziminius.webp',
    },
    {
        name: 'Riq IV',
        imageUrl: 'rick-and-morty/riq-iv.webp',
    },
    {
        name: 'Scrotian',
        imageUrl: 'rick-and-morty/scrotian.webp',
    },
    {
        name: 'Shimshamian',
        imageUrl: 'rick-and-morty/shimshamian.webp',
    },
    {
        name: 'Snuffles (Snowball)',
        imageUrl: 'rick-and-morty/snuffles-snowball.webp',
    },
    {
        name: 'Squanchy',
        imageUrl: 'rick-and-morty/squanchy.webp',
    },
    {
        name: 'Stair Goblin',
        imageUrl: 'rick-and-morty/stair-goblin.webp',
    },
    {
        name: 'Summer Smith',
        imageUrl: 'rick-and-morty/summer-smith.webp',
    },
    {
        name: 'Summer Smith',
        imageUrl: 'rick-and-morty/summer-smith-1.webp',
    },
    {
        name: 'Tammy Guetermann',
        imageUrl: 'rick-and-morty/tammy-guetermann.webp',
    },
    {
        name: 'Tophat Jones',
        imageUrl: 'rick-and-morty/tophat-jones.webp',
    },
    {
        name: 'Traflorkian',
        imageUrl: 'rick-and-morty/traflorkian.webp',
    },
    {
        name: 'Tricia Lange',
        imageUrl: 'rick-and-morty/tricia-lange.webp',
    },
    {
        name: 'Trunkphobic suspenders guy',
        imageUrl: 'rick-and-morty/trunkphobic-suspenders-guy.webp',
    },
    {
        name: 'Zeta Alpha Rick',
        imageUrl: 'rick-and-morty/zeta-alpha-rick.webp',
    },
]
