// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const rickAndMortyCharacters: Character[] = [
    {
        name: 'Aqua Rick',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/22.jpeg',
    },
    {
        name: 'Arbolian Mentirososian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/454.jpeg',
    },
    {
        name: 'Arcade Alien',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/23.jpeg',
    },
    {
        name: 'Attila Starwar',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/28.jpeg',
    },
    {
        name: 'Benjamin',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/34.jpeg',
    },
    {
        name: 'Bepisian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/35.jpeg',
    },
    {
        name: 'Beth Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    },
    {
        name: 'Beth Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/38.jpeg',
    },
    {
        name: 'Birdperson',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/47.jpeg',
    },
    {
        name: 'Brad',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/58.jpeg',
    },
    {
        name: 'Cyclops Rick',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/86.jpeg',
    },
    {
        name: 'Cynthia',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/88.jpeg',
    },
    {
        name: 'Evil Morty',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/118.jpeg',
    },
    {
        name: 'Flansian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/125.jpeg',
    },
    {
        name: 'Fulgora',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/129.jpeg',
    },
    {
        name: 'Gar Gloonch',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/131.jpeg',
    },
    {
        name: 'Garblovian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/133.jpeg',
    },
    {
        name: 'Greebybobe',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/395.jpeg',
    },
    {
        name: 'Jerry Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    },
    {
        name: 'Jerry Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/175.jpeg',
    },
    {
        name: 'Jessica',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/179.jpeg',
    },
    {
        name: 'Jessica',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/180.jpeg',
    },
    {
        name: "Jessica's Friend",
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/181.jpeg',
    },
    {
        name: 'Larva Alien',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/199.jpeg',
    },
    {
        name: 'Loggins',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/207.jpeg',
    },
    {
        name: 'Maximums Rickimus',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/215.jpeg',
    },
    {
        name: 'MC Haps',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/216.jpeg',
    },
    {
        name: 'Morty Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    },
    {
        name: 'Mr. Goldenfold',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/239.jpeg',
    },
    {
        name: 'Mr. Goldenfold',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/240.jpeg',
    },
    {
        name: 'Mr. Meeseeks',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/242.jpeg',
    },
    {
        name: 'Mr. Poopybutthole',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/244.jpeg',
    },
    {
        name: 'Mrs. Sanchez',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/249.jpeg',
    },
    {
        name: 'Nancy',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/251.jpeg',
    },
    {
        name: 'Phoenixperson',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/592.jpeg',
    },
    {
        name: 'President Curtis',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/347.jpeg',
    },
    {
        name: 'Principal Vagina',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/271.jpeg',
    },
    {
        name: 'Principal Vagina',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/272.jpeg',
    },
    {
        name: 'Pripudlian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/435.jpeg',
    },
    {
        name: 'Quantum Rick',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/274.jpeg',
    },
    {
        name: 'Revolio Clockberg Jr.',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/282.jpeg',
    },
    {
        name: 'Rick Sanchez',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    },
    {
        name: 'Ricktiminus Sancheziminius',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/294.jpeg',
    },
    {
        name: 'Riq IV',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/295.jpeg',
    },
    {
        name: 'Scrotian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/309.jpeg',
    },
    {
        name: 'Shimshamian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/311.jpeg',
    },
    {
        name: 'Snuffles (Snowball)',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/329.jpeg',
    },
    {
        name: 'Squanchy',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/331.jpeg',
    },
    {
        name: 'Stair Goblin',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/333.jpeg',
    },
    {
        name: 'Summer Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    },
    {
        name: 'Summer Smith',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/338.jpeg',
    },
    {
        name: 'Tammy Guetermann',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/344.jpeg',
    },
    {
        name: 'Tophat Jones',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/358.jpeg',
    },
    {
        name: 'Traflorkian',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/362.jpeg',
    },
    {
        name: 'Tricia Lange',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/365.jpeg',
    },
    {
        name: 'Trunkphobic suspenders guy',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/405.jpeg',
    },
    {
        name: 'Zeta Alpha Rick',
        imageUrl: 'https://rickandmortyapi.com/api/character/avatar/389.jpeg',
    },
]
