// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const tvShowCharacters: Character[] = [
    {
        name: '24',
        imageUrl: 'tv-shows/24.webp',
    },
    {
        name: '30 Rock',
        imageUrl: 'tv-shows/30-rock.webp',
    },
    {
        name: '9-1-1',
        imageUrl: 'tv-shows/9-1-1.webp',
    },
    {
        name: 'A Knight of the Seven Kingdoms',
        imageUrl: 'tv-shows/a-knight-of-the-seven-kingdoms.webp',
    },
    {
        name: 'Adventure Time',
        imageUrl: 'tv-shows/adventure-time.webp',
    },
    {
        name: 'American Dad!',
        imageUrl: 'tv-shows/american-dad.webp',
    },
    {
        name: 'American Horror Story',
        imageUrl: 'tv-shows/american-horror-story.webp',
    },
    {
        name: 'Arrow',
        imageUrl: 'tv-shows/arrow.webp',
    },
    {
        name: 'Baywatch',
        imageUrl: 'tv-shows/baywatch.webp',
    },
    {
        name: 'Better Call Saul',
        imageUrl: 'tv-shows/better-call-saul.webp',
    },
    {
        name: 'Black Mirror',
        imageUrl: 'tv-shows/black-mirror.webp',
    },
    {
        name: 'Blue Bloods',
        imageUrl: 'tv-shows/blue-bloods.webp',
    },
    {
        name: 'Bones',
        imageUrl: 'tv-shows/bones.webp',
    },
    {
        name: 'Breaking Bad',
        imageUrl: 'tv-shows/breaking-bad.webp',
    },
    {
        name: 'Bridgerton',
        imageUrl: 'tv-shows/bridgerton.webp',
    },
    {
        name: 'Castle',
        imageUrl: 'tv-shows/castle.webp',
    },
    {
        name: 'Charmed',
        imageUrl: 'tv-shows/charmed.webp',
    },
    {
        name: 'Cheers',
        imageUrl: 'tv-shows/cheers.webp',
    },
    {
        name: 'Chicago Fire',
        imageUrl: 'tv-shows/chicago-fire.webp',
    },
    {
        name: 'Chicago Med',
        imageUrl: 'tv-shows/chicago-med.webp',
    },
    {
        name: 'Chicago P.D.',
        imageUrl: 'tv-shows/chicago-p-d.webp',
    },
    {
        name: 'Chuck',
        imageUrl: 'tv-shows/chuck.webp',
    },
    {
        name: 'Columbo',
        imageUrl: 'tv-shows/columbo.webp',
    },
    {
        name: 'Criminal Minds',
        imageUrl: 'tv-shows/criminal-minds.webp',
    },
    {
        name: 'CSI: Crime Scene Investigation',
        imageUrl: 'tv-shows/csi-crime-scene-investigation.webp',
    },
    {
        name: 'CSI: Miami',
        imageUrl: 'tv-shows/csi-miami.webp',
    },
    {
        name: 'Designated Survivor',
        imageUrl: 'tv-shows/designated-survivor.webp',
    },
    {
        name: 'Desperate Housewives',
        imageUrl: 'tv-shows/desperate-housewives.webp',
    },
    {
        name: 'Dexter',
        imageUrl: 'tv-shows/dexter.webp',
    },
    {
        name: 'Doctor Who',
        imageUrl: 'tv-shows/doctor-who.webp',
    },
    {
        name: 'Elementary',
        imageUrl: 'tv-shows/elementary.webp',
    },
    {
        name: 'Eureka',
        imageUrl: 'tv-shows/eureka.webp',
    },
    {
        name: 'Family Guy',
        imageUrl: 'tv-shows/family-guy.webp',
    },
    {
        name: 'Fargo',
        imageUrl: 'tv-shows/fargo.webp',
    },
    {
        name: 'FBI',
        imageUrl: 'tv-shows/fbi.webp',
    },
    {
        name: 'Frasier',
        imageUrl: 'tv-shows/frasier.webp',
    },
    {
        name: 'Friends',
        imageUrl: 'tv-shows/friends.webp',
    },
    {
        name: 'FROM',
        imageUrl: 'tv-shows/from.webp',
    },
    {
        name: 'Game of Thrones',
        imageUrl: 'tv-shows/game-of-thrones.webp',
    },
    {
        name: 'Gotham',
        imageUrl: 'tv-shows/gotham.webp',
    },
    {
        name: "Grey's Anatomy",
        imageUrl: 'tv-shows/grey-s-anatomy.webp',
    },
    {
        name: 'Grimm',
        imageUrl: 'tv-shows/grimm.webp',
    },
    {
        name: 'Hawaii Five-0',
        imageUrl: 'tv-shows/hawaii-five-0.webp',
    },
    {
        name: 'Heartland',
        imageUrl: 'tv-shows/heartland.webp',
    },
    {
        name: 'Homeland',
        imageUrl: 'tv-shows/homeland.webp',
    },
    {
        name: 'House',
        imageUrl: 'tv-shows/house.webp',
    },
    {
        name: 'How I Met Your Mother',
        imageUrl: 'tv-shows/how-i-met-your-mother.webp',
    },
    {
        name: 'Invincible',
        imageUrl: 'tv-shows/invincible.webp',
    },
    {
        name: 'Law & Order',
        imageUrl: 'tv-shows/law-order.webp',
    },
    {
        name: 'Law & Order: Special Victims Unit',
        imageUrl: 'tv-shows/law-order-special-victims-unit.webp',
    },
    {
        name: 'Lost',
        imageUrl: 'tv-shows/lost.webp',
    },
    {
        name: 'Lucifer',
        imageUrl: 'tv-shows/lucifer.webp',
    },
    {
        name: 'Modern Family',
        imageUrl: 'tv-shows/modern-family.webp',
    },
    {
        name: 'Mom',
        imageUrl: 'tv-shows/mom.webp',
    },
    {
        name: 'Monk',
        imageUrl: 'tv-shows/monk.webp',
    },
    {
        name: 'NCIS',
        imageUrl: 'tv-shows/ncis.webp',
    },
    {
        name: 'NCIS: Los Angeles',
        imageUrl: 'tv-shows/ncis-los-angeles.webp',
    },
    {
        name: 'ONE PIECE',
        imageUrl: 'tv-shows/one-piece.webp',
    },
    {
        name: 'Outlander',
        imageUrl: 'tv-shows/outlander.webp',
    },
    {
        name: 'PAW Patrol',
        imageUrl: 'tv-shows/paw-patrol.webp',
    },
    {
        name: 'Peaky Blinders',
        imageUrl: 'tv-shows/peaky-blinders.webp',
    },
    {
        name: 'Peppa Pig',
        imageUrl: 'tv-shows/peppa-pig.webp',
    },
    {
        name: 'Person of Interest',
        imageUrl: 'tv-shows/person-of-interest.webp',
    },
    {
        name: 'Prison Break',
        imageUrl: 'tv-shows/prison-break.webp',
    },
    {
        name: 'Reacher',
        imageUrl: 'tv-shows/reacher.webp',
    },
    {
        name: 'Regular Show',
        imageUrl: 'tv-shows/regular-show.webp',
    },
    {
        name: 'Rick and Morty',
        imageUrl: 'tv-shows/rick-and-morty.webp',
    },
    {
        name: 'S.W.A.T.',
        imageUrl: 'tv-shows/s-w-a-t.webp',
    },
    {
        name: 'Seinfeld',
        imageUrl: 'tv-shows/seinfeld.webp',
    },
    {
        name: 'Shameless',
        imageUrl: 'tv-shows/shameless.webp',
    },
    {
        name: 'Smallville',
        imageUrl: 'tv-shows/smallville.webp',
    },
    {
        name: 'South Park',
        imageUrl: 'tv-shows/south-park.webp',
    },
    {
        name: 'Star Trek: The Next Generation',
        imageUrl: 'tv-shows/star-trek-the-next-generation.webp',
    },
    {
        name: 'Stargate SG-1',
        imageUrl: 'tv-shows/stargate-sg-1.webp',
    },
    {
        name: 'Stranger Things',
        imageUrl: 'tv-shows/stranger-things.webp',
    },
    {
        name: 'Suits',
        imageUrl: 'tv-shows/suits.webp',
    },
    {
        name: 'Supernatural',
        imageUrl: 'tv-shows/supernatural.webp',
    },
    {
        name: 'The Blacklist',
        imageUrl: 'tv-shows/the-blacklist.webp',
    },
    {
        name: 'The Boys',
        imageUrl: 'tv-shows/the-boys.webp',
    },
    {
        name: 'The Chosen',
        imageUrl: 'tv-shows/the-chosen.webp',
    },
    {
        name: 'The Daily Show',
        imageUrl: 'tv-shows/the-daily-show.webp',
    },
    {
        name: 'The Flash',
        imageUrl: 'tv-shows/the-flash.webp',
    },
    {
        name: 'The Good Doctor',
        imageUrl: 'tv-shows/the-good-doctor.webp',
    },
    {
        name: 'The Good Wife',
        imageUrl: 'tv-shows/the-good-wife.webp',
    },
    {
        name: 'The Mentalist',
        imageUrl: 'tv-shows/the-mentalist.webp',
    },
    {
        name: 'The Office',
        imageUrl: 'tv-shows/the-office.webp',
    },
    {
        name: 'The Pitt',
        imageUrl: 'tv-shows/the-pitt.webp',
    },
    {
        name: 'The Rookie',
        imageUrl: 'tv-shows/the-rookie.webp',
    },
    {
        name: 'The Simpsons',
        imageUrl: 'tv-shows/the-simpsons.webp',
    },
    {
        name: 'The Sopranos',
        imageUrl: 'tv-shows/the-sopranos.webp',
    },
    {
        name: 'The Vampire Diaries',
        imageUrl: 'tv-shows/the-vampire-diaries.webp',
    },
    {
        name: 'The Walking Dead',
        imageUrl: 'tv-shows/the-walking-dead.webp',
    },
    {
        name: 'The Wire',
        imageUrl: 'tv-shows/the-wire.webp',
    },
    {
        name: 'The X-Files',
        imageUrl: 'tv-shows/the-x-files.webp',
    },
    {
        name: 'Two and a Half Men',
        imageUrl: 'tv-shows/two-and-a-half-men.webp',
    },
    {
        name: 'Vikings',
        imageUrl: 'tv-shows/vikings.webp',
    },
    {
        name: 'White Collar',
        imageUrl: 'tv-shows/white-collar.webp',
    },
    {
        name: 'X-Men',
        imageUrl: 'tv-shows/x-men.webp',
    },
    {
        name: 'Yellowstone',
        imageUrl: 'tv-shows/yellowstone.webp',
    },
    {
        name: 'Young Sheldon',
        imageUrl: 'tv-shows/young-sheldon.webp',
    },
]
