// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const tvShowCharacters: Character[] = [
    {
        name: '30 Rock',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eYYQWACx7ttUzRwTNYuo6zveqpE.jpg',
    },
    {
        name: '7de Laan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vQcC4Kcx0ZEXxmj0gUrfkFR14LU.jpg',
    },
    {
        name: 'American Dad!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eb9sH2am9IUSQ8GhXTNAVoujk8W.jpg',
    },
    {
        name: 'Among Friends',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kBBbSgNchtMvsgD6z1oI1RRluHP.jpg',
    },
    {
        name: 'Baywatch',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/34t8WxHn1OcIVpcTxmjYmjX9tE4.jpg',
    },
    {
        name: 'Baywatch',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/34t8WxHn1OcIVpcTxmjYmjX9tE4.jpg',
    },
    {
        name: 'Binnelanders',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3bzECfllho8PphdYujLUIuhncJD.jpg',
    },
    {
        name: 'Body Language',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/u6BQZJpidQLN4YkPCYaXyL07EOu.jpg',
    },
    {
        name: 'Bones',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/eyTu5c8LniVciRZIOSHTvvkkgJa.jpg',
    },
    {
        name: 'Breaking Bad',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    },
    {
        name: 'C.I.D.',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3UymnlLfLMKxG8OcFhSnAlnhQfZ.jpg',
    },
    {
        name: 'Cheers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nD1ZQBKbgKSmKcrAkWTofohsScj.jpg',
    },
    {
        name: 'Chicago Fire',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/r915sk2JpthZSjHEgZKifWxgo6L.jpg',
    },
    {
        name: 'Chuck',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/vEZvGVVMjk1TRs59nfypTI5lAXj.jpg',
    },
    {
        name: 'Conan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oQxrvUhP3ycwnlxIrIMQ9Z3kleq.jpg',
    },
    {
        name: 'Coronation Street',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5x1HXqYqPyYw7oc7Isu1lvVmwRP.jpg',
    },
    {
        name: 'Criminal Minds',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gigxjNnACiXAfrwoMox5WJFgc0I.jpg',
    },
    {
        name: 'CSI: Crime Scene Investigation',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/i5hmoRjHNWady4AtAGICTUXknKH.jpg',
    },
    {
        name: 'CSI: Miami',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pNW64pjaHvf6purNaFhq4SHYRfl.jpg',
    },
    {
        name: 'Desperate Housewives',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4qeI51jDzH81PpUUNaJCBrfm7f6.jpg',
    },
    {
        name: 'Doctor Who',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/w8enSKCf6Zm0topeQ2XPccDqsqp.jpg',
    },
    {
        name: 'Doraemon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9ZN1P32SHviL3SV51qLivxycvcx.jpg',
    },
    {
        name: 'EastEnders',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/z4jgyI5TpoRZiJTNchkVkMrGQyz.jpg',
    },
    {
        name: 'Eureka',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/f2l5hUk63hPqYTucnFy2HmElFV0.jpg',
    },
    {
        name: 'Family Guy',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3PFsEuAiyLkWsP4GG6dIV37Q6gu.jpg',
    },
    {
        name: 'Family Matters',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lIIPV3te2mxBQBHw2rfhwkUYsHf.jpg',
    },
    {
        name: 'FBI',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zfKS4WL0OZ9udpNoSYZw91VB3aH.jpg',
    },
    {
        name: 'Frasier',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gYAb6GCVEFsU9hzMCG5rxaxoIv3.jpg',
    },
    {
        name: 'Friends',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg',
    },
    {
        name: 'Fuse',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9hdEulzIzfj0M2JBKRRIxWOBXUY.jpg',
    },
    {
        name: 'Game of Thrones',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    },
    {
        name: 'Goede Tijden, Slechte Tijden',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/p1oXgtJ0q0wAcEp3tHA5DpiynxL.jpg',
    },
    {
        name: 'Good Mythical Morning',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jMpBQr2aNOFAI6wsC47zsOG6qOh.jpg',
    },
    {
        name: 'Government Job',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sceVlRK5RvnU1qjNipyWDHQXB7x.jpg',
    },
    {
        name: "Grey's Anatomy",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hjJkrLXhWvGHpLeLBDFznpBTY1S.jpg',
    },
    {
        name: 'Gute Zeiten, schlechte Zeiten',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qujVFLAlBnPU9mZElV4NZgL8iXT.jpg',
    },
    {
        name: 'Heartland',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uc2gtWczT58BiAUJWFz9P5aZmNF.jpg',
    },
    {
        name: "HK 80's",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6IpuLrhh7XZfIvz0OmFOSJdSORe.jpg',
    },
    {
        name: 'Horizon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uX8pic7asQBdnwMB9QjPvTsn1Dw.jpg',
    },
    {
        name: 'House',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3Cz7ySOQJmqiuTdrc6CY0r65yDI.jpg',
    },
    {
        name: 'Infinite Challenge',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3ZIPTvMnzI5ThmdGeEYQFxJV5Sg.jpg',
    },
    {
        name: 'JUJUTSU KAISEN',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg',
    },
    {
        name: 'Kamen Rider',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lv3OlrXyTNg4Dz0JrtopOmMziNs.jpg',
    },
    {
        name: 'Knots Landing',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ohcRf8CyVpQiUw2ZTmGQ2I4fH8D.jpg',
    },
    {
        name: 'La Revuelta',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4uaguchJwBK0bl4zjluU6af8J7V.jpg',
    },
    {
        name: 'Late Night with Seth Meyers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jm95V8XjfvqmEhw0MN09wbg9Mi3.jpg',
    },
    {
        name: 'Late Show with David Letterman',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3wzEg2MknkM5AGytRrb1DRife6F.jpg',
    },
    {
        name: 'Law & Order',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/haJ9eHytVO3H3JooMJG1DiWwDNm.jpg',
    },
    {
        name: 'Law & Order: Special Victims Unit',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iofokHZoUB4Qhik4PflvJl8TT6a.jpg',
    },
    {
        name: 'Lost',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg',
    },
    {
        name: 'Lost',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg',
    },
    {
        name: 'Men on a Mission',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2jIi55JtYKJTL1km8qHMuUilOWo.jpg',
    },
    {
        name: 'Midsomer Murders',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pz7tsWxe0TTdfJnWPjZAEnrSl5M.jpg',
    },
    {
        name: 'Modern Family',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/k5Qg5rgPoKdh3yTJJrLtyoyYGwC.jpg',
    },
    {
        name: 'Modern Family',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/k5Qg5rgPoKdh3yTJJrLtyoyYGwC.jpg',
    },
    {
        name: 'NCIS',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mBcu8d6x6zB1el3MPNl7cZQEQ31.jpg',
    },
    {
        name: 'Obake no Q-tarō',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/acb9g0rlsFhy3LBPDvMF7Tso9Q0.jpg',
    },
    {
        name: 'ONE PIECE',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/blWCPEqDGLBuLB9u89CxP9ORQP4.jpg',
    },
    {
        name: 'Outlander',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bxBmfyzK0ARF9hqf2pbFWsddH14.jpg',
    },
    {
        name: 'PAW Patrol',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8HXkgUBO5OF8ZK9XbY69RM4S5rv.jpg',
    },
    {
        name: 'Pili',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sBVfyRYPmKSARRTodsTbwHqgcRA.jpg',
    },
    {
        name: 'Pili',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sBVfyRYPmKSARRTodsTbwHqgcRA.jpg',
    },
    {
        name: 'Radio Star',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uRUZDsvUfIP3JUEgOC8ReBlQQUU.jpg',
    },
    {
        name: 'Raw',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pv5WNnLUo7mpT8k901Lo8UovrqI.jpg',
    },
    {
        name: 'Running Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2Wmmu1MkqxJ48J7aySET9EKEjXz.jpg',
    },
    {
        name: 'Scarpetta',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zvkcHCJUPqv7R9ukaiDNkm75jy.jpg',
    },
    {
        name: 'Sea Hunt',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5aSZlCZ0zEvww83kmFFxlbCElPf.jpg',
    },
    {
        name: 'Secret Lives',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ugYAGyxwajuplDUUYT8Bzbj8eNR.jpg',
    },
    {
        name: 'Sesame Street',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/14k9BfZ2p4rQBMeJ5crKTfUZVwD.jpg',
    },
    {
        name: 'Shameless',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ifo31fMWLmyOVpdak9K0kY4jldQ.jpg',
    },
    {
        name: 'Shortland Street',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7T7TphnK6yvz9J5sMbJ5UyquYWK.jpg',
    },
    {
        name: 'Smallville',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mHZSq8LA5Dt48JjaOZ5tcPXQRVN.jpg',
    },
    {
        name: 'Stargate SG-1',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dQjmI7XxI47v8IM2MUysHG0LuU2.jpg',
    },
    {
        name: 'Stranger Things',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
    },
    {
        name: 'Supernatural',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/u40gJarLPlIkwouKlzGdobQOV9k.jpg',
    },
    {
        name: 'Tagesschau',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg',
    },
    {
        name: 'The Blacklist',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4HTfd1PhgFUenJxVuBDNdLmdr0c.jpg',
    },
    {
        name: 'The Chosen',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
    },
    {
        name: 'The Daily Show',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ixcfyK7it6FjRM36Te4OdblAq4X.jpg',
    },
    {
        name: 'The Flash',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/yZevl2vHQgmosfwUdVNzviIfaWS.jpg',
    },
    {
        name: 'The Goldbergs',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3aQipkhSCHUmaHjImqEqT80k6GP.jpg',
    },
    {
        name: 'The Late Late Show with Craig Ferguson',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg',
    },
    {
        name: 'The Late Show with Stephen Colbert',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg',
    },
    {
        name: 'The Mentalist',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/acYXu4KaDj1NIkMgObnhe4C4a0T.jpg',
    },
    {
        name: 'The Office',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
    },
    {
        name: 'The Pitt',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
    },
    {
        name: 'The Rookie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/70kTz0OmjjZe7zHvIDrq2iKW7PJ.jpg',
    },
    {
        name: 'The Simpsons',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uWpG7GqfKGQqX4YMAo3nv5OrglV.jpg',
    },
    {
        name: 'The Sopranos',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg',
    },
    {
        name: 'The Talk',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7sizkzLu7RNowjfojv6eUn2tAzA.jpg',
    },
    {
        name: 'The Tonight Show Starring Jimmy Fallon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1N4o5PmmqhlVDrcdJ2RlCFWbLGX.jpg',
    },
    {
        name: 'The Tonight Show Starring Johnny Carson',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uSvET5YUvHNDIeoCpErrbSmasFb.jpg',
    },
    {
        name: 'The Waltons',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/51HX9eNn5ZPjRIngDvnk4KzFb1a.jpg',
    },
    {
        name: 'The Wire',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg',
    },
    {
        name: 'The X-Files',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rcBx0p8h51LHceyhquYMxbspJQu.jpg',
    },
    {
        name: 'The X-Files',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rcBx0p8h51LHceyhquYMxbspJQu.jpg',
    },
    {
        name: 'Watch What Happens Live with Andy Cohen',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg',
    },
    {
        name: 'Will Trent',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qG5O46gUxxYGImld03tl2zLhvrg.jpg',
    },
    {
        name: 'Young Hearts',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bF24r2FxsjzgkJcrbBU8RC9JVoU.jpg',
    },
    {
        name: 'Young Sheldon',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kidkbZRBGbsEIrX7pODRSKi9ipl.jpg',
    },
]
