// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const tvShowCharacters: Character[] = [
    {
        name: '31 Minutes',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rI0hXEJFcgRaigCWGEuqEXQvOjY.jpg',
    },
    {
        name: 'Adventure Time: Fionna and Cake',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fi1b6U1kp73xheECzqwzMn8u3mX.jpg',
    },
    {
        name: 'Alchemy of Souls',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gvOZN1NlAoL8iz9ghpES1zWA3w3.jpg',
    },
    {
        name: 'Amphibia',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bFCgv9iWZECWSDxNQYc9soqvwjx.jpg',
    },
    {
        name: 'Anne with an E',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg',
    },
    {
        name: 'Arcane',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    },
    {
        name: 'Attack on Titan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    },
    {
        name: 'Avatar: The Last Airbender',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/v2vn1coUMPKw0GI1KGC5J4IXtqp.jpg',
    },
    {
        name: 'Banana Fish',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/d2TW5Rtd0uCasHlQygsDfWCROl2.jpg',
    },
    {
        name: 'Band of Brothers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8JMXquNmdMUy2n2RgW8gfOM0O3l.jpg',
    },
    {
        name: 'Batman: The Animated Series',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/lBomQFW1vlm1yUYMNSbFZ45R4Ox.jpg',
    },
    {
        name: 'Better Call Saul',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg',
    },
    {
        name: 'Big Time Rush',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/34y5JjZYj2paoxA0RXEppU5LRpb.jpg',
    },
    {
        name: 'Blue Planet II',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/j1NsoYYDYHnPkRr7Enqr8tlexgO.jpg',
    },
    {
        name: 'Bluey',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/b9mY0X5T20ZM073hoa5n0dgmbfN.jpg',
    },
    {
        name: 'BoJack Horseman',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6JFWzlChcGgLiIUo2COgNlWGFKy.jpg',
    },
    {
        name: 'Bon Appétit, Your Majesty',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bzYSIw9FTzQXUcWsnDSwlcwok3C.jpg',
    },
    {
        name: 'Boris',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iR7ufink0F23Wx19SetKaYqhjAZ.jpg',
    },
    {
        name: 'Breaking Bad',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    },
    {
        name: 'Cardcaptor Sakura',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dj0uI34MOkZMTE233tfRebs0YYx.jpg',
    },
    {
        name: 'Chernobyl',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
    },
    {
        name: 'Cosmos: A Personal Voyage',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/nOGArjE0WMkzY2GW1taJm8l9gxD.jpg',
    },
    {
        name: 'Crash Landing on You',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fgBNLPr6mC8pxuR79ENAJY4nBmj.jpg',
    },
    {
        name: 'Dan Da Dan',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/6qfZAOEUFIrbUH3JvePclx1nXzz.jpg',
    },
    {
        name: 'Death Note',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg',
    },
    {
        name: 'Demon Slayer: Kimetsu no Yaiba',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    },
    {
        name: 'Desafío Champions Sendokai',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/8dBMIQ2r8FdLABrZeGklAUAUYCH.jpg',
    },
    {
        name: 'Dexter: Resurrection',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kEHZfSZhZKDot4wqurgIzMUNq1W.jpg',
    },
    {
        name: 'Digimon Tamers',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uEs5GRuibXsSnAH2Hr0DiWupyzb.jpg',
    },
    {
        name: 'Dororo',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/2qSzgSE80OFrfgg5UFYbATdCQ6t.jpg',
    },
    {
        name: 'Dr. STONE',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ve1Sv3sVArmE0nlFjzadcNv1G8r.jpg',
    },
    {
        name: 'Fighting Spirit',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1LApB9C9kEkh2ZU2vzAhurNDipl.jpg',
    },
    {
        name: "Frieren: Beyond Journey's End",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
    },
    {
        name: 'Fullmetal Alchemist: Brotherhood',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
    },
    {
        name: 'Gachiakuta',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jH78nLFrTU6aP7hY7KO6DZHFLoX.jpg',
    },
    {
        name: 'Generator Rex',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fL7S22SWWOjJTgHEkk68VZ4Z8RO.jpg',
    },
    {
        name: 'given',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ul28sT3vNUDjhH24BDkqJ7gGof6.jpg',
    },
    {
        name: 'Goblin',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/sPkxHNw5BFvuCFGWw825TS7n6X3.jpg',
    },
    {
        name: 'Gravity Falls',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/my3IKg5kSCn1Swf07hewcZKJS3K.jpg',
    },
    {
        name: 'Haikyu!!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rBXEmHQaYoIAyOWRpu8v3cBGKcT.jpg',
    },
    {
        name: 'Hazbin Hotel',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aVYHMW8pdzJ9qG1OGRMKyGy9xor.jpg',
    },
    {
        name: 'Heartstopper',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wJJt1HG62h3WoGnLcRIbO2nNNkg.jpg',
    },
    {
        name: 'Heated Rivalry',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
    },
    {
        name: 'High School DxD',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5a9vaaLDAZTYjgfWIw7ZYhL1m1A.jpg',
    },
    {
        name: 'House',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/3Cz7ySOQJmqiuTdrc6CY0r65yDI.jpg',
    },
    {
        name: 'Hunter x Hunter',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/i2EEr2uBvRlAwJ8d8zTG2Y19mIa.jpg',
    },
    {
        name: 'I Am Not an Animal',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/zXhtWhYtlJVyyp5MdT7ggMJn5si.jpg',
    },
    {
        name: "I'm in the Band",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/cHTj9R311yylFlszfpQ0tk7Gpkh.jpg',
    },
    {
        name: 'InuYasha',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/jgvW9n0EwKtq9nbztWhyTvvoqjS.jpg',
    },
    {
        name: 'Invincible',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4tblBrslcKSifMVZ3TmtT2ukMor.jpg',
    },
    {
        name: "JoJo's Bizarre Adventure",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/ogAWwbh3frWtiTyyXrZaVFtqCgp.jpg',
    },
    {
        name: 'JUJUTSU KAISEN',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg',
    },
    {
        name: 'Kaguya-sama: Love Is War',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5khbC6AuNgnvnoDbjIMKCOhEtIc.jpg',
    },
    {
        name: 'Kamisama Kiss',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/5E7GL8KxpFemEFl3Lv8Fu4RuSwa.jpg',
    },
    {
        name: "KONOSUBA - God's blessing on this wonderful world!",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/oRaOeQlwktbGSd2T31FYAcgHZlh.jpg',
    },
    {
        name: 'Les Contes de la rue Broca',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mhuHrLGcWyqetfDjBkbebgw0mUI.jpg',
    },
    {
        name: 'Love, Victor',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pcT1vivabBnBk0tZgVBO1I8aK75.jpg',
    },
    {
        name: 'Lovely Runner',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/xJQyrif5M4UMoVBrBlwUabtaRxB.jpg',
    },
    {
        name: 'Merlí',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/wQaGnuwIHhmB1jgY6CM3rJgScYR.jpg',
    },
    {
        name: 'Mr. Queen',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aekZ1Mk3ROB19DDFNoSt5dcXoUQ.jpg',
    },
    {
        name: 'Mushoku Tensei: Jobless Reincarnation',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gLKOYIMyKlUHW0SVdskhgf9C0yy.jpg',
    },
    {
        name: 'My Hero Academia',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg',
    },
    {
        name: 'Naruto Shippūden',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/71mASgFgSiPl9QUexVH8BubU0lD.jpg',
    },
    {
        name: 'Navillera',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/pBd6pEhszsWk95TrUqo4bdXhH8T.jpg',
    },
    {
        name: 'Neon Genesis Evangelion',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/y2ah9t0navXyIvoHg1uIbIHO3tt.jpg',
    },
    {
        name: 'Once',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/d4vPg3QsTJJh6C5MHARTb5CyqOu.jpg',
    },
    {
        name: 'One Piece',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uiIB9ctqZFbfRXXimtpmZb5dusi.jpg',
    },
    {
        name: 'Over the Garden Wall',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/m3lU8n7WxzMecxKZcqhq5y5ESy.jpg',
    },
    {
        name: 'Planet Earth',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/bNcNxUtZ520d5de5s78onoiSiwQ.jpg',
    },
    {
        name: 'Planet Earth II',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/tUKomxy50suT4MyxjYfOJDkZUq3.jpg',
    },
    {
        name: 'Primal',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mf12pRakr3eYdJtv6klQtoznnbU.jpg',
    },
    {
        name: 'Ranma ½',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/qb1R5iLZcjIgdDIfXFQXmJadQPI.jpg',
    },
    {
        name: 'Regular Show',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mS5SLxMYcKfUxA0utBSR5MOAWWr.jpg',
    },
    {
        name: 'Rick and Morty',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/WGRQ8FpjkDTzivQJ43t94bOuY0.jpg',
    },
    {
        name: 'Run BTS!',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/guNo600nrTIIh88C9i6HFlCAhE.jpg',
    },
    {
        name: 'Rurouni Kenshin',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/iP6i2AJGkxSugByBRrxNd2Goey8.jpg',
    },
    {
        name: 'Scissor Seven',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/mSLSrOndwNoompAARPHBaxF2E6E.jpg',
    },
    {
        name: 'Shadow Hunter',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hOTaiR2qRDZtHgR2Kwz7RcAVqA6.jpg',
    },
    {
        name: 'Slam Dunk',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/gpkM8VeiYyQuEg9qkAoNplktwe4.jpg',
    },
    {
        name: 'Solo Leveling',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
    },
    {
        name: 'Stranger Things',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
    },
    {
        name: 'The Amazing World of Gumball',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/VYnnyA2hyxi3VUPgCA71mMtt69.jpg',
    },
    {
        name: 'The Apothecary Diaries',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/e3ojpANrFnmJCyeBNTinYwyBCIN.jpg',
    },
    {
        name: "The Boy's Word: Blood on the Asphalt",
        imageUrl:
            'https://image.tmdb.org/t/p/w500/fmJ2vVzaSAPvCqB79H70uMHSNr4.jpg',
    },
    {
        name: 'The Chosen',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
    },
    {
        name: 'The Office',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
    },
    {
        name: 'The Originals',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/keJOhJXGiLL54EW6QocbyvQGquA.jpg',
    },
    {
        name: 'The Owl House',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rhzwpJBhi2WkfihXndS1xUdQlzB.jpg',
    },
    {
        name: 'The Pitt',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
    },
    {
        name: 'The Rookie',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/70kTz0OmjjZe7zHvIDrq2iKW7PJ.jpg',
    },
    {
        name: 'The Sopranos',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg',
    },
    {
        name: 'The Spectacular Spider-Man',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/dCNxOhXT7c4lqYuRpdM3m8s9XDp.jpg',
    },
    {
        name: 'The Wire',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg',
    },
    {
        name: 'Toilet-Bound Hanako-kun',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/h1X1G8Q9Ba9Vy1YIgXHduenP8nv.jpg',
    },
    {
        name: 'Villainous',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/uKtxJqOeB74Lm6ZNCyEqMaFlXbp.jpg',
    },
    {
        name: 'Weak Hero',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/hS9VVF5ffTVWNoC9B48QNsZFGy9.jpg',
    },
    {
        name: 'When Life Gives You Tangerines',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
    },
    {
        name: 'Wizards of Waverly Place',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/spVI8Zns4Ep30zzxcoO7f7nwfck.jpg',
    },
    {
        name: 'Your Lie in April',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/rRjfH3ckTYz8z8aSkJshFL4VyK9.jpg',
    },
    {
        name: 'Zoids: Chaotic Century',
        imageUrl:
            'https://image.tmdb.org/t/p/w500/aVGuBvoBr9ujme4uUkAIRYk5vlt.jpg',
    },
]
