// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

export const valorantCharacters: Character[] = [
    {
        name: 'Astra',
        imageUrl: 'valorant/astra.webp',
    },
    {
        name: 'Breach',
        imageUrl: 'valorant/breach.webp',
    },
    {
        name: 'Brimstone',
        imageUrl: 'valorant/brimstone.webp',
    },
    {
        name: 'Chamber',
        imageUrl: 'valorant/chamber.webp',
    },
    {
        name: 'Clove',
        imageUrl: 'valorant/clove.webp',
    },
    {
        name: 'Cypher',
        imageUrl: 'valorant/cypher.webp',
    },
    {
        name: 'Deadlock',
        imageUrl: 'valorant/deadlock.webp',
    },
    {
        name: 'Fade',
        imageUrl: 'valorant/fade.webp',
    },
    {
        name: 'Gekko',
        imageUrl: 'valorant/gekko.webp',
    },
    {
        name: 'Harbor',
        imageUrl: 'valorant/harbor.webp',
    },
    {
        name: 'Iso',
        imageUrl: 'valorant/iso.webp',
    },
    {
        name: 'Jett',
        imageUrl: 'valorant/jett.webp',
    },
    {
        name: 'KAY/O',
        imageUrl: 'valorant/kay-o.webp',
    },
    {
        name: 'Killjoy',
        imageUrl: 'valorant/killjoy.webp',
    },
    {
        name: 'Miks',
        imageUrl: 'valorant/miks.webp',
    },
    {
        name: 'Neon',
        imageUrl: 'valorant/neon.webp',
    },
    {
        name: 'Omen',
        imageUrl: 'valorant/omen.webp',
    },
    {
        name: 'Phoenix',
        imageUrl: 'valorant/phoenix.webp',
    },
    {
        name: 'Raze',
        imageUrl: 'valorant/raze.webp',
    },
    {
        name: 'Reyna',
        imageUrl: 'valorant/reyna.webp',
    },
    {
        name: 'Sage',
        imageUrl: 'valorant/sage.webp',
    },
    {
        name: 'Skye',
        imageUrl: 'valorant/skye.webp',
    },
    {
        name: 'Sova',
        imageUrl: 'valorant/sova.webp',
    },
    {
        name: 'Tejo',
        imageUrl: 'valorant/tejo.webp',
    },
    {
        name: 'Veto',
        imageUrl: 'valorant/veto.webp',
    },
    {
        name: 'Viper',
        imageUrl: 'valorant/viper.webp',
    },
    {
        name: 'Vyse',
        imageUrl: 'valorant/vyse.webp',
    },
    {
        name: 'Waylay',
        imageUrl: 'valorant/waylay.webp',
    },
    {
        name: 'Yoru',
        imageUrl: 'valorant/yoru.webp',
    },
]
