import { writeFileSync } from 'fs'
import { join } from 'path'

const OUT_DIR = join(import.meta.dir, '../src/data/characters')

const header = `// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

`

const PRINT_WIDTH = 80

function serializeString(s: string): string {
    if (s.includes("'")) return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
    return `'${s.replace(/\\/g, '\\\\')}'`
}

function serialize(chars: { name: string; imageUrl: string }[]): string {
    const items = chars.map(({ name, imageUrl }) => {
        const nameStr = serializeString(name)
        const urlStr = serializeString(imageUrl)
        const urlLine = `        imageUrl: ${urlStr},`
        const urlFormatted =
            urlLine.length > PRINT_WIDTH
                ? `        imageUrl:\n            ${urlStr},`
                : urlLine
        return `    {\n        name: ${nameStr},\n${urlFormatted}\n    }`
    })
    return `[\n${items.join(',\n')},\n]`
}

async function fetchLol(): Promise<string> {
    const versions: string[] = await fetch(
        'https://ddragon.leagueoflegends.com/api/versions.json',
    ).then((r) => r.json())

    const version = versions[0]
    const data = await fetch(
        `https://ddragon.leagueoflegends.com/cdn/${version}/data/en_US/champion.json`,
    ).then((r) => r.json())

    const champions = Object.values(data.data as Record<string, { name: string; id: string }>)
        .map(({ name, id }) => ({
            name,
            imageUrl: `https://ddragon.leagueoflegends.com/cdn/${version}/img/champion/${id}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`LoL: ${champions.length} champions (v${version})`)
    return (
        header +
        `export const leagueOfLegendsCharacters: Character[] = ${serialize(champions)}\n`
    )
}

async function fetchDota2(): Promise<string> {
    const heroes: { localized_name: string; name: string }[] = await fetch(
        'https://api.opendota.com/api/heroes',
    ).then((r) => r.json())

    const characters = heroes
        .map(({ localized_name, name }) => ({
            name: localized_name,
            imageUrl: `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${name.replace('npc_dota_hero_', '')}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Dota 2: ${characters.length} heroes`)
    return (
        header + `export const dota2Characters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchValorant(): Promise<string> {
    const data = await fetch(
        'https://valorant-api.com/v1/agents?isPlayableCharacter=true',
    ).then((r) => r.json())

    const characters = (data.data as { displayName: string; uuid: string }[])
        .map(({ displayName, uuid }) => ({
            name: displayName,
            imageUrl: `https://media.valorant-api.com/agents/${uuid}/displayicon.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Valorant: ${characters.length} agents`)
    return (
        header + `export const valorantCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchFlags(): Promise<string> {
    const codes: Record<string, string> = await fetch(
        'https://flagcdn.com/en/codes.json',
    ).then((r) => r.json())

    const exclude = new Set([
        'ac', 'cp', 'dg', 'ea', 'eu', 'hm', 'ic', 'sh', 'sj', 'ta', 'un',
        'xk', 'bv', 'aq', 'tf', 'gs', 'io', 'um',
    ])

    const characters = Object.entries(codes)
        .filter(([code]) => code.length === 2 && !exclude.has(code))
        .map(([code, name]) => ({
            name,
            imageUrl: `https://flagcdn.com/w1280/${code}.webp`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Flags: ${characters.length} countries`)
    return (
        header + `export const flagCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchPokemon(): Promise<string> {
    const data = await fetch(
        'https://pokeapi.co/api/v2/pokemon?limit=1025',
    ).then((r) => r.json())

    const characters = (data.results as { name: string; url: string }[])
        .slice(0, 151)
        .map(({ name, url }) => {
            const id = url.split('/').filter(Boolean).pop()!
            return {
                name: name.charAt(0).toUpperCase() + name.slice(1).replace(/-/g, ' '),
                imageUrl: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`,
            }
        })

    console.log(`Pokémon: ${characters.length} pokémon`)
    return (
        header + `export const pokemonCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchFortnite(): Promise<string> {
    const data = await fetch(
        'https://fortnite-api.com/v2/cosmetics/br?language=en',
    ).then((r) => r.json())

    const characters = (
        data.data as {
            name: string
            type: { value: string }
            rarity: { value: string }
            images: { icon?: string; featured?: string }
        }[]
    )
        .filter(
            (x) =>
                x.type?.value === 'outfit' &&
                x.rarity?.value === 'legendary' &&
                x.images?.featured,
        )
        .map(({ name, images }) => ({
            name,
            imageUrl: images.featured!,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Fortnite: ${characters.length} outfits`)
    return (
        header + `export const fortniteCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchGenshin(): Promise<string> {
    const data = await fetch('https://gi.yatta.moe/api/v2/en/avatar').then((r) => r.json())

    const characters = Object.values(
        data.data.items as Record<string, { name: string; icon: string }>,
    )
        .map(({ name, icon }) => ({
            name,
            imageUrl: `https://gi.yatta.moe/assets/UI/${icon}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Genshin Impact: ${characters.length} characters`)
    return (
        header + `export const genshinCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchRickAndMorty(): Promise<string> {
    const first = await fetch('https://rickandmortyapi.com/api/character').then((r) => r.json())
    const pages: number = first.info.pages

    const results = [...first.results]
    await Promise.all(
        Array.from({ length: pages - 1 }, (_, i) =>
            fetch(`https://rickandmortyapi.com/api/character?page=${i + 2}`)
                .then((r) => r.json())
                .then((d) => results.push(...d.results)),
        ),
    )

    const characters = (results as { name: string; image: string; episode: string[] }[])
        .filter((c) => c.episode.length >= 3)
        .map(({ name, image }) => ({ name, imageUrl: image }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Rick & Morty: ${characters.length} characters`)
    return (
        header +
        `export const rickAndMortyCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchOverwatch(): Promise<string> {
    const data = await fetch('https://overfast-api.tekrop.fr/heroes').then((r) => r.json())

    const characters = (data as { name: string; portrait: string }[])
        .map(({ name, portrait }) => ({ name, imageUrl: portrait }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Overwatch: ${characters.length} heroes`)
    return (
        header + `export const overwatchCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchDragonBall(): Promise<string> {
    const data = await fetch(
        'https://dragonball-api.com/api/characters?limit=100',
    ).then((r) => r.json())

    const characters = (data.items as { name: string; image: string }[])
        .map(({ name, image }) => ({ name, imageUrl: image }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Dragon Ball: ${characters.length} characters`)
    return (
        header + `export const dragonBallCharacters: Character[] = ${serialize(characters)}\n`
    )
}

type TmdbItem = { title?: string; name?: string; poster_path?: string; profile_path?: string }

async function fetchTmdb(endpoint: string, apiKey: string, pages: number): Promise<TmdbItem[]> {
    const results: TmdbItem[] = []
    await Promise.all(
        Array.from({ length: pages }, (_, i) =>
            fetch(
                `https://api.themoviedb.org/3/${endpoint}?api_key=${apiKey}&language=en-US&page=${i + 1}`,
            )
                .then((r) => r.json())
                .then((d) => results.push(...(d.results ?? []))),
        ),
    )
    return results
}

async function fetchMovies(apiKey: string): Promise<string> {
    const results = await fetchTmdb('movie/top_rated', apiKey, 5)

    const characters = results
        .filter((m) => m.poster_path)
        .map((m) => ({
            name: m.title!,
            imageUrl: `https://image.tmdb.org/t/p/w500${m.poster_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Movies: ${characters.length} movies`)
    return header + `export const movieCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchTvShows(apiKey: string): Promise<string> {
    const results = await fetchTmdb('tv/top_rated', apiKey, 5)

    const characters = results
        .filter((s) => s.poster_path)
        .map((s) => ({
            name: s.name!,
            imageUrl: `https://image.tmdb.org/t/p/w500${s.poster_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`TV Shows: ${characters.length} shows`)
    return header + `export const tvShowCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchPeople(apiKey: string): Promise<string> {
    const results = await fetchTmdb('person/popular', apiKey, 3)

    const characters = results
        .filter((p) => p.profile_path)
        .slice(0, 50)
        .map((p) => ({
            name: p.name!,
            imageUrl: `https://image.tmdb.org/t/p/w500${p.profile_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`People: ${characters.length} people`)
    return header + `export const peopleCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchNaruto(): Promise<string> {
    const first = await fetch('https://dattebayo-api.onrender.com/characters?limit=100').then(
        (r) => r.json(),
    )

    const results = [...first.characters]
    const totalPages = Math.ceil(first.total / 100)

    await Promise.all(
        Array.from({ length: totalPages - 1 }, (_, i) =>
            fetch(`https://dattebayo-api.onrender.com/characters?limit=100&page=${i + 2}`)
                .then((r) => r.json())
                .then((d) => results.push(...d.characters)),
        ),
    )

    const characters = (results as { name: string; images: string[] }[])
        .filter((c) => c.images.length > 0)
        .slice(0, 60)
        .map(({ name, images }) => ({ name, imageUrl: images[0] }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Naruto: ${characters.length} characters`)
    return (
        header + `export const narutoCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchJikanAnime(animeId: number, limit: number): Promise<{ name: string; imageUrl: string }[]> {
    const data = await fetch(
        `https://api.jikan.moe/v4/anime/${animeId}/characters`,
    ).then((r) => r.json())

    return (data.data as { character: { name: string; images: { jpg: { image_url: string } } }; favorites: number }[])
        .filter((c) => c.character.images?.jpg?.image_url)
        .sort((a, b) => b.favorites - a.favorites)
        .slice(0, limit)
        .map((c) => ({
            name: c.character.name.includes(', ')
                ? c.character.name.split(', ').reverse().join(' ')
                : c.character.name,
            imageUrl: c.character.images.jpg.image_url,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))
}

async function fetchOnePiece(): Promise<string> {
    const characters = await fetchJikanAnime(21, 60)
    console.log(`One Piece: ${characters.length} characters`)
    return header + `export const onePieceCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchAttackOnTitan(): Promise<string> {
    const characters = await fetchJikanAnime(16498, 40)
    console.log(`Attack on Titan: ${characters.length} characters`)
    return header + `export const attackOnTitanCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchDemonSlayer(): Promise<string> {
    const characters = await fetchJikanAnime(38000, 40)
    console.log(`Demon Slayer: ${characters.length} characters`)
    return header + `export const demonSlayerCharacters: Character[] = ${serialize(characters)}\n`
}

async function main() {
    const tmdbApiKey = process.env.TMDB_API_KEY
    if (!tmdbApiKey) throw new Error('TMDB_API_KEY env variable is required')

    console.log('Generating character data...\n')

    const [lol, dota2, valorant, flags, pokemon, fortnite, genshin, rickAndMorty, overwatch, dragonBall, naruto, movies, tvShows, people] =
        await Promise.all([
            fetchLol(),
            fetchDota2(),
            fetchValorant(),
            fetchFlags(),
            fetchPokemon(),
            fetchFortnite(),
            fetchGenshin(),
            fetchRickAndMorty(),
            fetchOverwatch(),
            fetchDragonBall(),
            fetchNaruto(),
            fetchMovies(tmdbApiKey),
            fetchTvShows(tmdbApiKey),
            fetchPeople(tmdbApiKey),
        ])

    // Jikan API has rate limiting, fetch sequentially
    const onePiece = await fetchOnePiece()
    await new Promise((r) => setTimeout(r, 1000))
    const attackOnTitan = await fetchAttackOnTitan()
    await new Promise((r) => setTimeout(r, 1000))
    const demonSlayer = await fetchDemonSlayer()

    writeFileSync(join(OUT_DIR, 'league-of-legends.ts'), lol)
    writeFileSync(join(OUT_DIR, 'dota-2.ts'), dota2)
    writeFileSync(join(OUT_DIR, 'valorant.ts'), valorant)
    writeFileSync(join(OUT_DIR, 'flags.ts'), flags)
    writeFileSync(join(OUT_DIR, 'pokemon.ts'), pokemon)
    writeFileSync(join(OUT_DIR, 'fortnite.ts'), fortnite)
    writeFileSync(join(OUT_DIR, 'genshin.ts'), genshin)
    writeFileSync(join(OUT_DIR, 'rick-and-morty.ts'), rickAndMorty)
    writeFileSync(join(OUT_DIR, 'overwatch.ts'), overwatch)
    writeFileSync(join(OUT_DIR, 'dragon-ball.ts'), dragonBall)
    writeFileSync(join(OUT_DIR, 'naruto.ts'), naruto)
    writeFileSync(join(OUT_DIR, 'movies.ts'), movies)
    writeFileSync(join(OUT_DIR, 'tv-shows.ts'), tvShows)
    writeFileSync(join(OUT_DIR, 'people.ts'), people)
    writeFileSync(join(OUT_DIR, 'one-piece.ts'), onePiece)
    writeFileSync(join(OUT_DIR, 'attack-on-titan.ts'), attackOnTitan)
    writeFileSync(join(OUT_DIR, 'demon-slayer.ts'), demonSlayer)

    console.log('\nDone! Files written to src/data/characters/')
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
