import { writeFileSync } from 'fs'
import { join } from 'path'

const OUT_DIR = join(import.meta.dir, '../src/data/characters')

const header = `// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

`

const PRINT_WIDTH = 80

function serializeString(s: string): string {
    if (s.includes("'")) return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
    return `'${s.replace(/\\/g, '\\\\')}'`
}

function serialize(chars: { name: string; imageUrl: string }[]): string {
    const items = chars.map(({ name, imageUrl }) => {
        const nameStr = serializeString(name)
        const urlStr = serializeString(imageUrl)
        const urlLine = `        imageUrl: ${urlStr},`
        const urlFormatted =
            urlLine.length > PRINT_WIDTH
                ? `        imageUrl:\n            ${urlStr},`
                : urlLine
        return `    {\n        name: ${nameStr},\n${urlFormatted}\n    }`
    })
    return `[\n${items.join(',\n')},\n]`
}

async function fetchLol(): Promise<string> {
    const versions: string[] = await fetch(
        'https://ddragon.leagueoflegends.com/api/versions.json',
    ).then((r) => r.json())

    const version = versions[0]
    const data = await fetch(
        `https://ddragon.leagueoflegends.com/cdn/${version}/data/en_US/champion.json`,
    ).then((r) => r.json())

    const champions = Object.values(data.data as Record<string, { name: string; id: string }>)
        .map(({ name, id }) => ({
            name,
            imageUrl: `https://ddragon.leagueoflegends.com/cdn/${version}/img/champion/${id}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`LoL: ${champions.length} champions (v${version})`)
    return (
        header +
        `export const leagueOfLegendsCharacters: Character[] = ${serialize(champions)}\n`
    )
}

async function fetchDota2(): Promise<string> {
    const heroes: { localized_name: string; name: string }[] = await fetch(
        'https://api.opendota.com/api/heroes',
    ).then((r) => r.json())

    const characters = heroes
        .map(({ localized_name, name }) => ({
            name: localized_name,
            imageUrl: `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${name.replace('npc_dota_hero_', '')}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Dota 2: ${characters.length} heroes`)
    return (
        header + `export const dota2Characters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchValorant(): Promise<string> {
    const data = await fetch(
        'https://valorant-api.com/v1/agents?isPlayableCharacter=true',
    ).then((r) => r.json())

    const characters = (data.data as { displayName: string; uuid: string }[])
        .map(({ displayName, uuid }) => ({
            name: displayName,
            imageUrl: `https://media.valorant-api.com/agents/${uuid}/displayicon.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Valorant: ${characters.length} agents`)
    return (
        header + `export const valorantCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchFlags(): Promise<string> {
    const codes: Record<string, string> = await fetch(
        'https://flagcdn.com/en/codes.json',
    ).then((r) => r.json())

    const exclude = new Set([
        'ac', 'cp', 'dg', 'ea', 'eu', 'hm', 'ic', 'sh', 'sj', 'ta', 'un',
        'xk', 'bv', 'aq', 'tf', 'gs', 'io', 'um',
    ])

    const characters = Object.entries(codes)
        .filter(([code]) => code.length === 2 && !exclude.has(code))
        .map(([code, name]) => ({
            name,
            imageUrl: `https://flagcdn.com/w1280/${code}.webp`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Flags: ${characters.length} countries`)
    return (
        header + `export const flagCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function main() {
    console.log('Generating character data...\n')

    const [lol, dota2, valorant, flags] = await Promise.all([
        fetchLol(),
        fetchDota2(),
        fetchValorant(),
        fetchFlags(),
    ])

    writeFileSync(join(OUT_DIR, 'league-of-legends.ts'), lol)
    writeFileSync(join(OUT_DIR, 'dota-2.ts'), dota2)
    writeFileSync(join(OUT_DIR, 'valorant.ts'), valorant)
    writeFileSync(join(OUT_DIR, 'flags.ts'), flags)

    console.log('\nDone! Files written to src/data/characters/')
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
