import { writeFileSync } from 'fs'
import { join } from 'path'

const OUT_DIR = join(import.meta.dir, '../src/data/characters')

async function safeJson(url: string, options?: RequestInit, retries = 3): Promise<any> {
    for (let i = 0; i < retries; i++) {
        const r = await fetch(url, options)
        const text = await r.text()
        try {
            return JSON.parse(text)
        } catch {
            if (i < retries - 1) {
                console.warn(`JSON parse failed for ${url}, retrying (${i + 1}/${retries})...`)
                await new Promise((res) => setTimeout(res, 2000))
            } else {
                throw new Error(`Failed to parse JSON from ${url}: ${text.slice(0, 100)}`)
            }
        }
    }
}

const header = `// Auto-generated by scripts/generate-characters.ts — do not edit manually
import type { Character } from '../../types'

`

const PRINT_WIDTH = 80

function serializeString(s: string): string {
    if (s.includes("'")) return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
    return `'${s.replace(/\\/g, '\\\\')}'`
}

function serialize(chars: { name: string; imageUrl: string }[]): string {
    const items = chars.map(({ name, imageUrl }) => {
        const nameStr = serializeString(name)
        const urlStr = serializeString(imageUrl)
        const urlLine = `        imageUrl: ${urlStr},`
        const urlFormatted =
            urlLine.length > PRINT_WIDTH
                ? `        imageUrl:\n            ${urlStr},`
                : urlLine
        return `    {\n        name: ${nameStr},\n${urlFormatted}\n    }`
    })
    return `[\n${items.join(',\n')},\n]`
}

async function fetchLol(): Promise<string> {
    const versions: string[] = await fetch(
        'https://ddragon.leagueoflegends.com/api/versions.json',
    ).then((r) => r.json())

    const version = versions[0]
    const data = await fetch(
        `https://ddragon.leagueoflegends.com/cdn/${version}/data/en_US/champion.json`,
    ).then((r) => r.json())

    const champions = Object.values(data.data as Record<string, { name: string; id: string }>)
        .map(({ name, id }) => ({
            name,
            imageUrl: `https://ddragon.leagueoflegends.com/cdn/${version}/img/champion/${id}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`LoL: ${champions.length} champions (v${version})`)
    return (
        header +
        `export const leagueOfLegendsCharacters: Character[] = ${serialize(champions)}\n`
    )
}

async function fetchDota2(): Promise<string> {
    const heroes: { localized_name: string; name: string }[] = await fetch(
        'https://api.opendota.com/api/heroes',
    ).then((r) => r.json())

    const characters = heroes
        .map(({ localized_name, name }) => ({
            name: localized_name,
            imageUrl: `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${name.replace('npc_dota_hero_', '')}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Dota 2: ${characters.length} heroes`)
    return (
        header + `export const dota2Characters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchValorant(): Promise<string> {
    const data = await fetch(
        'https://valorant-api.com/v1/agents?isPlayableCharacter=true',
    ).then((r) => r.json())

    const characters = (data.data as { displayName: string; uuid: string }[])
        .map(({ displayName, uuid }) => ({
            name: displayName,
            imageUrl: `https://media.valorant-api.com/agents/${uuid}/displayicon.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Valorant: ${characters.length} agents`)
    return (
        header + `export const valorantCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchFlags(): Promise<string> {
    const codes: Record<string, string> = await fetch(
        'https://flagcdn.com/en/codes.json',
    ).then((r) => r.json())

    const exclude = new Set([
        'ac', 'cp', 'dg', 'ea', 'eu', 'hm', 'ic', 'sh', 'sj', 'ta', 'un',
        'xk', 'bv', 'aq', 'tf', 'gs', 'io', 'um',
    ])

    const characters = Object.entries(codes)
        .filter(([code]) => code.length === 2 && !exclude.has(code))
        .map(([code, name]) => ({
            name,
            imageUrl: `https://flagcdn.com/w1280/${code}.webp`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Flags: ${characters.length} countries`)
    return (
        header + `export const flagCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchPokemon(): Promise<string> {
    const data = await fetch(
        'https://pokeapi.co/api/v2/pokemon?limit=1025',
    ).then((r) => r.json())

    const characters = (data.results as { name: string; url: string }[])
        .slice(0, 151)
        .map(({ name, url }) => {
            const id = url.split('/').filter(Boolean).pop()!
            return {
                name: name.charAt(0).toUpperCase() + name.slice(1).replace(/-/g, ' '),
                imageUrl: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`,
            }
        })

    console.log(`Pokémon: ${characters.length} pokémon`)
    return (
        header + `export const pokemonCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchFortnite(): Promise<string> {
    const data = await fetch(
        'https://fortnite-api.com/v2/cosmetics/br?language=en',
    ).then((r) => r.json())

    const characters = (
        data.data as {
            name: string
            type: { value: string }
            rarity: { value: string }
            images: { icon?: string; featured?: string }
        }[]
    )
        .filter(
            (x) =>
                x.type?.value === 'outfit' &&
                x.rarity?.value === 'legendary' &&
                x.images?.featured,
        )
        .map(({ name, images }) => ({
            name,
            imageUrl: images.featured!,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Fortnite: ${characters.length} outfits`)
    return (
        header + `export const fortniteCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchGenshin(): Promise<string> {
    const data = await fetch('https://gi.yatta.moe/api/v2/en/avatar').then((r) => r.json())

    const characters = Object.values(
        data.data.items as Record<string, { name: string; icon: string }>,
    )
        .map(({ name, icon }) => ({
            name,
            imageUrl: `https://gi.yatta.moe/assets/UI/${icon}.png`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Genshin Impact: ${characters.length} characters`)
    return (
        header + `export const genshinCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchRickAndMorty(): Promise<string> {
    const first = await fetch('https://rickandmortyapi.com/api/character').then((r) => r.json())
    const pages: number = first.info.pages

    const results = [...first.results]
    await Promise.all(
        Array.from({ length: pages - 1 }, (_, i) =>
            fetch(`https://rickandmortyapi.com/api/character?page=${i + 2}`)
                .then((r) => r.json())
                .then((d) => results.push(...d.results)),
        ),
    )

    const characters = (results as { name: string; image: string; episode: string[] }[])
        .filter((c) => c.episode.length >= 3)
        .map(({ name, image }) => ({ name, imageUrl: image }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Rick & Morty: ${characters.length} characters`)
    return (
        header +
        `export const rickAndMortyCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchOverwatch(): Promise<string> {
    const data = await fetch('https://overfast-api.tekrop.fr/heroes').then((r) => r.json())

    const characters = (data as { name: string; portrait: string }[])
        .map(({ name, portrait }) => ({ name, imageUrl: portrait }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Overwatch: ${characters.length} heroes`)
    return (
        header + `export const overwatchCharacters: Character[] = ${serialize(characters)}\n`
    )
}

async function fetchDragonBall(): Promise<string> {
    const data = await fetch(
        'https://dragonball-api.com/api/characters?limit=100',
    ).then((r) => r.json())

    const characters = (data.items as { name: string; image: string }[])
        .map(({ name, image }) => ({ name, imageUrl: image }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Dragon Ball: ${characters.length} characters`)
    return (
        header + `export const dragonBallCharacters: Character[] = ${serialize(characters)}\n`
    )
}

type TmdbItem = { title?: string; name?: string; poster_path?: string; profile_path?: string }

async function fetchTmdb(endpoint: string, apiKey: string, pages: number): Promise<TmdbItem[]> {
    const results: TmdbItem[] = []
    await Promise.all(
        Array.from({ length: pages }, (_, i) =>
            fetch(
                `https://api.themoviedb.org/3/${endpoint}?api_key=${apiKey}&language=en-US&page=${i + 1}`,
            )
                .then((r) => r.json())
                .then((d) => results.push(...(d.results ?? []))),
        ),
    )
    return results
}

async function fetchTmdbDiscover(endpoint: string, apiKey: string, pages: number, extraParams: string): Promise<TmdbItem[]> {
    const results: TmdbItem[] = []
    await Promise.all(
        Array.from({ length: pages }, (_, i) =>
            fetch(
                `https://api.themoviedb.org/3/${endpoint}?api_key=${apiKey}&language=en-US&sort_by=popularity.desc&page=${i + 1}${extraParams}`,
            )
                .then((r) => r.json())
                .then((d) => results.push(...(d.results ?? []))),
        ),
    )
    return results
}

async function fetchMovies(apiKey: string): Promise<string> {
    const results = await fetchTmdbDiscover(
        'discover/movie',
        apiKey,
        5,
        '&vote_count.gte=1000&with_original_language=en'
    )

    const characters = results
        .filter((m) => m.poster_path)
        .map((m) => ({
            name: m.title!,
            imageUrl: `https://image.tmdb.org/t/p/w500${m.poster_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Movies: ${characters.length} movies`)
    return header + `export const movieCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchTvShows(apiKey: string): Promise<string> {
    const results = await fetchTmdbDiscover(
        'discover/tv',
        apiKey,
        5,
        '&vote_count.gte=500&with_original_language=en'
    )

    const characters = results
        .filter((s) => s.poster_path)
        .map((s) => ({
            name: s.name!,
            imageUrl: `https://image.tmdb.org/t/p/w500${s.poster_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`TV Shows: ${characters.length} shows`)
    return header + `export const tvShowCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchPeople(apiKey: string): Promise<string> {
    const results = await fetchTmdb('person/popular', apiKey, 3)

    const characters = results
        .filter((p) => p.profile_path)
        .slice(0, 50)
        .map((p) => ({
            name: p.name!,
            imageUrl: `https://image.tmdb.org/t/p/w500${p.profile_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`People: ${characters.length} people`)
    return header + `export const peopleCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchNaruto(): Promise<string> {
    const first = await safeJson('https://dattebayo-api.onrender.com/characters?limit=100')

    const results = [...first.characters]
    const totalPages = Math.ceil(first.total / 100)

    await Promise.all(
        Array.from({ length: totalPages - 1 }, (_, i) =>
            safeJson(`https://dattebayo-api.onrender.com/characters?limit=100&page=${i + 2}`)
                .then((d) => results.push(...d.characters)),
        ),
    )

    const characters = (results as { name: string; images: string[] }[])
        .filter((c) => c.images.length > 0)
        .slice(0, 60)
        .map(({ name, images }) => ({ name, imageUrl: images[0] }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Naruto: ${characters.length} characters`)
    return (
        header + `export const narutoCharacters: Character[] = ${serialize(characters)}\n`
    )
}

const BRANDS = [
    { name: 'Apple', domain: 'apple.com' },
    { name: 'Google', domain: 'google.com' },
    { name: 'Microsoft', domain: 'microsoft.com' },
    { name: 'Amazon', domain: 'amazon.com' },
    { name: 'Meta', domain: 'meta.com' },
    { name: 'Netflix', domain: 'netflix.com' },
    { name: 'Spotify', domain: 'spotify.com' },
    { name: 'YouTube', domain: 'youtube.com' },
    { name: 'Instagram', domain: 'instagram.com' },
    { name: 'Twitter', domain: 'twitter.com' },
    { name: 'TikTok', domain: 'tiktok.com' },
    { name: 'Snapchat', domain: 'snapchat.com' },
    { name: 'WhatsApp', domain: 'whatsapp.com' },
    { name: 'LinkedIn', domain: 'linkedin.com' },
    { name: 'Reddit', domain: 'reddit.com' },
    { name: 'Twitch', domain: 'twitch.tv' },
    { name: 'Discord', domain: 'discord.com' },
    { name: 'Tesla', domain: 'tesla.com' },
    { name: 'Nike', domain: 'nike.com' },
    { name: 'Adidas', domain: 'adidas.com' },
    { name: 'Puma', domain: 'puma.com' },
    { name: 'Coca-Cola', domain: 'coca-cola.com' },
    { name: 'Pepsi', domain: 'pepsi.com' },
    { name: "McDonald's", domain: 'mcdonalds.com' },
    { name: 'Starbucks', domain: 'starbucks.com' },
    { name: 'KFC', domain: 'kfc.com' },
    { name: 'Burger King', domain: 'burgerking.com' },
    { name: 'Subway', domain: 'subway.com' },
    { name: 'Domino\'s', domain: 'dominos.com' },
    { name: 'Disney', domain: 'disney.com' },
    { name: 'Marvel', domain: 'marvel.com' },
    { name: 'Nintendo', domain: 'nintendo.com' },
    { name: 'PlayStation', domain: 'playstation.com' },
    { name: 'Xbox', domain: 'xbox.com' },
    { name: 'Steam', domain: 'steampowered.com' },
    { name: 'Epic Games', domain: 'epicgames.com' },
    { name: 'EA Sports', domain: 'ea.com' },
    { name: 'Ubisoft', domain: 'ubisoft.com' },
    { name: 'BMW', domain: 'bmw.com' },
    { name: 'Mercedes-Benz', domain: 'mercedes-benz.com' },
    { name: 'Audi', domain: 'audi.com' },
    { name: 'Volkswagen', domain: 'vw.com' },
    { name: 'Toyota', domain: 'toyota.com' },
    { name: 'Ferrari', domain: 'ferrari.com' },
    { name: 'Lamborghini', domain: 'lamborghini.com' },
    { name: 'Porsche', domain: 'porsche.com' },
    { name: 'Ford', domain: 'ford.com' },
    { name: 'Samsung', domain: 'samsung.com' },
    { name: 'Sony', domain: 'sony.com' },
    { name: 'LG', domain: 'lg.com' },
    { name: 'Intel', domain: 'intel.com' },
    { name: 'Nvidia', domain: 'nvidia.com' },
    { name: 'AMD', domain: 'amd.com' },
    { name: 'Visa', domain: 'visa.com' },
    { name: 'Mastercard', domain: 'mastercard.com' },
    { name: 'PayPal', domain: 'paypal.com' },
    { name: 'Airbnb', domain: 'airbnb.com' },
    { name: 'Uber', domain: 'uber.com' },
    { name: 'Shopify', domain: 'shopify.com' },
]

async function fetchBrands(): Promise<string> {
    const characters = BRANDS
        .map(({ name, domain }) => ({
            name,
            imageUrl: `https://img.logo.dev/${domain}?token=pk_eQWznTEVSQWtTwGzi_p5Qg&format=png&theme=dark`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Brands: ${characters.length} brands`)
    return header + `export const brandCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchFootball(apiKey: string): Promise<string> {
    const competitions = ['PL', 'PD', 'BL1', 'SA', 'FL1']
    const teamMap = new Map<number, { name: string; crest: string }>()

    await Promise.all(
        competitions.map((code) =>
            safeJson(`https://api.football-data.org/v4/competitions/${code}/teams`, {
                headers: { 'X-Auth-Token': apiKey },
            })
                .then((d) => {
                    if (d.teams) {
                        for (const t of d.teams as { id: number; name: string; crest: string }[]) {
                            if (t.crest) teamMap.set(t.id, { name: t.name, crest: t.crest })
                        }
                    }
                }),
        ),
    )

    const characters = Array.from(teamMap.values())
        .map(({ name, crest }) => ({ name, imageUrl: crest }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Football: ${characters.length} clubs`)
    return header + `export const footballCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchJikanAnime(animeId: number, limit: number): Promise<{ name: string; imageUrl: string }[]> {
    const data = await fetch(
        `https://api.jikan.moe/v4/anime/${animeId}/characters`,
    ).then((r) => r.json())

    return (data.data as { character: { name: string; images: { jpg: { image_url: string } } }; favorites: number }[])
        .filter((c) => c.character.images?.jpg?.image_url)
        .sort((a, b) => b.favorites - a.favorites)
        .slice(0, limit)
        .map((c) => ({
            name: c.character.name.includes(', ')
                ? c.character.name.split(', ').reverse().join(' ')
                : c.character.name,
            imageUrl: c.character.images.jpg.image_url,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))
}

async function fetchOnePiece(): Promise<string> {
    const characters = await fetchJikanAnime(21, 60)
    console.log(`One Piece: ${characters.length} characters`)
    return header + `export const onePieceCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchAttackOnTitan(): Promise<string> {
    const characters = await fetchJikanAnime(16498, 40)
    console.log(`Attack on Titan: ${characters.length} characters`)
    return header + `export const attackOnTitanCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchDemonSlayer(): Promise<string> {
    const characters = await fetchJikanAnime(38000, 40)
    console.log(`Demon Slayer: ${characters.length} characters`)
    return header + `export const demonSlayerCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchJujutsuKaisen(): Promise<string> {
    const characters = await fetchJikanAnime(40748, 40)
    console.log(`Jujutsu Kaisen: ${characters.length} characters`)
    return header + `export const jujutsuKaisenCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchMyHeroAcademia(): Promise<string> {
    const characters = await fetchJikanAnime(31964, 40)
    console.log(`My Hero Academia: ${characters.length} characters`)
    return header + `export const myHeroAcademiaCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchDeathNote(): Promise<string> {
    const characters = await fetchJikanAnime(1535, 30)
    console.log(`Death Note: ${characters.length} characters`)
    return header + `export const deathNoteCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchFullmetalAlchemist(): Promise<string> {
    const characters = await fetchJikanAnime(5114, 40)
    console.log(`FMA Brotherhood: ${characters.length} characters`)
    return header + `export const fullmetalAlchemistCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchHunterXHunter(): Promise<string> {
    const characters = await fetchJikanAnime(11061, 40)
    console.log(`Hunter x Hunter: ${characters.length} characters`)
    return header + `export const hunterXHunterCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchAnimeSeries(tmdbApiKey: string): Promise<string> {
    const results: { name: string; poster_path: string | null }[] = []
    for (let page = 1; page <= 4; page++) {
        const data = await fetch(
            `https://api.themoviedb.org/3/discover/tv?api_key=${tmdbApiKey}&with_genres=16&with_original_language=ja&sort_by=popularity.desc&page=${page}`,
        ).then((r) => r.json())
        results.push(...(data.results ?? []))
    }

    const characters = results
        .filter((a) => a.poster_path)
        .slice(0, 80)
        .map((a) => ({
            name: a.name,
            imageUrl: `https://image.tmdb.org/t/p/w500${a.poster_path}`,
        }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Anime Series: ${characters.length} anime`)
    return header + `export const animeSeriesCharacters: Character[] = ${serialize(characters)}\n`
}

async function fetchHarryPotter(): Promise<string> {
    const data = await safeJson('https://hp-api.onrender.com/api/characters')
    const characters = (data as { name: string; image: string }[])
        .filter((c) => c.image)
        .slice(0, 50)
        .map((c) => ({ name: c.name, imageUrl: c.image }))
        .sort((a, b) => a.name.localeCompare(b.name))

    console.log(`Harry Potter: ${characters.length} characters`)
    return header + `export const harryPotterCharacters: Character[] = ${serialize(characters)}\n`
}

async function main() {
    const tmdbApiKey = process.env.TMDB_API_KEY
    if (!tmdbApiKey) throw new Error('TMDB_API_KEY env variable is required')
    const footballApiKey = process.env.FOOTBALL_DATA_API_KEY
    if (!footballApiKey) throw new Error('FOOTBALL_DATA_API_KEY env variable is required')

    console.log('Generating character data...\n')

    const [lol, dota2, valorant, flags, pokemon, fortnite, genshin, rickAndMorty, overwatch, dragonBall, naruto, movies, tvShows, people, brands, football, animeSeries, harryPotter] =
        await Promise.all([
            fetchLol(),
            fetchDota2(),
            fetchValorant(),
            fetchFlags(),
            fetchPokemon(),
            fetchFortnite(),
            fetchGenshin(),
            fetchRickAndMorty(),
            fetchOverwatch(),
            fetchDragonBall(),
            fetchNaruto(),
            fetchMovies(tmdbApiKey),
            fetchTvShows(tmdbApiKey),
            fetchPeople(tmdbApiKey),
            fetchBrands(),
            fetchFootball(footballApiKey),
            fetchAnimeSeries(tmdbApiKey),
            fetchHarryPotter(),
        ])

    // Jikan API has rate limiting, fetch sequentially
    const onePiece = await fetchOnePiece()
    await new Promise((r) => setTimeout(r, 1000))
    const attackOnTitan = await fetchAttackOnTitan()
    await new Promise((r) => setTimeout(r, 1000))
    const demonSlayer = await fetchDemonSlayer()
    await new Promise((r) => setTimeout(r, 1000))
    const jujutsuKaisen = await fetchJujutsuKaisen()
    await new Promise((r) => setTimeout(r, 1000))
    const myHeroAcademia = await fetchMyHeroAcademia()
    await new Promise((r) => setTimeout(r, 1000))
    const deathNote = await fetchDeathNote()
    await new Promise((r) => setTimeout(r, 1000))
    const fullmetalAlchemist = await fetchFullmetalAlchemist()
    await new Promise((r) => setTimeout(r, 1000))
    const hunterXHunter = await fetchHunterXHunter()

    writeFileSync(join(OUT_DIR, 'league-of-legends.ts'), lol)
    writeFileSync(join(OUT_DIR, 'dota-2.ts'), dota2)
    writeFileSync(join(OUT_DIR, 'valorant.ts'), valorant)
    writeFileSync(join(OUT_DIR, 'flags.ts'), flags)
    writeFileSync(join(OUT_DIR, 'pokemon.ts'), pokemon)
    writeFileSync(join(OUT_DIR, 'fortnite.ts'), fortnite)
    writeFileSync(join(OUT_DIR, 'genshin.ts'), genshin)
    writeFileSync(join(OUT_DIR, 'rick-and-morty.ts'), rickAndMorty)
    writeFileSync(join(OUT_DIR, 'overwatch.ts'), overwatch)
    writeFileSync(join(OUT_DIR, 'dragon-ball.ts'), dragonBall)
    writeFileSync(join(OUT_DIR, 'naruto.ts'), naruto)
    writeFileSync(join(OUT_DIR, 'movies.ts'), movies)
    writeFileSync(join(OUT_DIR, 'tv-shows.ts'), tvShows)
    writeFileSync(join(OUT_DIR, 'people.ts'), people)
    writeFileSync(join(OUT_DIR, 'brands.ts'), brands)
    writeFileSync(join(OUT_DIR, 'football.ts'), football)
    writeFileSync(join(OUT_DIR, 'one-piece.ts'), onePiece)
    writeFileSync(join(OUT_DIR, 'attack-on-titan.ts'), attackOnTitan)
    writeFileSync(join(OUT_DIR, 'demon-slayer.ts'), demonSlayer)
    writeFileSync(join(OUT_DIR, 'jujutsu-kaisen.ts'), jujutsuKaisen)
    writeFileSync(join(OUT_DIR, 'my-hero-academia.ts'), myHeroAcademia)
    writeFileSync(join(OUT_DIR, 'death-note.ts'), deathNote)
    writeFileSync(join(OUT_DIR, 'fullmetal-alchemist.ts'), fullmetalAlchemist)
    writeFileSync(join(OUT_DIR, 'hunter-x-hunter.ts'), hunterXHunter)
    writeFileSync(join(OUT_DIR, 'anime-series.ts'), animeSeries)
    writeFileSync(join(OUT_DIR, 'harry-potter.ts'), harryPotter)

    console.log('\nDone! Files written to src/data/characters/')
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
